-- liquibase formatted sql

-- changeset root:1753259493085-62
CREATE OR REPLACE FORCE VIEW LOG_V_VIS_LAST_SCHED_JOB_DA_DROPPARE (ID_LOG_JOB, NM_JOB, DT_REG_LOG_JOB_INI, FL_JOB_ATTIVO, LAST_EXEC_OK) AS select max (tab1.id_log_job), tab1.nm_job,tab1.dt_reg_log_job_ini, tab1.fl_job_attivo,tab1.LAST_EXEC_OK
  from (
  SELECT inizio_job.id_log_job,
           inizio_job.nm_job,
           inizio_job.dt_reg_log_job    dt_reg_log_job_ini,
           CASE
               WHEN EXISTS
                        (SELECT *
                           FROM LOG_JOB fine_job
                          WHERE fine_job.nm_job = inizio_job.nm_job
                            AND fine_job.ti_reg_log_job IN
                                    ('FINE_SCHEDULAZIONE', 'ERRORE')
                            AND fine_job.dt_reg_log_job >=
                                inizio_job.dt_reg_log_job) THEN
                   '0'
               ELSE
                   '1'
           END                          fl_job_attivo,
           CASE
               WHEN EXISTS
                        (SELECT *
                           FROM LOG_JOB fine_job
                          WHERE fine_job.nm_job = inizio_job.nm_job
                            AND fine_job.ti_reg_log_job IN
                                    ('FINE_SCHEDULAZIONE')
                            AND fine_job.dt_reg_log_job >=
                                inizio_job.dt_reg_log_job) THEN
                   '1'
               ELSE
                   '0'
           END                          last_exec_ok
      FROM LOG_JOB inizio_job
     WHERE inizio_job.ti_reg_log_job = 'INIZIO_SCHEDULAZIONE'
       AND inizio_job.dt_reg_log_job =
           (SELECT MAX (inizio_job_max.dt_reg_log_job)
              FROM LOG_JOB inizio_job_max
             WHERE inizio_job_max.nm_job = inizio_job.nm_job
               AND inizio_job_max.ti_reg_log_job = 'INIZIO_SCHEDULAZIONE'
               )) tab1
group by  tab1.nm_job,tab1.dt_reg_log_job_ini, tab1.fl_job_attivo,tab1.LAST_EXEC_OK;

-- changeset root:1753259493085-63
COMMENT ON COLUMN LOG_V_VIS_LAST_SCHED_JOB_DA_DROPPARE.ID_LOG_JOB IS 'PK.1 relativa a tabella LOG_JOB';

-- changeset root:1753259493085-64
CREATE TABLE TMP_AGG_PRAMETRI_ACCORDO (NM_ENTE_SIAM VARCHAR2(254 BYTE) NOT NULL, NM_AMBIENTE_ENTE_CONVENZ VARCHAR2(100 BYTE) NOT NULL, ID_ACCORDO_ENTE NUMBER NOT NULL, NM_AMBIENTE VARCHAR2(100 BYTE), NM_ENTE VARCHAR2(100 BYTE), NM_STRUT VARCHAR2(100 BYTE), NM_ENTE_ACC VARCHAR2(254 BYTE) NOT NULL, NM_STRUT_ACC VARCHAR2(254 BYTE) NOT NULL, NM_AMBIENTE_ACC VARCHAR2(100 BYTE));

-- changeset root:1753259493085-65
CREATE TABLE TMP_ARK_FORNIT (ID_ENTE_ARK_RIF NUMBER, ID_ENTE_CONVENZ NUMBER NOT NULL, ID_USER_IAM NUMBER NOT NULL);

-- changeset root:1753259493085-66
CREATE TABLE TMP_COLLEG_ENTI (ID_ENTE_SIAM NUMBER NOT NULL, NM_ENTE_SIAM VARCHAR2(254 BYTE) NOT NULL, ID_AMBITO_TERRIT NUMBER NOT NULL, CD_AMBITO_TERRIT VARCHAR2(100 BYTE), DT_INI_VAL date NOT NULL, DT_CESSAZIONE date);

-- changeset root:1753259493085-67
CREATE TABLE TMP_COLLEG_ENTI_FUSI (ID_ENTE_SIAM NUMBER, NM_ENTE_SIAM VARCHAR2(254 BYTE), NM_COLLEG VARCHAR2(265 BYTE), FL_CAPOFILA CHAR(1 BYTE), DT_INI_VAL date, DT_FIN_VAL date);

-- changeset root:1753259493085-68
CREATE TABLE TMP_CONSERV_DA_CREARE (ID_ENTE_CONSERV NUMBER, NM_CONSERV CHAR(19 BYTE), DS_VIA_SEDE_LEGALE CHAR(6 BYTE), CD_CAP_SEDE_LEGALE CHAR(5 BYTE), DS_CITTA_SEDE_LEGALE CHAR(6 BYTE), ID_PROV_SEDE_LEGALE NUMBER, CD_NAZIONE_SEDE_LEGALE CHAR(2 BYTE), ID_AMBITO_TERRIT NUMBER, TI_CD_ENTE_CONVENZ CHAR(5 BYTE), CD_ENTE_CONVENZ CHAR(14 BYTE), ID_CATEG_ENTE NUMBER, ID_AMBIENTE_ENTE_CONVENZ NUMBER NOT NULL, DT_DEC_ACCORDO date, ID_TIPO_ACCORDO NUMBER, ID_CLASSE_ENTE_CONVENZ NUMBER, DT_SCAD_ACCORDO date, FL_PAGAMENTO CHAR(1 BYTE));

-- changeset root:1753259493085-69
CREATE TABLE TMP_DICH_AUTOR (NM_RUOLO VARCHAR2(100 BYTE) NOT NULL, NM_APPLIC VARCHAR2(100 BYTE) NOT NULL, TI_DICH_AUTOR VARCHAR2(20 BYTE) NOT NULL, TI_SCOPO_DICH_AUTOR VARCHAR2(22 BYTE) NOT NULL, NM_ENTRY_MENU_PADRE VARCHAR2(100 BYTE), NM_ENTRY_MENU_FOGLIA VARCHAR2(100 BYTE), NM_PAGINA_WEB VARCHAR2(100 BYTE), NM_AZIONE_PAGINA VARCHAR2(100 BYTE), NM_SERVIZIO_WEB VARCHAR2(100 BYTE));

-- changeset root:1753259493085-70
CREATE TABLE TMP_ENTE_CONVENZ_ENTE_SACER (ENTE VARCHAR2(100 BYTE) NOT NULL, ID_ENTE_SIAM NUMBER, ID_ENTE_SACER NUMBER NOT NULL, NM_ENTE_SACER VARCHAR2(100 BYTE) NOT NULL, ID_AMBITO_TERRIT NUMBER);

-- changeset root:1753259493085-71
CREATE TABLE TMP_FORNITORE_DA_CREARE (ID_ENTE_FORNIT_EST NUMBER, NM_FORNITORE CHAR(4 BYTE), DS_VIA_SEDE_LEGALE CHAR(11 BYTE), CD_CAP_SEDE_LEGALE CHAR(5 BYTE), DS_CITTA_SEDE_LEGALE CHAR(11 BYTE), ID_PROV_SEDE_LEGALE NUMBER);

-- changeset root:1753259493085-72
CREATE TABLE TMP_GESTORE_DA_CREARE (ID_ENTE_GESTORE NUMBER, NM_GESTORE CHAR(14 BYTE), DS_VIA_SEDE_LEGALE CHAR(15 BYTE), CD_CAP_SEDE_LEGALE CHAR(5 BYTE), DS_CITTA_SEDE_LEGALE CHAR(17 BYTE), ID_PROV_SEDE_LEGALE NUMBER, CD_NAZIONE_SEDE_LEGALE CHAR(2 BYTE), ID_AMBITO_TERRIT NUMBER, TI_CD_ENTE_CONVENZ CHAR(5 BYTE), CD_ENTE_CONVENZ CHAR(9 BYTE), ID_CATEG_ENTE NUMBER, ID_AMBIENTE_ENTE_CONVENZ NUMBER NOT NULL, DT_DEC_ACCORDO date, ID_TIPO_ACCORDO NUMBER, ID_CLASSE_ENTE_CONVENZ NUMBER, DT_SCAD_ACCORDO date, FL_PAGAMENTO CHAR(1 BYTE), ID_ENTE_CONSERV NUMBER);

-- changeset root:1753259493085-73
CREATE TABLE TMP_GESTORE_DIVENTA_CONSERV (ID_ENTE_GESTORE NUMBER NOT NULL, ID_AMBIENTE_PRODUT_OLD NUMBER, ID_ACCORDO_PRODUT_OLD NUMBER NOT NULL, DT_DEC_ACCORDO_OLD date, DT_SCAD_ACCORDO_OLD date, ID_ENTE_GESTORE_OLD NUMBER NOT NULL, ID_ENTE_CONSERV_OLD NUMBER NOT NULL, ID_ENTE_AMMINISTRATORE_OLD NUMBER NOT NULL, ID_AMBIENTE_PRODUT_NEW NUMBER NOT NULL, DT_INI_VAL_AMB_NEW date NOT NULL, DT_FINE_VAL_AMB_NEW date NOT NULL, DT_DEC_ACCORDO_NEW date);

-- changeset root:1753259493085-74
CREATE TABLE TMP_LOG_STRUTTURE_ORG (ID_OGGETTO NUMBER);

-- changeset root:1753259493085-75
CREATE TABLE TMP_LOG_STRUTTURE_ORG_2212 (ID_OGGETTO NUMBER NOT NULL);

-- changeset root:1753259493085-76
CREATE TABLE TMP_LOG_USER_DA_REPLIC (NM_RUOLO VARCHAR2(100 BYTE) NOT NULL, ID_APPLIC NUMBER NOT NULL, NM_APPLIC VARCHAR2(100 BYTE) NOT NULL, ID_USER_IAM NUMBER NOT NULL, NM_USERID VARCHAR2(100 BYTE) NOT NULL);

-- changeset root:1753259493085-77
CREATE TABLE TMP_MOD_PRODUT_CAMBIO_GESTORE (ID_ENTE_PRODUT NUMBER NOT NULL, NM_ENTE_PRODUT VARCHAR2(254 BYTE) NOT NULL, ID_ENTE_GESTORE_NEW NUMBER, ID_ACCORDO_PRODUT NUMBER NOT NULL, DT_DEC_ACCORDO date, DT_SCAD_ACCORDO date, ID_ENTE_GESTORE NUMBER NOT NULL, ID_ENTE_CONSERV NUMBER NOT NULL, ID_ENTE_AMMINISTRATORE NUMBER NOT NULL);

-- changeset root:1753259493085-78
CREATE TABLE TMP_NUOVA_RICHIESTA (ID_OGGETTO NUMBER NOT NULL);

-- changeset root:1753259493085-79
CREATE TABLE TMP_NUOVO_ENTE_UNTENTI (ID_OGGETTO NUMBER);

-- changeset root:1753259493085-80
CREATE TABLE TMP_ORGANIZ_CAMBIO_GEST (ID_APPLIC NUMBER NOT NULL, NM_APPLIC VARCHAR2(100 BYTE) NOT NULL, ID_ORGANIZ_IAM NUMBER NOT NULL, ID_ORGANIZ_APPLIC NUMBER NOT NULL, ID_ENTE_GESTORE NUMBER NOT NULL);

-- changeset root:1753259493085-81
CREATE TABLE TMP_ORGANO_DA_CREARE (ID_ENTE_ORGANO NUMBER, NM_ORGANO CHAR(48 BYTE), DS_VIA_SEDE_LEGALE CHAR(15 BYTE), CD_CAP_SEDE_LEGALE CHAR(5 BYTE), DS_CITTA_SEDE_LEGALE CHAR(17 BYTE), ID_PROV_SEDE_LEGALE NUMBER);

-- changeset root:1753259493085-82
CREATE TABLE TMP_ORG_DI_VIGILANZA (ID_ENTE_SIAM NUMBER);

-- changeset root:1753259493085-83
CREATE TABLE TMP_PRODUTTORI_SIST_VERS (ID_ORG_ENTE_FORNIT_EST NUMBER, NM_PRODUTTORE VARCHAR2(100 BYTE) NOT NULL, DS_VIA_SEDE_LEGALE VARCHAR2(254 BYTE), CD_CAP_SEDE_LEGALE NUMBER, DS_CITTA_SEDE_LEGALE VARCHAR2(254 BYTE));

-- changeset root:1753259493085-84
CREATE TABLE TMP_SUPT_FORNIT (ID_ENTE_FORNIT_EST NUMBER NOT NULL, ID_ENTE_PRODUT NUMBER NOT NULL);

-- changeset root:1753259493085-85
CREATE TABLE TMP_USER_AMMIN (ID_USER_IAM NUMBER NOT NULL);

-- changeset root:1753259493085-86
CREATE TABLE TMP_USER_APPART_ORGANO_VIGIL (ID_USER_IAM NUMBER NOT NULL, ID_ORGANO_VIGIL NUMBER NOT NULL, ID_ACCORDO_VIGIL NUMBER NOT NULL, ID_ENTE_PRODUT NUMBER NOT NULL);

-- changeset root:1753259493085-87
CREATE TABLE TMP_USER_CONSERV (ID_USER_IAM NUMBER NOT NULL, ID_ENTE_ORGANO_VIGIL NUMBER NOT NULL, ID_ACCORDO_VIGIL NUMBER NOT NULL);

-- changeset root:1753259493085-88
CREATE TABLE TMP_USER_DA_ABIL_TI_FASC (ID_USER_IAM NUMBER NOT NULL, NM_USERID VARCHAR2(100 BYTE) NOT NULL, ID_USO_USER_APPLIC NUMBER NOT NULL, ID_CLASSE_TIPO_DATO NUMBER NOT NULL, ID_RICH_GEST_USER NUMBER NOT NULL);

-- changeset root:1753259493085-89
CREATE TABLE TMP_USER_DA_CESSARE (NM_USERID VARCHAR2(100 BYTE));

-- changeset root:1753259493085-90
CREATE TABLE TMP_USER_FORNIT (ID_USER_IAM NUMBER NOT NULL, ID_ENTE_FORNIT NUMBER NOT NULL);

-- changeset root:1753259493085-91
CREATE TABLE TMP_USER_MODIF_RUOLO_DEF (ID_USER_IAM NUMBER, ID_USO_USER_APPLIC NUMBER, ID_APPLIC NUMBER, ID_USO_RUOLO_USER_DEFAULT NUMBER, NM_RUO_OLD VARCHAR2(27 BYTE));

-- changeset root:1753259493085-92
CREATE TABLE TMP_USER_MODIF_RUOLO_ORG (ID_USER_IAM NUMBER, ID_USO_USER_APPLIC NUMBER, ID_APPLIC NUMBER, ID_DICH_ABIL_ORGANIZ NUMBER, ID_USO_RUOLO_DICH NUMBER, NM_RUO_OLD VARCHAR2(27 BYTE));

-- changeset root:1753259493085-93
CREATE TABLE TMP_USER_NEW_AMB (ID_USER_IAM NUMBER NOT NULL, NM_USERID VARCHAR2(100 BYTE) NOT NULL, ID_DICH_ABIL_ENTE_CONVENZ NUMBER NOT NULL, ID_ENTE_GESTORE NUMBER NOT NULL);

-- changeset root:1753259493085-94
CREATE TABLE TMP_USER_OLD_AMB (ID_USER_IAM NUMBER NOT NULL, NM_USERID VARCHAR2(100 BYTE) NOT NULL, ID_ABIL_ENTE_SIAM NUMBER NOT NULL);

-- changeset root:1753259493085-95
CREATE TABLE TMP_USER_RIF_FORNIT (ID_ENTE_USER_RIF NUMBER, ID_ENTE_CONVENZ NUMBER NOT NULL, ID_USER_IAM NUMBER NOT NULL);

-- changeset root:1753259493085-96
CREATE TABLE TMP_USER_USO_SERVIZI (ID_USER_IAM NUMBER NOT NULL, NM_USERID VARCHAR2(100 BYTE) NOT NULL, DT_REG_PSW date NOT NULL, DT_SCAD_PSW date NOT NULL, FL_USO_SERVIZI_SACER NUMBER, FL_USO_SERVIZI_SACER_PRE NUMBER, FL_USO_SERVIZI_PING NUMBER, FL_USO_VERSO NUMBER, FL_USO_VERSO_PRE NUMBER, TIPO_USER VARCHAR2(20 BYTE) DEFAULT 'PERSONA_FISICA' NOT NULL);

-- changeset root:1753259493085-97
CREATE TABLE TMP_UTENTI_AUTOMA_CESSATI (ID_FOTO_OGGETTO_EVENTO NUMBER NOT NULL, ID_USER_IAM NUMBER NOT NULL, NM_USERID VARCHAR2(100 BYTE) NOT NULL, DATA_CESSAZIONE_UTENTE TIMESTAMP(6) NOT NULL, ID_SISTEMA_VERSANTE_MANCANTE NUMBER, ID_SISTEMA_VERSANTE_RECUPERATO NUMBER NOT NULL, NM_SISTEMA_VERSANTE_RECUPERATO VARCHAR2(4000 BYTE));

-- changeset root:1753259493085-98
CREATE TABLE TMP_UTENTI_AUTOMA_CESSATI_VERSATORI (ID_USER_IAM NUMBER NOT NULL, ID_SISTEMA_VERSANTE_RECUPERATO NUMBER NOT NULL);

-- changeset root:1753259493085-99
CREATE TABLE TMP_VIGIL_ENTE_DA_CREARE (ID_ORGANO_VIGIL NUMBER NOT NULL, NM_ENTE_ORGANO VARCHAR2(254 BYTE) NOT NULL, ID_ACCORDO_VIGIL NUMBER NOT NULL, DT_INI_ACC_VIGIL date NOT NULL, DT_FINE_ACC_VIGIL date NOT NULL, ID_ENTE_PRODUT NUMBER NOT NULL, NM_ENTE_PRODUT VARCHAR2(254 BYTE) NOT NULL, DT_INI_VAL date NOT NULL, DT_CESSAZIONE date, DT_DEC_ACCORDO date, DT_SCAD_ACCORDO date);

-- changeset root:1753259493085-100
CREATE TABLE USR_OLD_PSW_BCK (ID_OLD_PSW NUMBER NOT NULL, ID_USER_IAM NUMBER NOT NULL, PG_OLD_PSW NUMBER NOT NULL, CD_PSW VARCHAR2(100 BYTE) NOT NULL, CD_SALT VARCHAR2(100 BYTE) NOT NULL);

-- changeset root:1753259493085-1
DROP INDEX IDX_ABIL_ENTE_ACC_VIG;

-- changeset root:1753259493085-2
CREATE INDEX IDX_ABIL_ENTE_ACC_VIG ON USR_ABIL_ENTE_SIAM(ID_ACCORDO_VIGIL);

-- changeset root:1753259493085-3
DROP INDEX IDX_ABIL_ENTE_APP_COLLEG;

-- changeset root:1753259493085-4
CREATE INDEX IDX_ABIL_ENTE_APP_COLLEG ON USR_ABIL_ENTE_SIAM(ID_APPART_COLLEG_ENTI);

-- changeset root:1753259493085-5
DROP INDEX IDX_ABIL_ENTE_SUPT_EST;

-- changeset root:1753259493085-6
CREATE INDEX IDX_ABIL_ENTE_SUPT_EST ON USR_ABIL_ENTE_SIAM(ID_SUPT_EST_ENTE_CONVENZ);

-- changeset root:1753259493085-7
DROP INDEX IDX_STO_ENTE_AMB;

-- changeset root:1753259493085-8
CREATE INDEX IDX_STO_ENTE_AMB ON ORG_STO_ENTE_AMBIENTE_CONVENZ(ID_AMBIENTE_ENTE_CONVENZ);

-- changeset root:1753259493085-9
ALTER TABLE APL_NOTA_RILASCIO DROP PRIMARY KEY DROP INDEX;

-- changeset root:1753259493085-10
CREATE UNIQUE INDEX PK_APL_NOTA_RILASCIO ON APL_NOTA_RILASCIO(ID_NOTA_RILASCIO);

-- changeset root:1753259493085-11
ALTER TABLE APL_NOTA_RILASCIO ADD CONSTRAINT PK_APL_NOTA_RILASCIO PRIMARY KEY (ID_NOTA_RILASCIO) USING INDEX PK_APL_NOTA_RILASCIO;

-- changeset root:1753259493085-12
ALTER TABLE ORG_CLUSTER_ACCORDO DROP PRIMARY KEY DROP INDEX;

-- changeset root:1753259493085-13
CREATE UNIQUE INDEX PK_CLUSTER_ACCORDO ON ORG_CLUSTER_ACCORDO(ID_CLUSTER_ACCORDO);

-- changeset root:1753259493085-14
ALTER TABLE ORG_CLUSTER_ACCORDO ADD CONSTRAINT PK_CLUSTER_ACCORDO PRIMARY KEY (ID_CLUSTER_ACCORDO) USING INDEX PK_CLUSTER_ACCORDO;

-- changeset root:1753259493085-15
ALTER TABLE ORG_FASCIA_STORAGE_ACCORDO DROP PRIMARY KEY DROP INDEX;

-- changeset root:1753259493085-16
CREATE UNIQUE INDEX PK_FAS_STOR_ACCORDO ON ORG_FASCIA_STORAGE_ACCORDO(ID_FASCIA_STORAGE_ACCORDO);

-- changeset root:1753259493085-17
ALTER TABLE ORG_FASCIA_STORAGE_ACCORDO ADD CONSTRAINT PK_FAS_STOR_ACCORDO PRIMARY KEY (ID_FASCIA_STORAGE_ACCORDO) USING INDEX PK_FAS_STOR_ACCORDO;

-- changeset root:1753259493085-18
ALTER TABLE ORG_AA_ACCORDO DROP PRIMARY KEY DROP INDEX;

-- changeset root:1753259493085-19
CREATE UNIQUE INDEX PK_ORG_AA_ACCORDO ON ORG_AA_ACCORDO(ID_AA_ACCORDO);

-- changeset root:1753259493085-20
ALTER TABLE ORG_AA_ACCORDO ADD CONSTRAINT PK_ORG_AA_ACCORDO PRIMARY KEY (ID_AA_ACCORDO) USING INDEX PK_ORG_AA_ACCORDO;

-- changeset root:1753259493085-21
ALTER TABLE ORG_TARIFFA_AA_ACCORDO DROP PRIMARY KEY DROP INDEX;

-- changeset root:1753259493085-22
CREATE UNIQUE INDEX PK_ORG_TARIF_AA_ACC ON ORG_TARIFFA_AA_ACCORDO(ID_TARIFFA_AA_ACCORDO);

-- changeset root:1753259493085-23
ALTER TABLE ORG_TARIFFA_AA_ACCORDO ADD CONSTRAINT PK_ORG_TARIF_AA_ACC PRIMARY KEY (ID_TARIFFA_AA_ACCORDO) USING INDEX PK_ORG_TARIF_AA_ACC;

-- changeset root:1753259493085-24
ALTER TABLE ORG_STO_ENTE_AMBIENTE_CONVENZ DROP PRIMARY KEY DROP INDEX;

-- changeset root:1753259493085-25
CREATE UNIQUE INDEX PK_STO_ENTE_AMB_CONV ON ORG_STO_ENTE_AMBIENTE_CONVENZ(ID_STO_ENTE_AMBIENTE_CONVENZ);

-- changeset root:1753259493085-26
ALTER TABLE ORG_STO_ENTE_AMBIENTE_CONVENZ ADD CONSTRAINT PK_STO_ENTE_AMB_CONV PRIMARY KEY (ID_STO_ENTE_AMBIENTE_CONVENZ) USING INDEX PK_STO_ENTE_AMB_CONV;

-- changeset root:1753259493085-27
ALTER TABLE ORG_TARIFFA_ACCORDO DROP PRIMARY KEY DROP INDEX;

-- changeset root:1753259493085-28
CREATE UNIQUE INDEX PK_TARIFFA_ACCOR ON ORG_TARIFFA_ACCORDO(ID_TARIFFA_ACCORDO);

-- changeset root:1753259493085-29
ALTER TABLE ORG_TARIFFA_ACCORDO ADD CONSTRAINT PK_TARIFFA_ACCOR PRIMARY KEY (ID_TARIFFA_ACCORDO) USING INDEX PK_TARIFFA_ACCOR;

-- changeset root:1753259493085-30
ALTER TABLE IAM_VALORE_PARAM_APPLIC DROP PRIMARY KEY DROP INDEX;

-- changeset root:1753259493085-31
CREATE UNIQUE INDEX PK_VAL_PAR_APL_IAM ON IAM_VALORE_PARAM_APPLIC(ID_VALORE_PARAM_APPLIC);

-- changeset root:1753259493085-32
ALTER TABLE IAM_VALORE_PARAM_APPLIC ADD CONSTRAINT PK_VAL_PAR_APL_IAM PRIMARY KEY (ID_VALORE_PARAM_APPLIC) USING INDEX PK_VAL_PAR_APL_IAM;

-- changeset root:1753259493085-33
ALTER TABLE USR_ABIL_DATI DROP CONSTRAINT UN_ABIL_DATI DROP INDEX;

-- changeset root:1753259493085-34
CREATE UNIQUE INDEX UN_ABIL_DATI ON USR_ABIL_DATI(ID_USO_USER_APPLIC, ID_TIPO_DATO_IAM, ID_SUPT_EST_ENTE_CONVENZ, ID_VIGIL_ENTE_PRODUT);

-- changeset root:1753259493085-35
ALTER TABLE USR_ABIL_DATI ADD CONSTRAINT UN_ABIL_DATI UNIQUE (ID_USO_USER_APPLIC, ID_TIPO_DATO_IAM, ID_SUPT_EST_ENTE_CONVENZ, ID_VIGIL_ENTE_PRODUT) USING INDEX UN_ABIL_DATI;

-- changeset root:1753259493085-36
ALTER TABLE USR_ABIL_ENTE_SIAM DROP CONSTRAINT UN_ABIL_ENTE DROP INDEX;

-- changeset root:1753259493085-37
CREATE UNIQUE INDEX UN_ABIL_ENTE ON USR_ABIL_ENTE_SIAM(ID_USER_IAM, ID_ENTE_SIAM, ID_APPART_COLLEG_ENTI);

-- changeset root:1753259493085-38
ALTER TABLE USR_ABIL_ENTE_SIAM ADD CONSTRAINT UN_ABIL_ENTE UNIQUE (ID_USER_IAM, ID_ENTE_SIAM, ID_APPART_COLLEG_ENTI) USING INDEX UN_ABIL_ENTE;

-- changeset root:1753259493085-39
ALTER TABLE ORG_CLUSTER_ACCORDO DROP CONSTRAINT UN_CLUSTER_ACCORDO DROP INDEX;

-- changeset root:1753259493085-40
CREATE UNIQUE INDEX UN_CLUSTER_ACCORDO ON ORG_CLUSTER_ACCORDO(CD_CLUSTER);

-- changeset root:1753259493085-41
ALTER TABLE ORG_CLUSTER_ACCORDO ADD CONSTRAINT UN_CLUSTER_ACCORDO UNIQUE (CD_CLUSTER) USING INDEX UN_CLUSTER_ACCORDO;

-- changeset root:1753259493085-42
ALTER TABLE ORG_ENTE_USER_RIF DROP CONSTRAINT UN_ENTE_USR_RIF DROP INDEX;

-- changeset root:1753259493085-43
CREATE UNIQUE INDEX UN_ENTE_USR_RIF ON ORG_ENTE_USER_RIF(ID_ENTE_CONVENZ, ID_USER_IAM, QUALIFICA_USER);

-- changeset root:1753259493085-44
ALTER TABLE ORG_ENTE_USER_RIF ADD CONSTRAINT UN_ENTE_USR_RIF UNIQUE (ID_ENTE_CONVENZ, ID_USER_IAM, QUALIFICA_USER) USING INDEX UN_ENTE_USR_RIF;

-- changeset root:1753259493085-45
ALTER TABLE ORG_FASCIA_STORAGE_ACCORDO DROP CONSTRAINT UN_FAS_STOR_ACCORDO DROP INDEX;

-- changeset root:1753259493085-46
CREATE UNIQUE INDEX UN_FAS_STOR_ACCORDO ON ORG_FASCIA_STORAGE_ACCORDO(TI_FASCIA);

-- changeset root:1753259493085-47
ALTER TABLE ORG_FASCIA_STORAGE_ACCORDO ADD CONSTRAINT UN_FAS_STOR_ACCORDO UNIQUE (TI_FASCIA) USING INDEX UN_FAS_STOR_ACCORDO;

-- changeset root:1753259493085-48
ALTER TABLE ORG_AA_ACCORDO DROP CONSTRAINT UN_ORG_AA_ACCORDO DROP INDEX;

-- changeset root:1753259493085-49
CREATE UNIQUE INDEX UN_ORG_AA_ACCORDO ON ORG_AA_ACCORDO(AA_ANNO_ACCORDO, ID_ACCORDO_ENTE);

-- changeset root:1753259493085-50
ALTER TABLE ORG_AA_ACCORDO ADD CONSTRAINT UN_ORG_AA_ACCORDO UNIQUE (AA_ANNO_ACCORDO, ID_ACCORDO_ENTE) USING INDEX UN_ORG_AA_ACCORDO;

-- changeset root:1753259493085-51
ALTER TABLE ORG_TARIFFA_AA_ACCORDO DROP CONSTRAINT UN_ORG_TARIF_AA_ACC DROP INDEX;

-- changeset root:1753259493085-52
CREATE UNIQUE INDEX UN_ORG_TARIF_AA_ACC ON ORG_TARIFFA_AA_ACCORDO(ID_AA_ACCORDO, ID_TIPO_SERVIZIO);

-- changeset root:1753259493085-53
ALTER TABLE ORG_TARIFFA_AA_ACCORDO ADD CONSTRAINT UN_ORG_TARIF_AA_ACC UNIQUE (ID_AA_ACCORDO, ID_TIPO_SERVIZIO) USING INDEX UN_ORG_TARIF_AA_ACC;

-- changeset root:1753259493085-54
ALTER TABLE ORG_STO_ENTE_AMBIENTE_CONVENZ DROP CONSTRAINT UN_STO_ENTE_AMB_CONV DROP INDEX;

-- changeset root:1753259493085-55
CREATE UNIQUE INDEX UN_STO_ENTE_AMB_CONV ON ORG_STO_ENTE_AMBIENTE_CONVENZ(ID_ENTE_CONVENZ, DT_INI_VAL);

-- changeset root:1753259493085-56
ALTER TABLE ORG_STO_ENTE_AMBIENTE_CONVENZ ADD CONSTRAINT UN_STO_ENTE_AMB_CONV UNIQUE (ID_ENTE_CONVENZ, DT_INI_VAL) USING INDEX UN_STO_ENTE_AMB_CONV;

-- changeset root:1753259493085-57
ALTER TABLE ORG_TARIFFA_ACCORDO DROP CONSTRAINT UN_TARIFFA_ACCOR DROP INDEX;

-- changeset root:1753259493085-58
CREATE UNIQUE INDEX UN_TARIFFA_ACCOR ON ORG_TARIFFA_ACCORDO(ID_ACCORDO_ENTE, ID_TIPO_SERVIZIO);

-- changeset root:1753259493085-59
ALTER TABLE ORG_TARIFFA_ACCORDO ADD CONSTRAINT UN_TARIFFA_ACCOR UNIQUE (ID_ACCORDO_ENTE, ID_TIPO_SERVIZIO) USING INDEX UN_TARIFFA_ACCOR;

-- changeset root:1753259493085-60
CREATE OR REPLACE FORCE VIEW MON_V_LIS_INI_SCHED_JOB (ID_LOG_JOB, NM_JOB, DT_REG_LOG_JOB_INI, DT_REG_LOG_JOB_FINE_SUC, DT_REG_LOG_JOB_INI_SUC) AS select 
 inizio_job.id_log_job,
 inizio_job.nm_job,
 inizio_job.dt_reg_log_job dt_reg_log_job_ini,
 
 (select min(fine_job_min.dt_reg_log_job)
	from LOG_JOB fine_job_min
	where fine_job_min.nm_job = inizio_job.nm_job
	and fine_job_min.ti_reg_log_job in ('FINE_SCHEDULAZIONE', 'ERRORE')
  and fine_job_min.dt_reg_log_job >= inizio_job.dt_reg_log_job) dt_reg_log_job_fine_suc,
  
 (select min(inizio_suc.dt_reg_log_job) 
  from LOG_JOB inizio_suc
	where inizio_suc.nm_job = inizio_job.nm_job
  and inizio_suc.ti_reg_log_job = 'INIZIO_SCHEDULAZIONE'
	and inizio_suc.dt_reg_log_job > inizio_job.dt_reg_log_job) dt_reg_log_job_ini_suc
  
from LOG_JOB inizio_job
where inizio_job.ti_reg_log_job = 'INIZIO_SCHEDULAZIONE';

-- changeset root:1753259493085-61
CREATE OR REPLACE FORCE VIEW MON_V_LIS_SCHED_JOB (ID_LOG_JOB, NM_JOB, DT_REG_LOG_JOB_INI, DT_REG_LOG_JOB_FINE, DURATA_GG, DURATA_ORE, DURATA_MIN, DURATA_SEC, DL_MSG_ERR) AS select
 tmp.id_log_job,
 tmp.nm_job,
 tmp.dt_reg_log_job_ini,
 
 case
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc > tmp.dt_reg_log_job_fine_suc) 
	or (tmp.dt_reg_log_job_ini_suc is null)
		then tmp.dt_reg_log_job_fine_suc
		else null
 end dt_reg_log_job_fine,

 case
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc > tmp.dt_reg_log_job_fine_suc) 
	or (tmp.dt_reg_log_job_ini_suc is null and tmp.dt_reg_log_job_fine_suc is not null)
		then trunc((((86400*(tmp.dt_reg_log_job_fine_suc - tmp.dt_reg_log_job_ini))/60)/60)/24)
		else null
 end durata_gg,

 case
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc > tmp.dt_reg_log_job_fine_suc) 
	or (tmp.dt_reg_log_job_ini_suc is null and tmp.dt_reg_log_job_fine_suc is not null)
		then trunc(((86400*(tmp.dt_reg_log_job_fine_suc - tmp.dt_reg_log_job_ini))/60)/60)-24*(trunc((((86400*(tmp.dt_reg_log_job_fine_suc - tmp.dt_reg_log_job_ini))/60)/60)/24))
		else null
 end durata_ore,

 case
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc > tmp.dt_reg_log_job_fine_suc) 
	or (tmp.dt_reg_log_job_ini_suc is null and tmp.dt_reg_log_job_fine_suc is not null)
		then trunc((86400*(tmp.dt_reg_log_job_fine_suc - tmp.dt_reg_log_job_ini))/60)-60*(trunc(((86400*(tmp.dt_reg_log_job_fine_suc - tmp.dt_reg_log_job_ini))/60)/60))
		else null
 end durata_min,

 case
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc > tmp.dt_reg_log_job_fine_suc) 
	or (tmp.dt_reg_log_job_ini_suc is null and tmp.dt_reg_log_job_fine_suc is not null)
		then trunc(86400*(tmp.dt_reg_log_job_fine_suc - tmp.dt_reg_log_job_ini))-60*(trunc((86400*(tmp.dt_reg_log_job_fine_suc - tmp.dt_reg_log_job_ini))/60))
		else null
 end durata_sec,

 case
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc > tmp.dt_reg_log_job_fine_suc) 
	or (tmp.dt_reg_log_job_ini_suc is null and tmp.dt_reg_log_job_fine_suc is not null)
		then (select min(fine_job.dl_msg_err)
			from LOG_JOB fine_job 
			where fine_job.nm_job = tmp.nm_job
			and fine_job.ti_reg_log_job in ('FINE_SCHEDULAZIONE', 'ERRORE')
			and fine_job.dt_reg_log_job = tmp.dt_reg_log_job_fine_suc)
	when (tmp.dt_reg_log_job_ini_suc is not null and tmp.dt_reg_log_job_fine_suc is not null and tmp.dt_reg_log_job_ini_suc < tmp.dt_reg_log_job_fine_suc)
		then 'Job terminato per caduta dell''application server'
		else null
 end dl_msg_err
 
from MON_V_LIS_INI_SCHED_JOB tmp;

