-- liquibase formatted sql

-- changeset root:1751558214405-59
CREATE TABLE MOVE_RECORD_LOG (COUNT_REC NUMBER NOT NULL, DATA TIMESTAMP(6), STATO_ELAB VARCHAR2(4000 BYTE), PROGRESS NUMBER);

-- changeset root:1751558214405-60
CREATE TABLE PIG_FILE_OBJECT_STORAGE (ID_PIG_FILE_OBJECT_STORAGE NUMBER NOT NULL, ID_PIG_FILE_OBJECT NUMBER NOT NULL, NM_TENANT VARCHAR2(100 BYTE), NM_BUCKET VARCHAR2(100 BYTE), CD_KEY_FILE VARCHAR2(254 BYTE), ID_DEC_BACKEND NUMBER NOT NULL, CONSTRAINT PK_PIG_FILE_OBJECT_STORAGE PRIMARY KEY (ID_PIG_FILE_OBJECT_STORAGE));

-- changeset root:1751558214405-61
CREATE OR REPLACE FORCE VIEW MON_V_OBJ_RANGE_DT_ORIGINALE (ID_VERS, ID_OBJECT, ID_TIPO_OBJECT, TI_STATO_OBJECT, TI_DT_CREAZIONE, TI_CLASSE_VERS_FILE) AS SELECT
        obj.id_vers       ,
        obj.id_object     ,
        obj.id_tipo_object,
        CASE WHEN ti_obj.ti_vers_file = 'DA_TRASFORMARE' THEN CASE WHEN obj.ti_stato_object != 'VERSATO_A_PING' THEN CASE WHEN obj.ti_stato_object = 'CHIUSO_OK' THEN CASE WHEN EXISTS
                                        (
                                                SELECT
                                                        *
                                                FROM
                                                        PIG_UNITA_DOC_OBJECT ud
                                                JOIN
                                                        PIG_OBJECT figlio
                                                ON
                                                        figlio.id_object_padre = obj.id_object
                                                AND     ud.id_object           = figlio.id_object
                                                WHERE
                                                        ud.id_object               = figlio.id_object
                                                AND     (ti_stato_unita_doc_object = 'VERSATA_ERR'
                                                        AND cd_err_sacer IN ('UD-002',
                                                                            'UD-002-001')) ) THEN 'WARNING_CHIAVE_DUPLICATA' ELSE obj.ti_stato_object END ELSE obj.ti_stato_object END ELSE CASE WHEN EXISTS
                                (
                                        SELECT
                                                *
                                        FROM
                                                PIG_OBJECT figlio
                                        WHERE
                                                figlio.id_object_padre = obj.id_object
                                        AND     figlio.ti_stato_object = 'IN_ATTESA_SCHED' ) THEN 'VERSATO_A_PING' ELSE CASE WHEN EXISTS
                                        (
                                                SELECT
                                                        *
                                                FROM
                                                        PIG_OBJECT figlio
                                                WHERE
                                                        figlio.id_object_padre = obj.id_object
                                                AND     figlio.ti_stato_object IN ('CHIUSO_ERR_SCHED') ) THEN 'PROBLEMA_PREPARAZIONE_SIP' ELSE CASE WHEN EXISTS
                                                (
                                                        SELECT
                                                                *
                                                        FROM
                                                                PIG_OBJECT figlio
                                                        WHERE
                                                                figlio.id_object_padre = obj.id_object
                                                        AND     figlio.ti_stato_object IN ('CHIUSO_ERR_CODA',
                                                                                          'CHIUSO_ERR_VERS') ) THEN 'PROBLEMA_VERS_SACER' ELSE 'IN_CORSO_VERS_SACER' END END END END ELSE CASE WHEN obj.ti_stato_object = 'CHIUSO_OK' THEN CASE WHEN EXISTS
                                (
                                        SELECT
                                                *
                                        FROM
                                                PIG_UNITA_DOC_OBJECT ud
                                        WHERE
                                                ud.id_object               = obj.id_object
                                        AND     (ti_stato_unita_doc_object = 'VERSATA_ERR'
                                                AND cd_err_sacer IN ('UD-002'                                                                                                                     ,
                                                                    'UD-002-001')) ) THEN 'WARNING_CHIAVE_DUPLICATA' ELSE obj.ti_stato_object END ELSE obj.ti_stato_object END END ti_stato_object,
        CASE WHEN stato_cor.ts_reg_stato BETWEEN trunc(sysdate)
                AND sysdate                       + 1/24 THEN 'CORR' WHEN stato_cor.ts_reg_stato BETWEEN trunc(sysdate - 6)
                AND to_date(to_char(trunc(sysdate - 1), 'dd-mm-yyyy') || ' 23:59:59', 'dd-mm-yyyy HH24:mi:ss') THEN '6_GG_PREC_CORR' ELSE 'PREC_6_GG_PREC_CORR' END ti_dt_creazione,
        CASE WHEN ti_obj.ti_vers_file             IN ('NO_ZIP'                                                                                                                     ,
                                         'ZIP_CON_XML_SACER'                                                                                                                       ,
                                         'ZIP_NO_XML_SACER') THEN 'NON_DA_TRASFORMARE' ELSE 'DA_TRASFORMARE' END ti_classe_vers_file
FROM
        PIG_OBJECT obj
JOIN
        PIG_TIPO_OBJECT ti_obj
ON
        (
                ti_obj.id_tipo_object = obj.id_tipo_object)
JOIN
        PIG_VERS vers
ON
        (
                ti_obj.id_vers = vers.id_vers)
JOIN
        PIG_SESSIONE_INGEST ses
ON
        (
                ses.id_sessione_ingest = obj.id_last_sessione_ingest)
JOIN
        PIG_STATO_SESSIONE_INGEST stato_cor
ON
        (
                stato_cor.id_stato_sessione_ingest = ses.id_stato_sessione_ingest_cor)
WHERE
        obj.ti_stato_object IN ('CHIUSO_OK'               ,
                               'IN_ATTESA_FILE'           ,
                               'IN_ATTESA_SCHED'          ,
                               'IN_ATTESA_VERS'           ,
                               'IN_CODA_VERS'             ,
                               'WARNING'                  ,
                               'CHIUSO_WARNING'           ,
                               'DA_TRASFORMARE'           ,
                               'TRASFORMAZIONE_NON_ATTIVA',
                               'TRASFORMAZIONE_IN_CORSO'  ,
                               'PREPARAZIONE_OGG_IN_CORSO',
                               'TRASFORMATO'              ,
                               'VERSATO_A_PING'           ,
                               'ERRORE_TRASFORMAZIONE'    ,
                               'WARNING_TRASFORMAZIONE'   ,
                               'ERRORE_VERSAMENTO_A_PING')
AND     vers.fl_cessato=0;

-- changeset root:1751558214405-62
CREATE SEQUENCE SPIG_FILE_OBJECT_STORAGE START WITH 5010 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1751558214405-63
CREATE SEQUENCE SPIG_SISMA_DOCUMENTI_STORAGE START WITH 5190 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1751558214405-64
CREATE SEQUENCE SPIG_STRUM_URB_DOCUMENTI_STORAGE START WITH 5270 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1751558214405-65
CREATE SEQUENCE SXFO_REPORT_OBJECT_STORAGE START WITH 6070 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1751558214405-66 splitStatements:true
CREATE TABLE PIG_DEC_BACKEND (ID_DEC_BACKEND NUMBER NOT NULL, NM_BACKEND VARCHAR2(100 BYTE) NOT NULL, NM_TIPO_BACKEND VARCHAR2(4 BYTE) NOT NULL, DL_BACKEND_URI VARCHAR2(100 BYTE), DS_DESCRIZIONE_BACKEND VARCHAR2(500 BYTE), CONSTRAINT PK_PIG_DEC_BACKEND PRIMARY KEY (ID_DEC_BACKEND));
COMMENT ON TABLE PIG_DEC_BACKEND IS 'La tabella di censimento dei backend';
COMMENT ON COLUMN PIG_DEC_BACKEND.ID_DEC_BACKEND IS 'PK fisica della tabella autogenerata';
COMMENT ON COLUMN PIG_DEC_BACKEND.NM_BACKEND IS 'PK logica della tabella.Il valore deve essere univoco';
COMMENT ON COLUMN PIG_DEC_BACKEND.NM_TIPO_BACKEND IS 'Tipologia del backend (vedi vincolo check)';
COMMENT ON COLUMN PIG_DEC_BACKEND.DL_BACKEND_URI IS 'URI del backend (se necessario)';
COMMENT ON COLUMN PIG_DEC_BACKEND.DS_DESCRIZIONE_BACKEND IS 'Descrizione del backend';

-- changeset root:1751558214405-67 splitStatements:true
CREATE TABLE PIG_DEC_CONFIG_OBJECT_STORAGE (ID_DEC_CONFIG_OBJECT_STORAGE NUMBER NOT NULL, ID_DEC_BACKEND NUMBER NOT NULL, NM_CONFIG_OBJECT_STORAGE VARCHAR2(100 BYTE) NOT NULL, DS_VALORE_CONFIG_OBJECT_STORAGE VARCHAR2(100 BYTE) NOT NULL, TI_USO_CONFIG_OBJECT_STORAGE VARCHAR2(50 BYTE) NOT NULL, DS_DESCRIZIONE_CONFIG_OBJECT_STORAGE VARCHAR2(500 BYTE), CONSTRAINT PK_DEC_CONFIG_OBJECT_STORAGE0 PRIMARY KEY (ID_DEC_CONFIG_OBJECT_STORAGE));
COMMENT ON TABLE PIG_DEC_CONFIG_OBJECT_STORAGE IS 'La tabella di configurazione dei backend di tipo Object Storage';
COMMENT ON COLUMN PIG_DEC_CONFIG_OBJECT_STORAGE.ID_DEC_CONFIG_OBJECT_STORAGE IS 'PK fisica della tabella, autogenerata';
COMMENT ON COLUMN PIG_DEC_CONFIG_OBJECT_STORAGE.ID_DEC_BACKEND IS 'FK della tabella DEC_BACKEND';
COMMENT ON COLUMN PIG_DEC_CONFIG_OBJECT_STORAGE.NM_CONFIG_OBJECT_STORAGE IS 'Nome delle configurazione: attualmente BUCKET, ACCESS_KEY_ID_SYS_PROP o SECRET_KEY_SYS_PROP. Unito alla colonna TI_USO_CONFIG_OBJECT_STORAGE rappresenta la chiave logica della tabella';
COMMENT ON COLUMN PIG_DEC_CONFIG_OBJECT_STORAGE.DS_VALORE_CONFIG_OBJECT_STORAGE IS 'Indica il nome del bucket su cui verranno salvati i dati';
COMMENT ON COLUMN PIG_DEC_CONFIG_OBJECT_STORAGE.TI_USO_CONFIG_OBJECT_STORAGE IS 'Tipo d''uso per il parametro. Attualmente WRITE-STAGING,WRITE-COMPONENTI, WRITE-SIP, WRITE-AIP, READ-STAGING, READ-COMPONENTI,READ-SIP, READ-AIP. Bisogna valutare se farlo diventare un vincolo sulla colonna.';
COMMENT ON COLUMN PIG_DEC_CONFIG_OBJECT_STORAGE.DS_DESCRIZIONE_CONFIG_OBJECT_STORAGE IS 'Breve descrizione della configurazione';

-- changeset root:1751558214405-68
CREATE TABLE PIG_FILE_OBJECT_OLD (ID_FILE_OBJECT NUMBER NOT NULL, ID_OBJECT NUMBER NOT NULL, NM_FILE_OBJECT VARCHAR2(100 BYTE) NOT NULL, ID_TIPO_FILE_OBJECT NUMBER NOT NULL, DS_HASH_FILE_VERS VARCHAR2(254 BYTE), TI_ALGO_HASH_FILE_VERS VARCHAR2(20 BYTE), CD_ENCODING_HASH_FILE_VERS VARCHAR2(100 BYTE), NI_SIZE_FILE_VERS NUMBER, NM_BUCKET VARCHAR2(100 BYTE), CD_KEY_FILE VARCHAR2(254 BYTE), CONSTRAINT PK_FILE_OBJ PRIMARY KEY (ID_FILE_OBJECT));

-- changeset root:1751558214405-69
CREATE TABLE PIG_INFO_DICOM_OLD (ID_INFO_DICOM NUMBER NOT NULL, ID_OBJECT NUMBER NOT NULL, ID_VERS NUMBER NOT NULL, CD_VERSIONE_DATI_SPEC_DICOM VARCHAR2(100 BYTE) NOT NULL, CD_AET_NODO_DICOM VARCHAR2(100 BYTE) NOT NULL, DL_LISTA_SOP_CLASS VARCHAR2(2048 BYTE), DT_STUDY_DATE date NOT NULL, DS_ACCESSION_NUMBER VARCHAR2(254 BYTE), DL_LISTA_MODALITY_IN_STUDY VARCHAR2(2048 BYTE), DS_INSTITUTION_NAME VARCHAR2(254 BYTE), DS_REF_PHYSICIAN_NAME VARCHAR2(254 BYTE), DL_STUDY_DESCRIPTION VARCHAR2(1024 BYTE), DS_PATIENT_NAME VARCHAR2(100 BYTE) NOT NULL, CD_PATIENT_ID VARCHAR2(100 BYTE) NOT NULL, CD_PATIENT_ID_ISSUER VARCHAR2(100 BYTE), DT_PATIENT_BIRTH_DATE date, TI_PATIENT_SEX CHAR(1 BYTE), DS_STUDY_INSTANCE_UID VARCHAR2(254 BYTE) NOT NULL, NI_STUDY_RELATED_SERIES NUMBER(5, 0) NOT NULL, NI_STUDY_RELATED_IMAGES NUMBER(5, 0) NOT NULL, DS_STUDY_ID VARCHAR2(254 BYTE), DT_PRESA_IN_CARICO date NOT NULL, BL_DCM_HASH_TXT CLOB NOT NULL, DS_DCM_HASH VARCHAR2(254 BYTE) NOT NULL, TI_ALGO_DCM_HASH VARCHAR2(20 BYTE) NOT NULL, CD_ENCODING_DCM_HASH VARCHAR2(100 BYTE) NOT NULL, BL_GLOBAL_HASH_TXT CLOB NOT NULL, DS_GLOBAL_HASH VARCHAR2(254 BYTE) NOT NULL, TI_ALGO_GLOBAL_HASH VARCHAR2(20 BYTE) NOT NULL, CD_ENCODING_GLOBAL_HASH VARCHAR2(100 BYTE) NOT NULL, DS_FILE_HASH VARCHAR2(254 BYTE) NOT NULL, TI_ALGO_FILE_HASH VARCHAR2(20 BYTE) NOT NULL, CD_ENCODING_FILE_HASH VARCHAR2(100 BYTE) NOT NULL, ID_XSD_SPEC NUMBER NOT NULL, CONSTRAINT PK_INFO_DICOM PRIMARY KEY (ID_INFO_DICOM));

-- changeset root:1751558214405-70
CREATE TABLE PIG_OBJECT_OLD (ID_OBJECT NUMBER NOT NULL, ID_VERS NUMBER NOT NULL, CD_KEY_OBJECT VARCHAR2(100 BYTE) NOT NULL, ID_TIPO_OBJECT NUMBER NOT NULL, ID_LAST_SESSIONE_INGEST NUMBER NOT NULL, TI_STATO_OBJECT VARCHAR2(30 BYTE) NOT NULL, FL_VERS_SACER_DA_RECUP CHAR(1 BYTE), MM_FIRST_SES NUMBER(6, 0) NOT NULL, ID_USER_IAM NUMBER, DS_OBJECT VARCHAR2(1024 BYTE), NI_UNITA_DOC_ATTESE NUMBER(5, 0), NI_TOT_OBJECT_TRASF NUMBER(3, 0), ID_OBJECT_PADRE NUMBER, PG_OGGETTO_TRASF NUMBER(3, 0), CD_TRASF VARCHAR2(100 BYTE), CD_VERSIONE_TRASF VARCHAR2(100 BYTE), CD_VERS_GEN VARCHAR2(100 BYTE), FL_RICH_ANNUL_TIMEOUT CHAR(1 BYTE), TI_GEST_OGGETTI_FIGLI VARCHAR2(20 BYTE), NOTE VARCHAR2(1024 BYTE), TI_PRIORITA VARCHAR2(20 CHAR), TI_PRIORITA_VERSAMENTO VARCHAR2(20 CHAR), CONSTRAINT PK_OBJ PRIMARY KEY (ID_OBJECT));

-- changeset root:1751558214405-71
CREATE TABLE PIG_OBJECT_TRASF_OLD (ID_OBJECT_TRASF NUMBER NOT NULL, ID_OBJECT NUMBER NOT NULL, CD_KEY_OBJECT_TRASF VARCHAR2(100 BYTE) NOT NULL, DS_OBJECT_TRASF VARCHAR2(1024 BYTE), ID_VERS NUMBER NOT NULL, ID_TIPO_OBJECT NUMBER NOT NULL, DS_PATH VARCHAR2(254 BYTE) NOT NULL, DS_HASH_FILE_VERS VARCHAR2(254 BYTE), TI_ALGO_HASH_FILE_VERS VARCHAR2(20 BYTE), CD_ENCODING_HASH_FILE_VERS VARCHAR2(100 BYTE), PG_OGGETTO_TRASF NUMBER(3, 0) NOT NULL, CD_ERR VARCHAR2(100 BYTE), DL_ERR VARCHAR2(1024 BYTE), CONSTRAINT PK_PIG_OBJECT_TRASF PRIMARY KEY (ID_OBJECT_TRASF));

-- changeset root:1751558214405-72
CREATE TABLE PIG_SESSIONE_INGEST_OLD (ID_SESSIONE_INGEST NUMBER NOT NULL, NM_AMBIENTE_VERS VARCHAR2(100 BYTE) NOT NULL, NM_VERS VARCHAR2(100 BYTE) NOT NULL, CD_KEY_OBJECT VARCHAR2(100 BYTE) NOT NULL, ID_VERS NUMBER, DT_APERTURA date NOT NULL, DT_CHIUSURA date, NM_TIPO_OBJECT VARCHAR2(100 BYTE), FL_FILE_CIFRATO CHAR(1 BYTE), FL_FORZA_ACCETTAZIONE CHAR(1 BYTE) DEFAULT '0', DL_MOTIVO_FORZA_ACCETTAZIONE VARCHAR2(1024 BYTE), CD_VERSIONE_XML_VERS VARCHAR2(100 BYTE), TI_STATO VARCHAR2(30 BYTE) NOT NULL, ID_OBJECT NUMBER, NI_UNITA_DOC_DA_VERS NUMBER, NI_UNITA_DOC_VERS NUMBER, CD_ERR VARCHAR2(100 BYTE), DL_ERR VARCHAR2(1024 BYTE), DL_MOTIVO_CHIUSO_WARNING VARCHAR2(1024 BYTE), NI_UNITA_DOC_VERS_OK NUMBER, NI_UNITA_DOC_VERS_ERR NUMBER, FL_FORZA_WARNING CHAR(1 BYTE), FL_SES_ERR_VERIF CHAR(1 BYTE), FL_SES_ERR_NON_RISOLUB CHAR(1 BYTE), NI_UNITA_DOC_VERS_TIMEOUT NUMBER, TI_STATO_VERIFICA_HASH VARCHAR2(20 BYTE), NM_AMBIENTE_VERS_PADRE VARCHAR2(100 BYTE), NM_VERS_PADRE VARCHAR2(100 BYTE), CD_KEY_OBJECT_PADRE VARCHAR2(100 BYTE), NI_UNITA_DOC_ATTESE NUMBER(5, 0), NI_TOT_OBJECT_TRASF NUMBER(3, 0), PG_OGGETTO_TRASF NUMBER(3, 0), DS_OBJECT VARCHAR2(1024 BYTE), ID_STATO_SESSIONE_INGEST_COR NUMBER, CD_TRASF VARCHAR2(100 BYTE), CD_VERSIONE_TRASF VARCHAR2(100 BYTE), CD_VERS_GEN VARCHAR2(100 BYTE), TI_GEST_OGGETTI_FIGLI VARCHAR2(20 BYTE), NOTE VARCHAR2(1024 BYTE), NM_REPORT_TRASF_OS VARCHAR2(200 BYTE), CONSTRAINT PK_SES_INGEST PRIMARY KEY (ID_SESSIONE_INGEST));

-- changeset root:1751558214405-73
CREATE TABLE PIG_SISMA_BCK (ID_SISMA NUMBER NOT NULL, TI_STATO VARCHAR2(40 CHAR) NOT NULL, OGGETTO VARCHAR2(300 BYTE), ANNO NUMBER(4, 0) NOT NULL, NUMERO VARCHAR2(20 CHAR) NOT NULL, DT_CREAZIONE date NOT NULL, ID_VERS NUMBER NOT NULL, DS_ERR VARCHAR2(300 CHAR), ID_USER_IAM NUMBER NOT NULL, CD_KEY VARCHAR2(50 CHAR) NOT NULL, CD_KEY_OS VARCHAR2(160 CHAR) NOT NULL, CD_ERR VARCHAR2(20 CHAR), DATA date NOT NULL, DT_STATO date, DS_DESCRIZIONE VARCHAR2(1024 BYTE), ID_SISMA_VAL_ATTO NUMBER NOT NULL, ANNO_AG NUMBER(4, 0), REGISTRO_AG VARCHAR2(60 CHAR), NUMERO_AG VARCHAR2(20 CHAR), DATA_AG date, ID_VERS_AG NUMBER, ID_SISMA_PROGETTI_AG NUMBER NOT NULL, ID_SISMA_FASE_PROGETTO NUMBER NOT NULL, ID_SISMA_STATO_PROGETTO NUMBER NOT NULL, CLASSIFICA VARCHAR2(100 BYTE), ID_FASCICOLO VARCHAR2(100 BYTE), OGGETTO_FASCICOLO VARCHAR2(100 BYTE), ID_SOTTOFASCICOLO VARCHAR2(100 BYTE), OGGETTO_SOTTOFASCICOLO VARCHAR2(100 BYTE), FL_INVIATO_A_ENTE VARCHAR2(1 BYTE) NOT NULL, FL_INTERVENTO_SOGGETTO_A_TUTELA VARCHAR2(1 BYTE), CLASSIFICA_AG VARCHAR2(100 BYTE), ID_FASCICOLO_AG VARCHAR2(100 BYTE), OGGETTO_FASCICOLO_AG VARCHAR2(100 BYTE), ID_SOTTOFASCICOLO_AG VARCHAR2(100 BYTE), OGGETTO_SOTTOFASCICOLO_AG VARCHAR2(100 BYTE));

-- changeset root:1751558214405-74
CREATE TABLE PIG_SISMA_DOCUMENTI_STORAGE (ID_PIG_SISMA_DOCUMENTI_STORAGE NUMBER NOT NULL, ID_SISMA_DOCUMENTI NUMBER NOT NULL, NM_TENANT VARCHAR2(100 BYTE), NM_BUCKET VARCHAR2(100 BYTE), CD_KEY_FILE VARCHAR2(254 BYTE), ID_DEC_BACKEND NUMBER NOT NULL, CONSTRAINT PK_PIG_SISMA_DOCUMENTI_STORAGE PRIMARY KEY (ID_PIG_SISMA_DOCUMENTI_STORAGE));

-- changeset root:1751558214405-75
CREATE TABLE PIG_SISMA_PIANO_DOC_REQ_BKP (ID_SISMA_PIANO_DOC_REQ NUMBER NOT NULL, ID_PIG_SISMA_VAL_DOC NUMBER NOT NULL, FL_DOC_OBBLIGATORIO CHAR(1 CHAR), ID_SISMA_VAL_ATTO NUMBER NOT NULL);

-- changeset root:1751558214405-76
CREATE TABLE PIG_SISMA_VAL_ATTO_BCK (ID_SISMA_VAL_ATTO NUMBER NOT NULL, NM_TIPO_ATTO VARCHAR2(60 CHAR) NOT NULL, TI_TIPO_ATTO VARCHAR2(60 CHAR) NOT NULL, ID_SISMA_FASE_PROGETTO NUMBER NOT NULL);

-- changeset root:1751558214405-77
CREATE TABLE PIG_STATO_SESSIONE_INGEST_OLD (ID_STATO_SESSIONE_INGEST NUMBER NOT NULL, ID_SESSIONE_INGEST NUMBER NOT NULL, TI_STATO VARCHAR2(30 BYTE) NOT NULL, TS_REG_STATO TIMESTAMP(3) NOT NULL, CONSTRAINT PK_STATO_SES_INGEST PRIMARY KEY (ID_STATO_SESSIONE_INGEST));

-- changeset root:1751558214405-78
CREATE TABLE PIG_STRUM_URB_COLLEGAMENTI_BKP (ID_STRUM_URB_COLLEGAMENTI NUMBER NOT NULL, ID_STRUMENTI_URBANISTICI NUMBER NOT NULL, NUMERO VARCHAR2(20 CHAR), ANNO NUMBER, ID_STRUM_URB_PIANO_STATO NUMBER NOT NULL);

-- changeset root:1751558214405-79
CREATE TABLE PIG_STRUM_URB_DOCUMENTI_STORAGE (ID_PIG_STRUM_URB_DOCUMENTI_STORAGE NUMBER NOT NULL, ID_STRUM_URB_DOCUMENTI NUMBER NOT NULL, NM_TENANT VARCHAR2(100 BYTE), NM_BUCKET VARCHAR2(100 BYTE), CD_KEY_FILE VARCHAR2(254 BYTE), ID_DEC_BACKEND NUMBER NOT NULL, CONSTRAINT PK_PIG_STRUM_URB_DOCUMENTI_STORAGE PRIMARY KEY (ID_PIG_STRUM_URB_DOCUMENTI_STORAGE));

-- changeset root:1751558214405-80
CREATE TABLE PIG_TIPO_FILE_OBJECT_BCK_20231023 (ID_TIPO_FILE_OBJECT NUMBER, ID_TIPO_OBJECT NUMBER, NM_TIPO_FILE_OBJECT VARCHAR2(100 BYTE), DS_TIPO_FILE_OBJECT VARCHAR2(254 BYTE), FL_VERS_SACER_ASINC CHAR(1 BYTE), NM_TIPO_DOC_SACER VARCHAR2(100 BYTE), TI_DOC_SACER VARCHAR2(20 BYTE), NM_TIPO_STRUT_DOC_SACER VARCHAR2(100 BYTE), NM_TIPO_COMP_DOC_SACER VARCHAR2(100 BYTE), NM_FMT_FILE_VERS_SACER VARCHAR2(100 BYTE), FL_VER_FIRMA_FMT_SACER CHAR(1 BYTE), NM_FMT_FILE_CALC_SACER VARCHAR2(100 BYTE), DS_FMT_RAPPR_ESTESO_CALC_SACER VARCHAR2(254 BYTE), DS_FMT_RAPPR_CALC_SACER VARCHAR2(254 BYTE), FL_CALC_HASH_SACER CHAR(1 BYTE), TI_CALC_HASH_SACER VARCHAR2(20 BYTE));

-- changeset root:1751558214405-81
CREATE TABLE PIG_UNITA_DOC_OBJECT_OLD (ID_UNITA_DOC_OBJECT NUMBER NOT NULL, ID_OBJECT NUMBER NOT NULL, CD_REGISTRO_UNITA_DOC_SACER VARCHAR2(100 BYTE) NOT NULL, AA_UNITA_DOC_SACER NUMBER(4, 0) NOT NULL, CD_KEY_UNITA_DOC_SACER VARCHAR2(100 BYTE) NOT NULL, NI_SIZE_FILE_BYTE NUMBER NOT NULL, TI_STATO_UNITA_DOC_OBJECT VARCHAR2(25 BYTE) NOT NULL, CD_ERR_SACER VARCHAR2(100 BYTE), DL_ERR_SACER VARCHAR2(1024 BYTE), ID_ORGANIZ_IAM NUMBER, FL_VERS_SIMULATO CHAR(1 BYTE), CD_VER_WS_SACER VARCHAR2(100 BYTE), CONSTRAINT PK_UNI_DOC_OBJ PRIMARY KEY (ID_UNITA_DOC_OBJECT));

-- changeset root:1751558214405-82
CREATE TABLE PIG_UNITA_DOC_SESSIONE_OLD (ID_UNITA_DOC_SESSIONE NUMBER NOT NULL, ID_SESSIONE_INGEST NUMBER NOT NULL, CD_REGISTRO_UNITA_DOC_SACER VARCHAR2(100 BYTE) NOT NULL, AA_UNITA_DOC_SACER NUMBER(4, 0) NOT NULL, CD_KEY_UNITA_DOC_SACER VARCHAR2(100 BYTE) NOT NULL, TI_STATO_UNITA_DOC_SESSIONE VARCHAR2(25 BYTE) NOT NULL, NI_SIZE_FILE_BYTE NUMBER NOT NULL, CD_ERR_SACER VARCHAR2(100 BYTE), DL_ERR_SACER VARCHAR2(1024 BYTE), ID_ORGANIZ_IAM NUMBER, FL_VERS_SIMULATO CHAR(1 BYTE), CD_VER_WS_SACER VARCHAR2(100 BYTE), CONSTRAINT PK_UNI_DOC_SES PRIMARY KEY (ID_UNITA_DOC_SESSIONE));

-- changeset root:1751558214405-83
CREATE TABLE PIG_VALORE_PARAM_APPLIC_OLD_MULTIOS (ID_VALORE_PARAM_APPLIC NUMBER NOT NULL, ID_PARAM_APPLIC NUMBER NOT NULL, TI_APPART VARCHAR2(30 BYTE) NOT NULL, DS_VALORE_PARAM_APPLIC VARCHAR2(254 BYTE) NOT NULL, ID_AMBIENTE_VERS NUMBER, ID_VERS NUMBER, ID_TIPO_OBJECT NUMBER);

-- changeset root:1751558214405-84
CREATE TABLE PIG_XML_OBJECT_OLD (ID_XML_OBJECT NUMBER NOT NULL, ID_OBJECT NUMBER NOT NULL, CD_VERSIONE_XML_VERS VARCHAR2(100 BYTE) NOT NULL, BL_XML CLOB NOT NULL, CONSTRAINT PK_XML_OBJ PRIMARY KEY (ID_XML_OBJECT));

-- changeset root:1751558214405-85
CREATE TABLE PIG_XML_OBJECT_TRASF_OLD (ID_XML_OBJECT_TRASF NUMBER NOT NULL, ID_OBJECT_TRASF NUMBER NOT NULL, CD_VERSIONE_XML_VERS VARCHAR2(100 BYTE) NOT NULL, BL_XML CLOB NOT NULL, CONSTRAINT PK_XML_OBJ_TRASF PRIMARY KEY (ID_XML_OBJECT_TRASF));

-- changeset root:1751558214405-86
CREATE TABLE PIG_XML_SACER_UNITA_DOC_OLD (ID_XML_SACER_UNITA_DOC NUMBER NOT NULL, ID_UNITA_DOC_OBJECT NUMBER NOT NULL, TI_XML_SACER VARCHAR2(20 BYTE) NOT NULL, BL_XML_SACER CLOB NOT NULL, CONSTRAINT PK_XML_UNI_DOC PRIMARY KEY (ID_XML_SACER_UNITA_DOC));

-- changeset root:1751558214405-87
CREATE TABLE PIG_XML_SACER_UNITA_DOC_SES_OLD (ID_XML_SACER_UNITA_DOC_SES NUMBER NOT NULL, ID_UNITA_DOC_SESSIONE NUMBER NOT NULL, TI_XML_SACER VARCHAR2(20 BYTE) NOT NULL, BL_XML_SACER CLOB NOT NULL, CONSTRAINT PK_XML_UNI_DOC_SES PRIMARY KEY (ID_XML_SACER_UNITA_DOC_SES));

-- changeset root:1751558214405-88
CREATE TABLE PIG_XML_SESSIONE_INGEST_OLD (ID_XML_SESSIONE_INGEST NUMBER NOT NULL, ID_SESSIONE_INGEST NUMBER NOT NULL, BL_XML CLOB NOT NULL, CONSTRAINT PK_XML_SES_INGEST PRIMARY KEY (ID_XML_SESSIONE_INGEST));

-- changeset root:1751558214405-89
CREATE TABLE TMP_OBJ_SES_DA_RECUP (ID_OBJECT NUMBER NOT NULL, ID_LAST_SESSIONE_INGEST NUMBER NOT NULL, CD_KEY_OBJECT VARCHAR2(150 CHAR) NOT NULL, DL_ERR_SACER VARCHAR2(1024 BYTE));

-- changeset root:1751558214405-90
CREATE TABLE TMP_XSD (ID VARCHAR2(40 BYTE), XSD CLOB);

-- changeset root:1751558214405-91
CREATE TABLE XFO_REPORT_OBJECT_STORAGE (ID_XFO_REPORT_OBJECT_STORAGE NUMBER NOT NULL, ID_SESSIONE_INGEST NUMBER NOT NULL, NM_TENANT VARCHAR2(100 BYTE), NM_BUCKET VARCHAR2(100 BYTE), CD_KEY_FILE VARCHAR2(254 BYTE), ID_DEC_BACKEND NUMBER NOT NULL, CONSTRAINT PK_XFO_REPORT_OBJECT_STORAGE PRIMARY KEY (ID_XFO_REPORT_OBJECT_STORAGE));

-- changeset root:1751558214405-92
CREATE UNIQUE INDEX UN_DEC_CONFIG_OBJECT_STORAGE0 ON PIG_DEC_CONFIG_OBJECT_STORAGE(ID_DEC_BACKEND, NM_CONFIG_OBJECT_STORAGE, TI_USO_CONFIG_OBJECT_STORAGE);

-- changeset root:1751558214405-93
ALTER TABLE PIG_DEC_CONFIG_OBJECT_STORAGE ADD CONSTRAINT UN_DEC_CONFIG_OBJECT_STORAGE0 UNIQUE (ID_DEC_BACKEND, NM_CONFIG_OBJECT_STORAGE, TI_USO_CONFIG_OBJECT_STORAGE) USING INDEX UN_DEC_CONFIG_OBJECT_STORAGE0;

-- changeset root:1751558214405-94
CREATE UNIQUE INDEX UN_FILE_OBJ ON PIG_FILE_OBJECT_OLD(ID_OBJECT, NM_FILE_OBJECT);

-- changeset root:1751558214405-95
ALTER TABLE PIG_FILE_OBJECT_OLD ADD CONSTRAINT UN_FILE_OBJ UNIQUE (ID_OBJECT, NM_FILE_OBJECT) USING INDEX UN_FILE_OBJ;

-- changeset root:1751558214405-96
CREATE UNIQUE INDEX UN_INFO_DICOM ON PIG_INFO_DICOM_OLD(ID_OBJECT);

-- changeset root:1751558214405-97
ALTER TABLE PIG_INFO_DICOM_OLD ADD CONSTRAINT UN_INFO_DICOM UNIQUE (ID_OBJECT) USING INDEX UN_INFO_DICOM;

-- changeset root:1751558214405-98
CREATE UNIQUE INDEX UN_OBJ ON PIG_OBJECT_OLD(ID_VERS, CD_KEY_OBJECT);

-- changeset root:1751558214405-99
ALTER TABLE PIG_OBJECT_OLD ADD CONSTRAINT UN_OBJ UNIQUE (ID_VERS, CD_KEY_OBJECT) USING INDEX UN_OBJ;

-- changeset root:1751558214405-100
CREATE UNIQUE INDEX UN_OBJ_TRASF ON PIG_OBJECT_TRASF_OLD(ID_OBJECT, CD_KEY_OBJECT_TRASF);

-- changeset root:1751558214405-101
ALTER TABLE PIG_OBJECT_TRASF_OLD ADD CONSTRAINT UN_OBJ_TRASF UNIQUE (ID_OBJECT, CD_KEY_OBJECT_TRASF) USING INDEX UN_OBJ_TRASF;

-- changeset root:1751558214405-102
CREATE UNIQUE INDEX UN_OBJ_TRASF_PG ON PIG_OBJECT_TRASF_OLD(ID_OBJECT, PG_OGGETTO_TRASF);

-- changeset root:1751558214405-103
ALTER TABLE PIG_OBJECT_TRASF_OLD ADD CONSTRAINT UN_OBJ_TRASF_PG UNIQUE (ID_OBJECT, PG_OGGETTO_TRASF) USING INDEX UN_OBJ_TRASF_PG;

-- changeset root:1751558214405-104
CREATE UNIQUE INDEX UN_OBJ_TRASF_VERS ON PIG_OBJECT_TRASF_OLD(ID_VERS, CD_KEY_OBJECT_TRASF);

-- changeset root:1751558214405-105
ALTER TABLE PIG_OBJECT_TRASF_OLD ADD CONSTRAINT UN_OBJ_TRASF_VERS UNIQUE (ID_VERS, CD_KEY_OBJECT_TRASF) USING INDEX UN_OBJ_TRASF_VERS;

-- changeset root:1751558214405-106
CREATE UNIQUE INDEX UN_STATO_SES_INGEST ON PIG_STATO_SESSIONE_INGEST_OLD(ID_SESSIONE_INGEST, TS_REG_STATO);

-- changeset root:1751558214405-107
ALTER TABLE PIG_STATO_SESSIONE_INGEST_OLD ADD CONSTRAINT UN_STATO_SES_INGEST UNIQUE (ID_SESSIONE_INGEST, TS_REG_STATO) USING INDEX UN_STATO_SES_INGEST;

-- changeset root:1751558214405-108
CREATE UNIQUE INDEX UN_UNI_DOC_OBJ ON PIG_UNITA_DOC_OBJECT_OLD(ID_OBJECT, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER);

-- changeset root:1751558214405-109
ALTER TABLE PIG_UNITA_DOC_OBJECT_OLD ADD CONSTRAINT UN_UNI_DOC_OBJ UNIQUE (ID_OBJECT, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER) USING INDEX UN_UNI_DOC_OBJ;

-- changeset root:1751558214405-110
CREATE UNIQUE INDEX UN_UNI_DOC_SES ON PIG_UNITA_DOC_SESSIONE_OLD(ID_SESSIONE_INGEST, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER);

-- changeset root:1751558214405-111
ALTER TABLE PIG_UNITA_DOC_SESSIONE_OLD ADD CONSTRAINT UN_UNI_DOC_SES UNIQUE (ID_SESSIONE_INGEST, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER) USING INDEX UN_UNI_DOC_SES;

-- changeset root:1751558214405-112
CREATE UNIQUE INDEX UN_XML_OBJ ON PIG_XML_OBJECT_OLD(ID_OBJECT);

-- changeset root:1751558214405-113
ALTER TABLE PIG_XML_OBJECT_OLD ADD CONSTRAINT UN_XML_OBJ UNIQUE (ID_OBJECT) USING INDEX UN_XML_OBJ;

-- changeset root:1751558214405-114
CREATE UNIQUE INDEX UN_XML_OBJ_TRASF ON PIG_XML_OBJECT_TRASF_OLD(ID_OBJECT_TRASF);

-- changeset root:1751558214405-115
ALTER TABLE PIG_XML_OBJECT_TRASF_OLD ADD CONSTRAINT UN_XML_OBJ_TRASF UNIQUE (ID_OBJECT_TRASF) USING INDEX UN_XML_OBJ_TRASF;

-- changeset root:1751558214405-116
CREATE UNIQUE INDEX UN_XML_SES_INGEST ON PIG_XML_SESSIONE_INGEST_OLD(ID_SESSIONE_INGEST);

-- changeset root:1751558214405-117
ALTER TABLE PIG_XML_SESSIONE_INGEST_OLD ADD CONSTRAINT UN_XML_SES_INGEST UNIQUE (ID_SESSIONE_INGEST) USING INDEX UN_XML_SES_INGEST;

-- changeset root:1751558214405-118
CREATE UNIQUE INDEX UN_XML_UNI_DOC ON PIG_XML_SACER_UNITA_DOC_OLD(ID_UNITA_DOC_OBJECT, TI_XML_SACER);

-- changeset root:1751558214405-119
ALTER TABLE PIG_XML_SACER_UNITA_DOC_OLD ADD CONSTRAINT UN_XML_UNI_DOC UNIQUE (ID_UNITA_DOC_OBJECT, TI_XML_SACER) USING INDEX UN_XML_UNI_DOC;

-- changeset root:1751558214405-120
CREATE UNIQUE INDEX UN_XML_UNI_DOC_SES ON PIG_XML_SACER_UNITA_DOC_SES_OLD(ID_UNITA_DOC_SESSIONE, TI_XML_SACER);

-- changeset root:1751558214405-121
ALTER TABLE PIG_XML_SACER_UNITA_DOC_SES_OLD ADD CONSTRAINT UN_XML_UNI_DOC_SES UNIQUE (ID_UNITA_DOC_SESSIONE, TI_XML_SACER) USING INDEX UN_XML_UNI_DOC_SES;

-- changeset root:1751558214405-122
CREATE INDEX IDX_FILE_OBJ ON PIG_FILE_OBJECT_OLD(ID_OBJECT);

-- changeset root:1751558214405-123
CREATE INDEX IDX_INFO_DICOM_ACCESSION ON PIG_INFO_DICOM_OLD(ID_VERS, DS_ACCESSION_NUMBER);

-- changeset root:1751558214405-124
CREATE INDEX IDX_INFO_DICOM_COGN_PATIENT ON PIG_INFO_DICOM_OLD(ID_VERS, DS_PATIENT_NAME);

-- changeset root:1751558214405-125
CREATE INDEX IDX_INFO_DICOM_DCM_HASH ON PIG_INFO_DICOM_OLD(ID_VERS, DS_DCM_HASH);

-- changeset root:1751558214405-126
CREATE INDEX IDX_INFO_DICOM_ID_PATIENT ON PIG_INFO_DICOM_OLD(ID_VERS, CD_PATIENT_ID, CD_PATIENT_ID_ISSUER);

-- changeset root:1751558214405-127
CREATE INDEX IDX_INFO_DICOM_STUDY_TIME ON PIG_INFO_DICOM_OLD(ID_VERS, DT_STUDY_DATE);

-- changeset root:1751558214405-128
CREATE INDEX IDX_INFO_DICOM_STUDY_UID ON PIG_INFO_DICOM_OLD(ID_VERS, DS_STUDY_INSTANCE_UID);

-- changeset root:1751558214405-129
CREATE INDEX IDX_OBJ_PADRE ON PIG_OBJECT_OLD(ID_OBJECT_PADRE);

-- changeset root:1751558214405-130
CREATE INDEX IDX_OBJ_TIPO_OBJ ON PIG_OBJECT_OLD(ID_TIPO_OBJECT);

-- changeset root:1751558214405-131
CREATE INDEX IDX_OBJ_USR ON PIG_OBJECT_OLD(ID_USER_IAM);

-- changeset root:1751558214405-132
CREATE INDEX IDX_SES_INGEST_ID_OBJECT ON PIG_SESSIONE_INGEST_OLD(ID_OBJECT);

-- changeset root:1751558214405-133
CREATE INDEX IDX_SES_INGEST_KEY_OBJECT ON PIG_SESSIONE_INGEST_OLD(NM_AMBIENTE_VERS, NM_VERS, CD_KEY_OBJECT);

-- changeset root:1751558214405-134
CREATE INDEX IDX_SES_INGEST_KEY_VERS_OBJ ON PIG_SESSIONE_INGEST_OLD(ID_VERS, CD_KEY_OBJECT);

-- changeset root:1751558214405-135
CREATE INDEX IDX_SES_INGEST_STATO_COR ON PIG_SESSIONE_INGEST_OLD(ID_STATO_SESSIONE_INGEST_COR);

-- changeset root:1751558214405-136
CREATE INDEX IDX_SES_INGEST_VERS ON PIG_SESSIONE_INGEST_OLD(ID_VERS, TI_STATO);

-- changeset root:1751558214405-137
CREATE INDEX IDX_TEST ON PIG_UNITA_DOC_OBJECT(ID_OBJECT);

-- changeset root:1751558214405-138
CREATE INDEX IDX_UNITA_DOC_OBJ ON PIG_XML_SACER_UNITA_DOC_OLD(ID_UNITA_DOC_OBJECT);

-- changeset root:1751558214405-139
CREATE INDEX IDX_UNI_DOC_OBJ_ORGANIZ ON PIG_UNITA_DOC_OBJECT_OLD(ID_ORGANIZ_IAM);

-- changeset root:1751558214405-140
CREATE INDEX IDX_UNI_DOC_SES_ORGANIZ ON PIG_UNITA_DOC_SESSIONE_OLD(ID_ORGANIZ_IAM);

-- changeset root:1751558214405-141
ALTER TABLE PIG_FILE_OBJECT_OLD ADD CONSTRAINT FK_FILE_OBJ_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1751558214405-142
ALTER TABLE PIG_FILE_OBJECT_OLD ADD CONSTRAINT FK_FILE_OBJ_TI_FILE_OBJ FOREIGN KEY (ID_TIPO_FILE_OBJECT) REFERENCES PIG_TIPO_FILE_OBJECT (ID_TIPO_FILE_OBJECT);

-- changeset root:1751558214405-143
ALTER TABLE PIG_INFO_DICOM_OLD ADD CONSTRAINT FK_INFO_DICOM_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1751558214405-144
ALTER TABLE PIG_INFO_DICOM_OLD ADD CONSTRAINT FK_INFO_DICOM_XSD_SPEC FOREIGN KEY (ID_XSD_SPEC) REFERENCES PIG_XSD_DATI_SPEC (ID_XSD_SPEC);

-- changeset root:1751558214405-145
ALTER TABLE PIG_OBJECT_OLD ADD CONSTRAINT FK_OBJ_PADRE FOREIGN KEY (ID_OBJECT_PADRE) REFERENCES PIG_OBJECT_OLD (ID_OBJECT);

-- changeset root:1751558214405-146
ALTER TABLE PIG_OBJECT ADD CONSTRAINT FK_OBJ_PADRE_NEW FOREIGN KEY (ID_OBJECT_PADRE) REFERENCES PIG_OBJECT (ID_OBJECT);

-- changeset root:1751558214405-147
ALTER TABLE PIG_OBJECT_OLD ADD CONSTRAINT FK_OBJ_TI_OBJ FOREIGN KEY (ID_TIPO_OBJECT) REFERENCES PIG_TIPO_OBJECT (ID_TIPO_OBJECT);

-- changeset root:1751558214405-148
ALTER TABLE PIG_OBJECT ADD CONSTRAINT FK_OBJ_TI_OBJ_NEW FOREIGN KEY (ID_TIPO_OBJECT) REFERENCES PIG_TIPO_OBJECT (ID_TIPO_OBJECT);

-- changeset root:1751558214405-149
ALTER TABLE PIG_OBJECT_TRASF_OLD ADD CONSTRAINT FK_OBJ_TRASF_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1751558214405-150
ALTER TABLE PIG_OBJECT_TRASF_OLD ADD CONSTRAINT FK_OBJ_TRASF_TI_OBJ FOREIGN KEY (ID_TIPO_OBJECT) REFERENCES PIG_TIPO_OBJECT (ID_TIPO_OBJECT);

-- changeset root:1751558214405-151
ALTER TABLE PIG_OBJECT_TRASF_OLD ADD CONSTRAINT FK_OBJ_TRASF_VERS FOREIGN KEY (ID_VERS) REFERENCES PIG_VERS (ID_VERS) ON DELETE CASCADE;

-- changeset root:1751558214405-152
ALTER TABLE PIG_OBJECT_OLD ADD CONSTRAINT FK_OBJ_USR FOREIGN KEY (ID_USER_IAM) REFERENCES IAM_USER (ID_USER_IAM);

-- changeset root:1751558214405-153
ALTER TABLE PIG_OBJECT ADD CONSTRAINT FK_OBJ_USR_NEW FOREIGN KEY (ID_USER_IAM) REFERENCES IAM_USER (ID_USER_IAM);

-- changeset root:1751558214405-154
ALTER TABLE PIG_OBJECT_OLD ADD CONSTRAINT FK_OBJ_VERS FOREIGN KEY (ID_VERS) REFERENCES PIG_VERS (ID_VERS) ON DELETE CASCADE;

-- changeset root:1751558214405-155
ALTER TABLE PIG_OBJECT ADD CONSTRAINT FK_OBJ_VERS_NEW FOREIGN KEY (ID_VERS) REFERENCES PIG_VERS (ID_VERS) ON DELETE CASCADE;

-- changeset root:1751558214405-156
ALTER TABLE PIG_FILE_OBJECT_STORAGE ADD CONSTRAINT FK_PIG_DEC_BACKEND FOREIGN KEY (ID_DEC_BACKEND) REFERENCES PIG_DEC_BACKEND (ID_DEC_BACKEND);

-- changeset root:1751558214405-157
ALTER TABLE PIG_DEC_CONFIG_OBJECT_STORAGE ADD CONSTRAINT FK_PIG_DEC_BACKEND0 FOREIGN KEY (ID_DEC_BACKEND) REFERENCES PIG_DEC_BACKEND (ID_DEC_BACKEND);

-- changeset root:1751558214405-158
ALTER TABLE XFO_REPORT_OBJECT_STORAGE ADD CONSTRAINT FK_PIG_DEC_BACKEND1 FOREIGN KEY (ID_DEC_BACKEND) REFERENCES PIG_DEC_BACKEND (ID_DEC_BACKEND);

-- changeset root:1751558214405-159
ALTER TABLE PIG_SISMA_DOCUMENTI_STORAGE ADD CONSTRAINT FK_PIG_DEC_BACKEND_PIG_SISMA_DOCUMENTI_STORAGE FOREIGN KEY (ID_DEC_BACKEND) REFERENCES PIG_DEC_BACKEND (ID_DEC_BACKEND);

-- changeset root:1751558214405-160
ALTER TABLE PIG_STRUM_URB_DOCUMENTI_STORAGE ADD CONSTRAINT FK_PIG_DEC_BACKEND_PIG_STRUM_URB_DOCUMENTI_STORAGE FOREIGN KEY (ID_DEC_BACKEND) REFERENCES PIG_DEC_BACKEND (ID_DEC_BACKEND);

-- changeset root:1751558214405-161
ALTER TABLE PIG_FILE_OBJECT_STORAGE ADD CONSTRAINT FK_PIG_FILE_OBJECT FOREIGN KEY (ID_PIG_FILE_OBJECT) REFERENCES PIG_FILE_OBJECT (ID_FILE_OBJECT);

-- changeset root:1751558214405-162
ALTER TABLE XFO_REPORT_OBJECT_STORAGE ADD CONSTRAINT FK_PIG_SESSIONE_INGEST FOREIGN KEY (ID_SESSIONE_INGEST) REFERENCES PIG_SESSIONE_INGEST (ID_SESSIONE_INGEST);

-- changeset root:1751558214405-163
ALTER TABLE PIG_SISMA_DOCUMENTI_STORAGE ADD CONSTRAINT FK_PIG_SISMA_DOCUMENTI FOREIGN KEY (ID_SISMA_DOCUMENTI) REFERENCES PIG_SISMA_DOCUMENTI (ID_SISMA_DOCUMENTI);

-- changeset root:1751558214405-164
ALTER TABLE PIG_STRUM_URB_DOCUMENTI_STORAGE ADD CONSTRAINT FK_PIG_STRUM_URB_DOCUMENTI FOREIGN KEY (ID_STRUM_URB_DOCUMENTI) REFERENCES PIG_STRUM_URB_DOCUMENTI (ID_STRUM_URB_DOCUMENTI);

-- changeset root:1751558214405-165
ALTER TABLE PIG_SESSIONE_INGEST_OLD ADD CONSTRAINT FK_SES_INGEST_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1751558214405-166
ALTER TABLE PIG_SESSIONE_INGEST_OLD ADD CONSTRAINT FK_SES_INGEST_VERS FOREIGN KEY (ID_VERS) REFERENCES PIG_VERS (ID_VERS) ON DELETE CASCADE;

-- changeset root:1751558214405-167
ALTER TABLE PIG_SESSIONE_RECUP ADD CONSTRAINT FK_SES_RECUP_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1751558214405-168
ALTER TABLE PIG_STATO_SESSIONE_INGEST_OLD ADD CONSTRAINT FK_STATO_SES_INGEST FOREIGN KEY (ID_SESSIONE_INGEST) REFERENCES PIG_SESSIONE_INGEST_OLD (ID_SESSIONE_INGEST) ON DELETE CASCADE;

-- changeset root:1751558214405-169
ALTER TABLE PIG_UNITA_DOC_OBJECT_OLD ADD CONSTRAINT FK_UNI_DOC_OBJ_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1751558214405-170
ALTER TABLE PIG_UNITA_DOC_OBJECT_OLD ADD CONSTRAINT FK_UNI_DOC_OBJ_ORG_IAM FOREIGN KEY (ID_ORGANIZ_IAM) REFERENCES SACER_IAM.USR_ORGANIZ_IAM (ID_ORGANIZ_IAM);

-- changeset root:1751558214405-171
ALTER TABLE PIG_UNITA_DOC_SESSIONE_OLD ADD CONSTRAINT FK_UNI_DOC_SES_ORG_IAM FOREIGN KEY (ID_ORGANIZ_IAM) REFERENCES SACER_IAM.USR_ORGANIZ_IAM (ID_ORGANIZ_IAM);

-- changeset root:1751558214405-172
ALTER TABLE PIG_UNITA_DOC_SESSIONE_OLD ADD CONSTRAINT FK_UNI_DOC_SES_SES_INGEST FOREIGN KEY (ID_SESSIONE_INGEST) REFERENCES PIG_SESSIONE_INGEST_OLD (ID_SESSIONE_INGEST) ON DELETE CASCADE;

-- changeset root:1751558214405-173
ALTER TABLE PIG_XML_OBJECT_OLD ADD CONSTRAINT FK_XML_OBJ_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1751558214405-174
ALTER TABLE PIG_XML_OBJECT_TRASF_OLD ADD CONSTRAINT FK_XML_OBJ_TRASF FOREIGN KEY (ID_OBJECT_TRASF) REFERENCES PIG_OBJECT_TRASF_OLD (ID_OBJECT_TRASF) ON DELETE CASCADE;

-- changeset root:1751558214405-175
ALTER TABLE PIG_XML_OBJECT_TRASF_OLD ADD CONSTRAINT FK_XML_OBJ_TRASF_NEW FOREIGN KEY (ID_OBJECT_TRASF) REFERENCES PIG_OBJECT_TRASF (ID_OBJECT_TRASF) ON DELETE CASCADE;

-- changeset root:1751558214405-176
ALTER TABLE PIG_XML_SESSIONE_INGEST_OLD ADD CONSTRAINT FK_XML_SES_INGEST_SES_INGEST FOREIGN KEY (ID_SESSIONE_INGEST) REFERENCES PIG_SESSIONE_INGEST_OLD (ID_SESSIONE_INGEST) ON DELETE CASCADE;

-- changeset root:1751558214405-177
ALTER TABLE PIG_XML_SACER_UNITA_DOC_SES_OLD ADD CONSTRAINT FK_XML_UNI_DOC_SES FOREIGN KEY (ID_UNITA_DOC_SESSIONE) REFERENCES PIG_UNITA_DOC_SESSIONE_OLD (ID_UNITA_DOC_SESSIONE) ON DELETE CASCADE;

-- changeset root:1751558214405-178
ALTER TABLE PIG_XML_SACER_UNITA_DOC_OLD ADD CONSTRAINT FK_XML_UNI_DOC_UNI_DOC_OBJ FOREIGN KEY (ID_UNITA_DOC_OBJECT) REFERENCES PIG_UNITA_DOC_OBJECT_OLD (ID_UNITA_DOC_OBJECT) ON DELETE CASCADE;

-- changeset root:1751558214405-179
ALTER TABLE PIG_XML_SACER_UNITA_DOC ADD CONSTRAINT FK_XML_UNI_DOC_UNI_DOC_OBJ_NEW FOREIGN KEY (ID_UNITA_DOC_OBJECT) REFERENCES PIG_UNITA_DOC_OBJECT (ID_UNITA_DOC_OBJECT) ON DELETE CASCADE;

-- changeset root:1751558214405-180
ALTER TABLE PIG_XML_SACER_UNITA_DOC DROP CONSTRAINT UN_XML_UNI_DOC_NEW DROP INDEX;

-- changeset root:1751558214405-181
ALTER TABLE PIG_XML_SACER_UNITA_DOC_SES DROP CONSTRAINT UN_XML_UNI_DOC_SES_NEW DROP INDEX;

-- changeset root:1751558214405-182
DROP TABLE MD_APPLICATIONFILES;

-- changeset root:1751558214405-183
DROP TABLE MD_APPLICATIONS;

-- changeset root:1751558214405-184
DROP TABLE MD_CATALOGS;

-- changeset root:1751558214405-185
DROP TABLE MD_COLUMNS;

-- changeset root:1751558214405-186
DROP TABLE MD_CONNECTIONS;

-- changeset root:1751558214405-187
DROP TABLE MD_CONSTRAINTS;

-- changeset root:1751558214405-188
DROP TABLE MD_FILE_ARTIFACTS;

-- changeset root:1751558214405-189
DROP TABLE MD_GROUP_MEMBERS;

-- changeset root:1751558214405-190
DROP TABLE MD_INDEX_DETAILS;

-- changeset root:1751558214405-191
DROP TABLE MD_MIGR_PARAMETER;

-- changeset root:1751558214405-192
DROP TABLE MD_OTHER_OBJECTS;

-- changeset root:1751558214405-193
DROP TABLE MD_PARTITIONS;

-- changeset root:1751558214405-194
DROP TABLE MD_PROJECTS;

-- changeset root:1751558214405-195
DROP TABLE MD_REPOVERSIONS;

-- changeset root:1751558214405-196
DROP TABLE MD_SEQUENCES;

-- changeset root:1751558214405-197
DROP TABLE MD_TABLESPACES;

-- changeset root:1751558214405-198
DROP TABLE MD_USERS;

-- changeset root:1751558214405-199
DROP TABLE MD_USER_PRIVILEGES;

-- changeset root:1751558214405-200
ALTER TABLE PIG_SISMA_PIANO_DOC_REQ DROP PRIMARY KEY DROP INDEX;

-- changeset root:1751558214405-1
COMMENT ON COLUMN PIG_DEC_JOB_FOTO.DT_PROSSIMA_ATTIVAZIONE_FOTO IS 'Quando il job verrÃ  eseguito la prossima volta (se Ã¨ attivo).';

-- changeset root:1751558214405-2
ALTER TABLE PIG_SISMA_DOCUMENTI MODIFY NM_FILE_OS NULL;

-- changeset root:1751558214405-3
COMMENT ON COLUMN PIG_DEC_JOB_FOTO.NM_NODO_ASSEGNATO_FOTO IS 'Nome del nodo del cluster su cui verrÃ  eseguito il job';

-- changeset root:1751558214405-4
ALTER TABLE PIG_OBJECT_TRASF DROP PRIMARY KEY DROP INDEX;

-- changeset root:1751558214405-5
CREATE UNIQUE INDEX PK_PIG_OBJECT_TRASF_NEW ON PIG_OBJECT_TRASF(ID_OBJECT_TRASF);

-- changeset root:1751558214405-6
ALTER TABLE PIG_OBJECT_TRASF ADD CONSTRAINT PK_PIG_OBJECT_TRASF_NEW PRIMARY KEY (ID_OBJECT_TRASF) USING INDEX PK_PIG_OBJECT_TRASF_NEW;

-- changeset root:1751558214405-7
ALTER TABLE PIG_XML_OBJECT_TRASF DROP PRIMARY KEY DROP INDEX;

-- changeset root:1751558214405-8
CREATE UNIQUE INDEX PK_XML_OBJ_TRASF_NEW ON PIG_XML_OBJECT_TRASF(ID_XML_OBJECT_TRASF);

-- changeset root:1751558214405-9
ALTER TABLE PIG_XML_OBJECT_TRASF ADD CONSTRAINT PK_XML_OBJ_TRASF_NEW PRIMARY KEY (ID_XML_OBJECT_TRASF) USING INDEX PK_XML_OBJ_TRASF_NEW;

-- changeset root:1751558214405-10
ALTER TABLE PIG_FILE_OBJECT DROP CONSTRAINT UN_FILE_OBJ_NEW DROP INDEX;

-- changeset root:1751558214405-11
CREATE UNIQUE INDEX UN_FILE_OBJ_NEW ON PIG_FILE_OBJECT(ID_OBJECT, NM_FILE_OBJECT);

-- changeset root:1751558214405-12
ALTER TABLE PIG_FILE_OBJECT ADD CONSTRAINT UN_FILE_OBJ_NEW UNIQUE (ID_OBJECT, NM_FILE_OBJECT) USING INDEX UN_FILE_OBJ_NEW;

-- changeset root:1751558214405-13
ALTER TABLE PIG_OBJECT_TRASF DROP CONSTRAINT UN_OBJ_TRASF_NEW DROP INDEX;

-- changeset root:1751558214405-14
CREATE UNIQUE INDEX UN_OBJ_TRASF_NEW ON PIG_OBJECT_TRASF(ID_OBJECT, CD_KEY_OBJECT_TRASF);

-- changeset root:1751558214405-15
ALTER TABLE PIG_OBJECT_TRASF ADD CONSTRAINT UN_OBJ_TRASF_NEW UNIQUE (ID_OBJECT, CD_KEY_OBJECT_TRASF) USING INDEX UN_OBJ_TRASF_NEW;

-- changeset root:1751558214405-16
ALTER TABLE PIG_OBJECT_TRASF DROP CONSTRAINT UN_OBJ_TRASF_PG_NEW DROP INDEX;

-- changeset root:1751558214405-17
CREATE UNIQUE INDEX UN_OBJ_TRASF_PG_NEW ON PIG_OBJECT_TRASF(ID_OBJECT, PG_OGGETTO_TRASF);

-- changeset root:1751558214405-18
ALTER TABLE PIG_OBJECT_TRASF ADD CONSTRAINT UN_OBJ_TRASF_PG_NEW UNIQUE (ID_OBJECT, PG_OGGETTO_TRASF) USING INDEX UN_OBJ_TRASF_PG_NEW;

-- changeset root:1751558214405-19
ALTER TABLE PIG_OBJECT_TRASF DROP CONSTRAINT UN_OBJ_TRASF_VERS_NEW DROP INDEX;

-- changeset root:1751558214405-20
CREATE UNIQUE INDEX UN_OBJ_TRASF_VERS_NEW ON PIG_OBJECT_TRASF(ID_VERS, CD_KEY_OBJECT_TRASF);

-- changeset root:1751558214405-21
ALTER TABLE PIG_OBJECT_TRASF ADD CONSTRAINT UN_OBJ_TRASF_VERS_NEW UNIQUE (ID_VERS, CD_KEY_OBJECT_TRASF) USING INDEX UN_OBJ_TRASF_VERS_NEW;

-- changeset root:1751558214405-22
ALTER TABLE PIG_UNITA_DOC_OBJECT DROP CONSTRAINT UN_UNI_DOC_OBJ_NEW DROP INDEX;

-- changeset root:1751558214405-23
CREATE UNIQUE INDEX UN_UNI_DOC_OBJ_NEW ON PIG_UNITA_DOC_OBJECT(ID_VERS, ID_OBJECT, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER);

-- changeset root:1751558214405-24
ALTER TABLE PIG_UNITA_DOC_OBJECT ADD CONSTRAINT UN_UNI_DOC_OBJ_NEW UNIQUE (ID_VERS, ID_OBJECT, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER) USING INDEX UN_UNI_DOC_OBJ_NEW;

-- changeset root:1751558214405-25
ALTER TABLE PIG_UNITA_DOC_SESSIONE DROP CONSTRAINT UN_UNI_DOC_SES_NEW DROP INDEX;

-- changeset root:1751558214405-26
CREATE UNIQUE INDEX UN_UNI_DOC_SES_NEW ON PIG_UNITA_DOC_SESSIONE(ID_SESSIONE_INGEST, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER);

-- changeset root:1751558214405-27
ALTER TABLE PIG_UNITA_DOC_SESSIONE ADD CONSTRAINT UN_UNI_DOC_SES_NEW UNIQUE (ID_SESSIONE_INGEST, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER) USING INDEX UN_UNI_DOC_SES_NEW;

-- changeset root:1751558214405-28
ALTER TABLE PIG_XML_OBJECT_TRASF DROP CONSTRAINT UN_XML_OBJ_TRASF_NEW DROP INDEX;

-- changeset root:1751558214405-29
CREATE UNIQUE INDEX UN_XML_OBJ_TRASF_NEW ON PIG_XML_OBJECT_TRASF(ID_OBJECT_TRASF);

-- changeset root:1751558214405-30
ALTER TABLE PIG_XML_OBJECT_TRASF ADD CONSTRAINT UN_XML_OBJ_TRASF_NEW UNIQUE (ID_OBJECT_TRASF) USING INDEX UN_XML_OBJ_TRASF_NEW;

-- changeset root:1751558214405-31
DROP INDEX IDX_OBJ_PADRE_NEW;

-- changeset root:1751558214405-32
CREATE INDEX IDX_OBJ_PADRE_NEW ON PIG_OBJECT(ID_OBJECT_PADRE);

-- changeset root:1751558214405-33
DROP INDEX IDX_SES_INGEST_STATO_COR_NEW;

-- changeset root:1751558214405-34
CREATE INDEX IDX_SES_INGEST_STATO_COR_NEW ON PIG_SESSIONE_INGEST(ID_STATO_SESSIONE_INGEST_COR);

-- changeset root:1751558214405-35
ALTER TABLE PIG_DEC_JOB_FOTO DROP PRIMARY KEY DROP INDEX;

-- changeset root:1751558214405-36
CREATE UNIQUE INDEX PK_JOB_FOTO ON PIG_DEC_JOB_FOTO(ID_JOB_FOTO);

-- changeset root:1751558214405-37
ALTER TABLE PIG_DEC_JOB_FOTO ADD CONSTRAINT PK_JOB_FOTO PRIMARY KEY (ID_JOB_FOTO) USING INDEX PK_JOB_FOTO;

-- changeset root:1751558214405-38
ALTER TABLE PIG_SESSIONE_INGEST DROP PRIMARY KEY DROP INDEX;

-- changeset root:1751558214405-39
CREATE UNIQUE INDEX PK_SES_INGEST_NEW ON PIG_SESSIONE_INGEST(ID_SESSIONE_INGEST);

-- changeset root:1751558214405-40
ALTER TABLE PIG_SESSIONE_INGEST ADD CONSTRAINT PK_SES_INGEST_NEW PRIMARY KEY (ID_SESSIONE_INGEST) USING INDEX PK_SES_INGEST_NEW;

-- changeset root:1751558214405-41
ALTER TABLE PIG_UNITA_DOC_SESSIONE DROP PRIMARY KEY DROP INDEX;

-- changeset root:1751558214405-42
CREATE UNIQUE INDEX PK_UNI_DOC_SES_NEW ON PIG_UNITA_DOC_SESSIONE(ID_UNITA_DOC_SESSIONE);

-- changeset root:1751558214405-43
ALTER TABLE PIG_UNITA_DOC_SESSIONE ADD CONSTRAINT PK_UNI_DOC_SES_NEW PRIMARY KEY (ID_UNITA_DOC_SESSIONE) USING INDEX PK_UNI_DOC_SES_NEW;

-- changeset root:1751558214405-44
ALTER TABLE PIG_XML_OBJECT DROP PRIMARY KEY DROP INDEX;

-- changeset root:1751558214405-45
CREATE UNIQUE INDEX PK_XML_OBJ_NEW ON PIG_XML_OBJECT(ID_XML_OBJECT);

-- changeset root:1751558214405-46
ALTER TABLE PIG_XML_OBJECT ADD CONSTRAINT PK_XML_OBJ_NEW PRIMARY KEY (ID_XML_OBJECT) USING INDEX PK_XML_OBJ_NEW;

-- changeset root:1751558214405-47
ALTER TABLE PIG_XML_SESSIONE_INGEST DROP PRIMARY KEY DROP INDEX;

-- changeset root:1751558214405-48
CREATE UNIQUE INDEX PK_XML_SES_INGEST_NEW ON PIG_XML_SESSIONE_INGEST(ID_XML_SESSIONE_INGEST);

-- changeset root:1751558214405-49
ALTER TABLE PIG_XML_SESSIONE_INGEST ADD CONSTRAINT PK_XML_SES_INGEST_NEW PRIMARY KEY (ID_XML_SESSIONE_INGEST) USING INDEX PK_XML_SES_INGEST_NEW;

-- changeset root:1751558214405-50
ALTER TABLE PIG_DEC_JOB_FOTO DROP CONSTRAINT UN_JOB_FOTO DROP INDEX;

-- changeset root:1751558214405-51
CREATE UNIQUE INDEX UN_JOB_FOTO ON PIG_DEC_JOB_FOTO(NM_JOB_FOTO);

-- changeset root:1751558214405-52
ALTER TABLE PIG_DEC_JOB_FOTO ADD CONSTRAINT UN_JOB_FOTO UNIQUE (NM_JOB_FOTO) USING INDEX UN_JOB_FOTO;

-- changeset root:1751558214405-53
CREATE OR REPLACE FORCE VIEW MON_V_CALC_STATO_OBJ_DA_TRASF (ID_OGGETTO_PADRE, TI_STATO_OBJECT_PADRE) AS SELECT obj_da_trasf.id_object id_oggetto_padre
	,CASE 
		WHEN NOT EXISTS (
				SELECT 1 FROM PIG_OBJECT obj_figlio
				JOIN MON_V_CHK_OBJ_TERMINATO figlio_terminato ON figlio_terminato.id_object = obj_figlio.id_object
				WHERE 
					obj_figlio.id_object_padre = obj_da_trasf.id_object
					AND figlio_terminato.fl_object_terminato = '0')
			THEN CASE 
					WHEN NOT EXISTS (SELECT 1 FROM PIG_OBJECT obj_figlio
										WHERE 
											obj_figlio.id_object_padre = obj_da_trasf.id_object
											AND obj_figlio.ti_stato_object != 'ANNULLATO')
						THEN 'ANNULLATO'
					ELSE CASE 
							WHEN EXISTS (SELECT 1 FROM PIG_OBJECT obj_figlio
										 JOIN PIG_UNITA_DOC_OBJECT ud_obj ON ud_obj.id_object = obj_figlio.id_object
										 WHERE obj_figlio.id_object_padre = obj_da_trasf.id_object
										 AND ud_obj.ti_stato_unita_doc_object = 'VERSATA_ERR'
										 AND ud_obj.cd_err_sacer NOT IN ('UD-002','UD-002-001'))									
							THEN 'CHIUSO_ERR_VERS'
							ELSE 'CHIUSO_OK'
							END
					END
		ELSE NULL
		END ti_stato_object_padre
FROM PIG_OBJECT obj_da_trasf;

-- changeset root:1751558214405-54
CREATE OR REPLACE FORCE VIEW MON_V_LIS_FILE_OBJECT (ID_OBJECT, ID_FILE_OBJECT, NM_FILE_OBJECT, ID_TIPO_FILE_OBJECT, NM_TIPO_FILE_OBJECT, DS_HASH_FILE_VERS, TI_ALGO_HASH_FILE_VERS, CD_ENCODING_HASH_FILE_VERS, NI_SIZE_FILE_VERS, NM_BUCKET, CD_KEY_FILE, ID_DEC_BACKEND) AS select
file_obj.id_object,
file_obj.id_file_object,
file_obj.nm_file_object,
file_obj.id_tipo_file_object,
tipo_file.nm_tipo_file_object,
file_obj.ds_hash_file_vers,
file_obj.ti_algo_hash_file_vers,
file_obj.cd_encoding_hash_file_vers,
file_obj.ni_size_file_vers,
fos.nm_bucket,
fos.cd_key_file,
fos.id_dec_backend

from PIG_FILE_OBJECT file_obj
join PIG_TIPO_FILE_OBJECT tipo_file
on (tipo_file.id_tipo_file_object = file_obj.id_tipo_file_object)
left join PIG_FILE_OBJECT_STORAGE fos
on (file_obj.id_file_object = fos.id_pig_file_object);

-- changeset root:1751558214405-55
CREATE OR REPLACE FORCE VIEW MON_V_OBJ_RANGE_DT (ID_VERS, ID_OBJECT, CD_KEY_OBJECT, ID_TIPO_OBJECT, TI_STATO_OBJECT, TI_DT_CREAZIONE, TI_CLASSE_VERS_FILE) AS WITH MultiVersatore
AS
(
    SELECT DISTINCT
        pv.id_vers id_vers_padre,
        pvt.id_vers_gen id_vers
    FROM pig_vers pv
        LEFT JOIN pig_tipo_object pto ON pto.id_vers = pv.id_vers
        LEFT JOIN pig_vers_tipo_object_da_trasf pvt ON pvt.id_tipo_object_da_trasf = pto.id_tipo_object
    WHERE
    pv.fl_cessato = 0
    AND pv.id_vers <> pvt.id_vers_gen
)
SELECT
		   obj.id_vers,
           obj.id_object,
		   obj.cd_key_object,
           obj.id_tipo_object,
           CASE
               WHEN ti_obj.ti_vers_file = 'DA_TRASFORMARE' THEN
                   CASE
                       WHEN obj.ti_stato_object != 'VERSATO_A_PING' THEN
                           CASE
                               WHEN obj.ti_stato_object = 'CHIUSO_OK' THEN
                                   CASE
                                       WHEN EXISTS
                                                (SELECT 1 FROM PIG_UNITA_DOC_OBJECT ud
                                                    INNER JOIN PIG_OBJECT figlio ON figlio.id_object_padre = obj.id_object AND figlio.id_object = ud.id_object
                                                    WHERE
                                                    figlio.id_object = ud.id_object
                                                    AND (ud.id_vers = vers.id_vers OR ud.id_vers IN (SELECT v.id_vers FROM MultiVersatore v WHERE v.id_vers_padre = vers.id_vers))
                                                    AND (ud.ti_stato_unita_doc_object = 'VERSATA_ERR' AND ud.cd_err_sacer IN ('UD-002','UD-002-001'))) THEN 'WARNING_CHIAVE_DUPLICATA'
                                       ELSE
                                           obj.ti_stato_object
                                   END
                               ELSE
                                   obj.ti_stato_object
                           END
                       ELSE
                           CASE
                               WHEN EXISTS
                                        (SELECT 1 FROM PIG_OBJECT figlio
                                            WHERE
                                                figlio.id_object_padre = obj.id_object
                                                AND figlio.ti_stato_object IN ('IN_ATTESA_SCHED', 'IN_CODA_HASH')
                                                AND (figlio.id_vers = vers.id_vers OR figlio.id_vers IN (SELECT v.id_vers FROM MultiVersatore v WHERE v.id_vers_padre = vers.id_vers))
                                                ) THEN
                                   'VERSATO_A_PING'
                               ELSE
                                   CASE
                                       WHEN EXISTS
                                                (SELECT 1 FROM PIG_OBJECT figlio
                                                    WHERE
                                                        figlio.id_object_padre = obj.id_object
                                                        AND figlio.ti_stato_object IN ('CHIUSO_ERR_SCHED', 'CHIUSO_ERR_VERIFICA_HASH')
                                                        AND (figlio.id_vers = vers.id_vers OR figlio.id_vers IN (SELECT v.id_vers FROM MultiVersatore v WHERE v.id_vers_padre = vers.id_vers))
                                                        ) THEN
                                            'PROBLEMA_PREPARAZIONE_SIP'
                                       ELSE
                                           CASE
                                               WHEN EXISTS
                                                        (SELECT 1 FROM PIG_OBJECT figlio
                                                            WHERE
                                                                figlio.id_object_padre = obj.id_object
                                                                AND figlio.ti_stato_object IN ('CHIUSO_ERR_CODA','CHIUSO_ERR_VERS')) THEN
                                                   'PROBLEMA_VERS_SACER'
                                               ELSE
                                                   'IN_CORSO_VERS_SACER'
                                           END
                                   END
                           END
                   END
               ELSE
                   CASE
                       WHEN obj.ti_stato_object = 'CHIUSO_OK' THEN
                           CASE
                               WHEN EXISTS
                                        (SELECT 1 FROM PIG_UNITA_DOC_OBJECT ud
                                            WHERE
                                                ud.id_object = obj.id_object
                                                AND (ud.id_vers = vers.id_vers OR ud.id_vers IN (SELECT v.id_vers FROM MultiVersatore v WHERE v.id_vers_padre = vers.id_vers))
                                                AND (ti_stato_unita_doc_object = 'VERSATA_ERR' AND cd_err_sacer IN ('UD-002', 'UD-002-001'))) THEN
                                    'WARNING_CHIAVE_DUPLICATA'
                               ELSE
                                   obj.ti_stato_object
                           END
                       ELSE
                           obj.ti_stato_object
                   END
           END    ti_stato_object,
           CASE
               WHEN stato_cor.ts_reg_stato BETWEEN TRUNC (SYSDATE) AND SYSDATE + 1 / 24 THEN 'CORR'
               WHEN stato_cor.ts_reg_stato BETWEEN TRUNC (SYSDATE - 6) AND TO_DATE (TO_CHAR (TRUNC (SYSDATE - 1),'dd-mm-yyyy') || ' 23:59:59','dd-mm-yyyy HH24:mi:ss') THEN '6_GG_PREC_CORR'
               ELSE
                   'PREC_6_GG_PREC_CORR'
           END ti_dt_creazione,
           CASE
               WHEN ti_obj.ti_vers_file IN ('NO_ZIP', 'ZIP_CON_XML_SACER', 'ZIP_NO_XML_SACER') THEN 'NON_DA_TRASFORMARE'
               ELSE
                   'DA_TRASFORMARE'
           END ti_classe_vers_file
      FROM PIG_OBJECT obj
      INNER JOIN PIG_TIPO_OBJECT ti_obj ON (ti_obj.id_tipo_object = obj.id_tipo_object)
      INNER JOIN PIG_VERS vers ON (ti_obj.id_vers = vers.id_vers AND vers.id_vers = obj.id_vers)
      INNER JOIN PIG_SESSIONE_INGEST ses ON (ses.id_sessione_ingest = obj.id_last_sessione_ingest)
      INNER JOIN PIG_STATO_SESSIONE_INGEST stato_cor ON (stato_cor.id_stato_sessione_ingest = ses.id_stato_sessione_ingest_cor)
      WHERE obj.ti_stato_object IN ('CHIUSO_OK',
                                    'IN_CODA_HASH',
                                   'IN_ATTESA_FILE',
                                   'IN_ATTESA_SCHED',
                                   'IN_ATTESA_VERS',
                                   'IN_CODA_VERS',
                                   'WARNING',
                                   'CHIUSO_WARNING',
                                   'DA_TRASFORMARE',
                                   'TRASFORMAZIONE_NON_ATTIVA',
                                   'TRASFORMAZIONE_IN_CORSO',
                                   'PREPARAZIONE_OGG_IN_CORSO',
                                   'TRASFORMATO',
                                   'VERSATO_A_PING',
                                   'ERRORE_TRASFORMAZIONE',
                                   'WARNING_TRASFORMAZIONE',
                                   'ERRORE_VERSAMENTO_A_PING')
       AND vers.fl_cessato = 0
       AND obj.id_vers = vers.id_vers;

-- changeset root:1751558214405-56
CREATE OR REPLACE FORCE VIEW MON_V_VIS_LAST_SCHED_JOB (ID_LOG_JOB, NM_JOB, DT_REG_LOG_JOB_INI, FL_JOB_ATTIVO, LAST_EXEC_OK) AS select max (tab1.id_log_job), tab1.nm_job,tab1.dt_reg_log_job_ini, tab1.fl_job_attivo,tab1.LAST_EXEC_OK
  from (
  SELECT inizio_job.id_log_job,
           inizio_job.nm_job,
           inizio_job.dt_reg_log_job    dt_reg_log_job_ini,
           CASE
               WHEN EXISTS
                        (SELECT *
                           FROM PIG_LOG_JOB fine_job
                          WHERE fine_job.nm_job = inizio_job.nm_job
                            AND fine_job.ti_reg_log_job IN
                                    ('FINE_SCHEDULAZIONE', 'ERRORE')
                            AND fine_job.dt_reg_log_job >=
                                inizio_job.dt_reg_log_job) THEN
                   '0'
               ELSE
                   '1'
           END                          fl_job_attivo,
           CASE
               WHEN EXISTS
                        (SELECT *
                           FROM PIG_LOG_JOB fine_job
                          WHERE fine_job.nm_job = inizio_job.nm_job
                            AND fine_job.ti_reg_log_job IN
                                    ('FINE_SCHEDULAZIONE')
                            AND fine_job.dt_reg_log_job >=
                                inizio_job.dt_reg_log_job) THEN
                   '1'
               ELSE
                   '0'
           END                          last_exec_ok
      FROM PIG_LOG_JOB inizio_job
     WHERE inizio_job.ti_reg_log_job = 'INIZIO_SCHEDULAZIONE'
       AND inizio_job.dt_reg_log_job =
           (SELECT MAX (inizio_job_max.dt_reg_log_job)
              FROM PIG_LOG_JOB inizio_job_max
             WHERE inizio_job_max.nm_job = inizio_job.nm_job
               AND inizio_job_max.ti_reg_log_job = 'INIZIO_SCHEDULAZIONE'
               )) tab1
group by  tab1.nm_job,tab1.dt_reg_log_job_ini, tab1.fl_job_attivo,tab1.LAST_EXEC_OK;

-- changeset root:1751558214405-57
CREATE OR REPLACE FORCE VIEW MON_V_VIS_OBJ_TRASF (ID_OBJECT_TRASF, ID_VERS_TRASF, NM_AMBIENTE_VERS_TRASF, NM_VERS_TRASF, CD_KEY_OBJECT_TRASF, PG_OGGETTO_TRASF, NM_TIPO_OBJECT_TRASF, DS_OBJECT_TRASF, DS_PATH, DS_PATH_TRASF, DS_HASH_FILE_VERS, TI_ALGO_HASH_FILE_VERS, CD_ENCODING_HASH_FILE_VERS, TI_STATO_TRASF, CD_ERR, DL_ERR, NM_AMBIENTE_VERS_DA_TRASF, NM_VERS_DA_TRASF, ID_VERS_DA_TRASF, CD_KEY_OBJECT_DA_TRASF, ID_OBJECT_DA_TRASF, NM_TIPO_OBJECT_DA_TRASF, DS_OBJECT_DA_TRASF, NI_TOT_OBJECT_TRASF, TI_STATO_OBJECT_DA_TRASF, DT_STATO_COR_DA_TRASF) AS select
 obj_trasf.id_object_trasf,
 
 obj_trasf.id_vers id_vers_trasf,
 amb_trasf.nm_ambiente_vers  nm_ambiente_vers_trasf, vers_trasf.nm_vers nm_vers_trasf, obj_trasf.cd_key_object_trasf,
 obj_trasf.pg_oggetto_trasf,
 ti_obj_trasf.nm_tipo_object nm_tipo_object_trasf,
 obj_trasf.ds_object_trasf,
 obj_trasf.ds_path,
 
 --vers_trasf.ds_path_trasf,
 (select val.ds_valore_param_applic from PIG_PARAM_APPLIC par
join PIG_VALORE_PARAM_APPLIC val
	on (val.id_param_applic = par.id_param_applic)
where par.nm_param_applic = 'DS_PATH_OUTPUT_FTP' and val.id_vers = vers_trasf.id_vers),
 obj_trasf.ds_hash_file_vers,
 obj_trasf.ti_algo_hash_file_vers,
 obj_trasf.cd_encoding_hash_file_vers,

 obj.ti_stato_object ti_stato_trasf,
 obj_trasf.cd_err,
 obj_trasf.dl_err,
 
 
 amb_da_trasf.nm_ambiente_vers  nm_ambiente_vers_da_trasf, vers_da_trasf.nm_vers nm_vers_da_trasf, vers_da_trasf.id_vers id_vers_da_trasf, obj_da_trasf.cd_key_object cd_key_object_da_trasf,
 obj_da_trasf.id_object id_object_da_trasf,
 ti_obj_da_trasf.nm_tipo_object nm_tipo_object_da_trasf,
 obj_da_trasf.ds_object ds_object_da_trasf,
 obj_da_trasf.ni_tot_object_trasf,
 obj_da_trasf.ti_stato_object ti_stato_object_da_trasf,
 stato_da_trasf.ts_reg_stato dt_stato_cor_da_trasf
 
from PIG_OBJECT_TRASF obj_trasf
join PIG_TIPO_OBJECT ti_obj_trasf
 on (ti_obj_trasf.id_tipo_object = obj_trasf.id_tipo_object)
join PIG_VERS vers_trasf
 on (vers_trasf.id_vers = obj_trasf.id_vers)
join PIG_AMBIENTE_VERS amb_trasf
 on (amb_trasf.id_ambiente_vers = vers_trasf.id_ambiente_vers)
 
left join PIG_OBJECT obj
 on (obj.id_vers = obj_trasf.id_vers
 and obj.cd_key_object = obj_trasf.cd_key_object_trasf
 and obj.pg_oggetto_trasf  = obj_trasf.pg_oggetto_trasf)

join PIG_OBJECT obj_da_trasf
 on (obj_da_trasf.id_object = obj_trasf.id_object)
join PIG_TIPO_OBJECT ti_obj_da_trasf
 on (ti_obj_da_trasf.id_tipo_object = obj_da_trasf.id_tipo_object)
join PIG_VERS vers_da_trasf
 on (vers_da_trasf.id_vers = obj_da_trasf.id_vers)
join PIG_AMBIENTE_VERS amb_da_trasf
 on (amb_da_trasf.id_ambiente_vers = vers_da_trasf.id_ambiente_vers)
join PIG_SESSIONE_INGEST ses_da_trasf
 on (ses_da_trasf.id_sessione_ingest = obj_da_trasf.id_last_sessione_ingest)
join PIG_STATO_SESSIONE_INGEST stato_da_trasf
 on (stato_da_trasf.id_stato_sessione_ingest = ses_da_trasf.id_stato_sessione_ingest_cor);

-- changeset root:1751558214405-58
CREATE OR REPLACE FORCE VIEW PIG_V_SISMA_CHECKS (ID_SISMA, FL_VERIFICA_IN_CORSO, FL_VERIFICA_ERRATA, FL_FILE_MANCANTE) AS SELECT sISMA.id_SISMA,
       CASE
           WHEN EXISTS
                  (SELECT 1
                   FROM pig_SISMA_documenti docs
                   WHERE docs.id_SISMA = sISMA.id_SISMA
                     AND (docs.FL_ESITO_VERIFICA = '0'
                          AND docs.fl_deleted = '0')--                   (docs.FL_ESITO_VERIFICA = 1 AND docs.err_desc is not null AND docs.fl_deleted = 0) or
 ) THEN '1'
           ELSE '0'
       END AS "FL_VERIFICA_IN_CORSO",
       CASE
           WHEN EXISTS
                  (SELECT 1
                   FROM pig_SISMA_documenti docs
                   WHERE docs.id_SISMA = sISMA.id_SISMA
                     AND docs.FL_ESITO_VERIFICA = '1'
                     AND (docs.cd_err IS NOT NULL
                          OR docs.ds_err IS NOT NULL)
                     AND docs.fl_deleted = '0') THEN '1'
           ELSE '0'
       END AS "FL_VERIFICA_ERRATA",
       CASE
           WHEN EXISTS
                  (SELECT 1
                   FROM pig_sisma_piano_doc_req req
                   JOIN pig_sisma_fase_progetto fase_progetto ON (fase_progetto.id_sisma_fase_progetto = req.id_sisma_fase_progetto)
                   JOIN pig_sisma_val_doc doc ON (doc.id_sisma_val_doc = req.id_pig_sisma_val_doc)
                   WHERE req.id_sisma_fase_progetto = sisma.id_sisma_fase_progetto
                     AND req.fl_doc_obbligatorio = '1'
                     AND NOT EXISTS
                       (SELECT 1
                        FROM pig_sisma_documenti docs
                        WHERE docs.id_sisma = sisma.id_sisma
                          AND docs.fl_deleted = '0'
                          AND req.id_pig_sisma_val_doc = docs.id_sisma_val_doc)) THEN '1'
           ELSE '0'
       END AS "FL_FILE_MANCANTE"
FROM pig_SISMA SISMA;

