-- liquibase formatted sql

-- changeset root:1753259610914-1
CREATE OR REPLACE FORCE VIEW "V_USR_IAM" ("ID_USER_IAM", "NM_COGNOME_USER", "NM_NOME_USER", "FL_ATTIVO", "NM_USERID", "CD_PWD", "CD_SALT", "NM_AMBIENTE", "NM_ENTE", "ID_STRUT", "NM_STRUT") AS select 
  u.id_user_iam,  
  u.NM_COGNOME_USER,
  u.NM_NOME_USER,
  u.FL_ATTIVO,
  u.NM_USERID, 
  u.CD_PSW,
  u.CD_SALT,

  amb.nm_ambiente,
  e.nm_ente,
  s.id_strut,
  s.nm_strut 
  from SACER.IAM_USER u
  join SACER.IAM_ABIL_ORGANIZ o 
  on u.id_user_iam = o.id_user_iam 
  
  
  join SACER.org_strut s
  on o.id_organiz_applic = s.id_strut
  join SACER.org_ente e
  on e.id_ente = s.id_ente
  join SACER.org_ambiente amb
  on amb.id_ambiente = e.id_ambiente;

-- changeset root:1753259610914-2
CREATE OR REPLACE FORCE VIEW "V_DEC_TIPO_UNITA_DOC" ("ID_TIPO_UNITA_DOC", "ID_STRUT", "NM_TIPO_UNITA_DOC", "DS_TIPO_UNITA_DOC", "CD_SERIE", "DT_ISTITUZ", "DT_SOPPRES", "TI_SAVE_FILE", "ID_CATEG_TIPO_UNITA_DOC", "ID_USER_IAM") AS SELECT ID_TIPO_UNITA_DOC,
    tipo_ud.ID_STRUT,
    tipo_ud.NM_TIPO_UNITA_DOC,
    tipo_ud.DS_TIPO_UNITA_DOC,
    tipo_ud.CD_SERIE,    
    tipo_ud.DT_ISTITUZ,
    tipo_ud.DT_SOPPRES,
    tipo_ud.TI_SAVE_FILE,
    tipo_ud.ID_CATEG_TIPO_UNITA_DOC,
	abil_org.id_user_iam
  FROM SACER.DEC_TIPO_UNITA_DOC tipo_ud
  join SACER.IAM_ABIL_ORGANIZ abil_org
    on (abil_org.id_organiz_applic = tipo_ud.id_strut)
  join SACER.IAM_ABIL_TIPO_DATO abil_dato
    on (abil_dato.id_abil_organiz = abil_org.id_abil_organiz
	and abil_dato.nm_classe_tipo_dato = 'TIPO_UNITA_DOC'
	and abil_dato.id_tipo_dato_applic = tipo_ud.id_tipo_unita_doc)
  WHERE tipo_ud.DT_SOPPRES >= sysdate
  AND tipo_ud.DT_ISTITUZ   <= sysdate;

-- changeset root:1753259610914-3
CREATE OR REPLACE FORCE VIEW "V_DEC_REGISTRO_UNITA_DOC" ("ID_REGISTRO_UNITA_DOC", "ID_STRUT", "CD_REGISTRO_UNITA_DOC", "DS_REGISTRO_UNITA_DOC", "DT_ISTITUZ", "DT_SOPPRES", "FL_REGISTRO_FISC", "ID_USER_IAM") AS SELECT reg.ID_REGISTRO_UNITA_DOC,
    reg.ID_STRUT,
    reg.CD_REGISTRO_UNITA_DOC,
    reg.DS_REGISTRO_UNITA_DOC,
    reg.DT_ISTITUZ,
    reg.DT_SOPPRES,
    reg.FL_REGISTRO_FISC,
	abil_org.id_user_iam
  FROM SACER.DEC_REGISTRO_UNITA_DOC reg
  join SACER.IAM_ABIL_ORGANIZ abil_org
    on (abil_org.id_organiz_applic = reg.id_strut)
  join SACER.IAM_ABIL_TIPO_DATO abil_dato
    on (abil_dato.id_abil_organiz = abil_org.id_abil_organiz
	and abil_dato.nm_classe_tipo_dato = 'REGISTRO'
	and abil_dato.id_tipo_dato_applic = reg.id_registro_unita_doc)
  WHERE reg.DT_SOPPRES >= sysdate
  AND reg.DT_ISTITUZ   <= sysdate;

-- changeset root:1753259610914-4
CREATE OR REPLACE FORCE VIEW "V_DEC_TIPO_DOC" ("ID_TIPO_DOC", "ID_STRUT", "NM_TIPO_DOC", "DS_TIPO_DOC", "FL_TIPO_DOC_PRINCIPALE", "DT_ISTITUZ", "DT_SOPPRES", "ID_USER_IAM") AS SELECT tipo_doc.ID_TIPO_DOC,
    tipo_doc.ID_STRUT,
    tipo_doc.NM_TIPO_DOC,
    tipo_doc.DS_TIPO_DOC,
    tipo_doc.FL_TIPO_DOC_PRINCIPALE,   
    tipo_doc.DT_ISTITUZ,
    tipo_doc.DT_SOPPRES,   
	abil_org.id_user_iam
  FROM SACER.DEC_TIPO_DOC tipo_doc
  join SACER.IAM_ABIL_ORGANIZ abil_org
    on (abil_org.id_organiz_applic = tipo_doc.id_strut)
  join SACER.IAM_ABIL_TIPO_DATO abil_dato
    on (abil_dato.id_abil_organiz = abil_org.id_abil_organiz
	and abil_dato.nm_classe_tipo_dato = 'TIPO_DOC'
	and abil_dato.id_tipo_dato_applic = tipo_doc.id_tipo_doc)
  WHERE tipo_doc.DT_SOPPRES >= sysdate
  AND tipo_doc.DT_ISTITUZ   <= sysdate;

-- changeset root:1753259610914-5
CREATE OR REPLACE FORCE VIEW "V_DEC_ATTRIB_DATI_SPEC" ("ID_ATTRIB_DATI_SPEC", "ID_STRUT", "TI_USO_ATTRIB", "TI_ENTITA_SACER", "ID_TIPO_UNITA_DOC", "ID_TIPO_DOC", "ID_TIPO_COMP_DOC", "NM_SISTEMA_MIGRAZ", "NM_ATTRIB_DATI_SPEC", "DS_ATTRIB_DATI_SPEC") AS select "ID_ATTRIB_DATI_SPEC","ID_STRUT","TI_USO_ATTRIB","TI_ENTITA_SACER","ID_TIPO_UNITA_DOC","ID_TIPO_DOC","ID_TIPO_COMP_DOC","NM_SISTEMA_MIGRAZ","NM_ATTRIB_DATI_SPEC","DS_ATTRIB_DATI_SPEC" 
  from SACER.DEC_ATTRIB_DATI_SPEC;

-- changeset root:1753259610914-6
CREATE OR REPLACE FORCE VIEW "V_DEC_ESTENSIONE_FILE" ("ID_ESTENSIONE_FILE", "ID_FORMATO_FILE_STANDARD", "CD_ESTENSIONE_FILE") AS select "ID_ESTENSIONE_FILE","ID_FORMATO_FILE_STANDARD","CD_ESTENSIONE_FILE" 
  from SACER.DEC_ESTENSIONE_FILE;

-- changeset root:1753259610914-7
CREATE OR REPLACE FORCE VIEW "V_DEC_FORMATO_FILE_AMMESSO" ("ID_FORMATO_FILE_AMMESSO", "ID_TIPO_COMP_DOC", "ID_FORMATO_FILE_DOC") AS select "ID_FORMATO_FILE_AMMESSO","ID_TIPO_COMP_DOC","ID_FORMATO_FILE_DOC" 
  from SACER.DEC_FORMATO_FILE_AMMESSO;

-- changeset root:1753259610914-8
CREATE OR REPLACE FORCE VIEW "V_DEC_TIPO_COMP_DOC" ("ID_TIPO_COMP_DOC", "ID_TIPO_STRUT_DOC", "ID_STRUT", "NM_TIPO_COMP_DOC", "DS_TIPO_COMP_DOC", "DT_ISTITUZ", "DT_SOPPRES", "TI_USO_COMP_DOC", "NM_FORMATO_FILE_DOC", "DS_FORMATO_FILE_DOC", "ID_FORMATO_FILE_DOC") AS select 
  comp.ID_TIPO_COMP_DOC, 
  comp.ID_TIPO_STRUT_DOC, 
  strut.id_strut, 
  comp.NM_TIPO_COMP_DOC, 
  comp.DS_TIPO_COMP_DOC, 
  comp.DT_ISTITUZ, 
  comp.DT_SOPPRES, 
  comp.TI_USO_COMP_DOC, 
  formdoc.nm_formato_file_doc, 
  formdoc.ds_formato_file_doc, 
  formdoc.id_formato_file_doc
  
  from SACER.DEC_TIPO_COMP_DOC comp 
  join SACER.DEC_TIPO_STRUT_DOC strut 
on (comp.ID_TIPO_STRUT_DOC = strut.ID_TIPO_STRUT_DOC) 

join SACER.dec_formato_file_ammesso formamm
on (formamm.id_tipo_comp_doc = comp.id_tipo_comp_doc)

join SACER.dec_formato_file_doc formdoc
on (formamm.id_formato_file_doc = formdoc.id_formato_file_doc)

where strut.NM_TIPO_STRUT_DOC = 'DocumentoGenerico'  
and  comp.DT_SOPPRES >= sysdate
and comp.DT_ISTITUZ   <= sysdate;

-- changeset root:1753259610914-9
CREATE OR REPLACE FORCE VIEW "V_DEC_FORMATO_FILE_BUSTA" ("ID_FORMATO_FILE_BUSTA", "ID_FORMATO_FILE_STANDARD", "TI_FORMATO_FIRMA_MARCA") AS select "ID_FORMATO_FILE_BUSTA","ID_FORMATO_FILE_STANDARD","TI_FORMATO_FIRMA_MARCA" 
  from SACER.DEC_FORMATO_FILE_BUSTA;

-- changeset root:1753259610914-10
CREATE OR REPLACE FORCE VIEW "V_DEC_FORMATO_FILE_DOC" ("ID_FORMATO_FILE_DOC", "ID_STRUT", "NM_FORMATO_FILE_DOC", "DS_FORMATO_FILE_DOC", "CD_VERSIONE", "DT_ISTITUZ", "DT_SOPPRES") AS select "ID_FORMATO_FILE_DOC","ID_STRUT","NM_FORMATO_FILE_DOC","DS_FORMATO_FILE_DOC","CD_VERSIONE","DT_ISTITUZ","DT_SOPPRES" 
  from SACER.DEC_FORMATO_FILE_DOC where DT_SOPPRES >= (CURRENT_DATE) and DT_ISTITUZ <= (CURRENT_DATE);

-- changeset root:1753259610914-11
CREATE OR REPLACE FORCE VIEW "V_DEC_FORMATO_FILE_STANDARD" ("ID_FORMATO_FILE_STANDARD", "NM_FORMATO_FILE_STANDARD", "DS_FORMATO_FILE_STANDARD", "CD_VERSIONE", "DS_COPYRIGHT", "NM_MIMETYPE_FILE", "TI_ESITO_CONTR_FORMATO", "FL_FORMATO_CONCAT") AS select "ID_FORMATO_FILE_STANDARD","NM_FORMATO_FILE_STANDARD","DS_FORMATO_FILE_STANDARD","CD_VERSIONE","DS_COPYRIGHT","NM_MIMETYPE_FILE","TI_ESITO_CONTR_FORMATO","FL_FORMATO_CONCAT" 
  from SACER.DEC_FORMATO_FILE_STANDARD;

-- changeset root:1753259610914-12
CREATE OR REPLACE FORCE VIEW "V_DEC_TIPO_DOC_AMMESSO" ("ID_TIPO_DOC_AMMESSO", "ID_TIPO_STRUT_UNITA_DOC", "ID_TIPO_DOC", "TI_DOC", "FL_OBBL") AS select "ID_TIPO_DOC_AMMESSO","ID_TIPO_STRUT_UNITA_DOC","ID_TIPO_DOC","TI_DOC","FL_OBBL" 
  from SACER.DEC_TIPO_DOC_AMMESSO;

-- changeset root:1753259610914-13
CREATE OR REPLACE FORCE VIEW "V_DEC_TIPO_RAPPR_COMP" ("ID_TIPO_RAPPR_COMP", "ID_STRUT", "NM_TIPO_RAPPR_COMP", "DS_TIPO_RAPPR_COMP", "DT_ISTITUZ", "DT_SOPPRES") AS select "ID_TIPO_RAPPR_COMP","ID_STRUT","NM_TIPO_RAPPR_COMP","DS_TIPO_RAPPR_COMP","DT_ISTITUZ","DT_SOPPRES" 
  from SACER.DEC_TIPO_RAPPR_COMP where DT_SOPPRES >= (CURRENT_DATE) and DT_ISTITUZ <= (CURRENT_DATE);

-- changeset root:1753259610914-14
CREATE OR REPLACE FORCE VIEW "V_DEC_TIPO_STRUT_DOC" ("ID_TIPO_STRUT_DOC", "ID_STRUT", "NM_TIPO_STRUT_DOC", "DS_TIPO_STRUT_DOC", "DT_ISTITUZ", "DT_SOPPRES") AS select "ID_TIPO_STRUT_DOC","ID_STRUT","NM_TIPO_STRUT_DOC","DS_TIPO_STRUT_DOC","DT_ISTITUZ","DT_SOPPRES" 
  from SACER.DEC_TIPO_STRUT_DOC where DT_SOPPRES >= (CURRENT_DATE) and DT_ISTITUZ <= (CURRENT_DATE);

-- changeset root:1753259610914-15
CREATE OR REPLACE FORCE VIEW "V_DEC_TIPO_STRUT_UNITA_DOC" ("ID_TIPO_STRUT_UNITA_DOC", "ID_TIPO_UNITA_DOC", "NM_TIPO_STRUT_UNITA_DOC", "DS_TIPO_STRUT_UNITA_DOC", "DT_ISTITUZ", "DT_SOPPRES") AS select "ID_TIPO_STRUT_UNITA_DOC","ID_TIPO_UNITA_DOC","NM_TIPO_STRUT_UNITA_DOC","DS_TIPO_STRUT_UNITA_DOC","DT_ISTITUZ","DT_SOPPRES" 
  from SACER.DEC_TIPO_STRUT_UNITA_DOC where DT_SOPPRES >= (CURRENT_DATE) and DT_ISTITUZ <= (CURRENT_DATE);

-- changeset root:1753259610914-16
CREATE OR REPLACE FORCE VIEW "V_DEC_TIPO_UNITA_DOC_AMMESSO" ("ID_TIPO_UNITA_DOC_AMMESSO", "ID_TIPO_UNITA_DOC", "ID_REGISTRO_UNITA_DOC") AS select "ID_TIPO_UNITA_DOC_AMMESSO","ID_TIPO_UNITA_DOC","ID_REGISTRO_UNITA_DOC" 
  from SACER.DEC_TIPO_UNITA_DOC_AMMESSO;

-- changeset root:1753259610914-17
CREATE OR REPLACE FORCE VIEW "V_DEC_USO_FORMATO_FILE_STAND" ("ID_USO_FORMATO_FILE_AMMESSO", "ID_FORMATO_FILE_DOC", "NI_ORD_USO", "ID_FORMATO_FILE_STANDARD") AS select "ID_USO_FORMATO_FILE_AMMESSO","ID_FORMATO_FILE_DOC","NI_ORD_USO","ID_FORMATO_FILE_STANDARD" 
  from SACER.DEC_USO_FORMATO_FILE_STANDARD;

-- changeset root:1753259610914-18
CREATE OR REPLACE FORCE VIEW "V_DEC_XSD_ATTRIB_DATI_SPEC" ("ID_XSD_ATTRIB_DATI_SPEC", "ID_XSD_DATI_SPEC", "ID_ATTRIB_DATI_SPEC", "NI_ORD_ATTRIB") AS select "ID_XSD_ATTRIB_DATI_SPEC","ID_XSD_DATI_SPEC","ID_ATTRIB_DATI_SPEC","NI_ORD_ATTRIB" 
  from SACER.DEC_XSD_ATTRIB_DATI_SPEC;

-- changeset root:1753259610914-19
CREATE OR REPLACE FORCE VIEW "V_DEC_XSD_DATI_SPEC" ("ID_XSD_DATI_SPEC", "ID_STRUT", "TI_USO_XSD", "TI_ENTITA_SACER", "ID_TIPO_UNITA_DOC", "ID_TIPO_DOC", "ID_TIPO_COMP_DOC", "NM_SISTEMA_MIGRAZ", "CD_VERSIONE_XSD", "DT_ISTITUZ", "DT_SOPPRES", "BL_XSD") AS select 
  ID_XSD_DATI_SPEC,
  ID_STRUT,
  TI_USO_XSD,
  TI_ENTITA_SACER,
  ID_TIPO_UNITA_DOC,
  ID_TIPO_DOC,
  ID_TIPO_COMP_DOC,
  NM_SISTEMA_MIGRAZ,
  CD_VERSIONE_XSD,
  DT_ISTITUZ, 
  DT_SOPPRES,
  BL_XSD
 from SACER.DEC_XSD_DATI_SPEC
  WHERE DT_SOPPRES >= sysdate
  AND DT_ISTITUZ   <= sysdate;

-- changeset root:1753259610914-20
CREATE SEQUENCE PAR_SEQ_IDCOMPONENTE START WITH 1127 INCREMENT BY 1 MINVALUE 0 MAXVALUE 999999999999999999999999999 CACHE 5 NOORDER;

-- changeset root:1753259610914-21
CREATE SEQUENCE PAR_SEQ_IDCONFIG START WITH 41 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 NOORDER;

-- changeset root:1753259610914-22
CREATE SEQUENCE PAR_SEQ_IDFASCICOLO START WITH 51 INCREMENT BY 1 MINVALUE 0 MAXVALUE 999999999999999999999999999 CACHE 5 NOORDER;

-- changeset root:1753259610914-23
CREATE SEQUENCE PAR_SEQ_IDGENERALI START WITH 2701 INCREMENT BY 1 MINVALUE 0 MAXVALUE 999999999999999999999999999 CACHE 5 NOORDER;

-- changeset root:1753259610914-24
CREATE SEQUENCE PAR_SEQ_IDUNITADOC START WITH 450 INCREMENT BY 1 MINVALUE 0 MAXVALUE 999999999999999999999999999 CACHE 5 NOORDER;

-- changeset root:1753259610914-25 splitStatements:true
CREATE TABLE PAR_COLLEGAMENTO (IDCOLLEGAMENTO NUMBER(*, 0) NOT NULL, IDUNITADOC NUMBER(*, 0), ID_STRUT NUMBER, NUMERO VARCHAR2(20 BYTE) NOT NULL, ANNO NUMBER(4, 0), ID_REGISTRO_UNITA_DOC NUMBER, FLGSTATO NUMBER(*, 0) NOT NULL, DTINS date NOT NULL, DTAGG date NOT NULL, PGM VARCHAR2(50 BYTE) NOT NULL, ID NUMBER(*, 0) NOT NULL, DESCRIZIONE VARCHAR2(254 BYTE), CONSTRAINT SYS_C0010378 PRIMARY KEY (IDCOLLEGAMENTO));
COMMENT ON COLUMN PAR_COLLEGAMENTO.NUMERO IS '@Label("Numero")';
COMMENT ON COLUMN PAR_COLLEGAMENTO.ANNO IS '@Label("Anno")';

-- changeset root:1753259610914-26 splitStatements:true
CREATE TABLE PAR_COMPONENTE (IDDOCUMENTO NUMBER(*, 0) NOT NULL, IDUNITADOC NUMBER(*, 0) NOT NULL, IDCOMPONENTE NUMBER(*, 0) NOT NULL, URNFILE VARCHAR2(1024 BYTE), NOME VARCHAR2(254 BYTE), RIFNUMERO VARCHAR2(100 BYTE), RIFANNO NUMBER(4, 0), RIFTIPOREGISTRO VARCHAR2(100 BYTE), CODALLEGATO VARCHAR2(32 BYTE), FLGSTATO NUMBER(*, 0) NOT NULL, DTINS date NOT NULL, DTAGG date NOT NULL, PGM VARCHAR2(50 BYTE) NOT NULL, ID NUMBER(*, 0) NOT NULL, ID_FORMATO_FILE_DOC NUMBER(*, 0), ID_TIPO_COMP_DOC NUMBER(38, 0), FLGUTFIRMARIFERIMENTOTEMP NUMBER(1, 0), DATARIFERIMENTOTEMP date, BL_FILE_COMP BLOB, DESCRIFERIMENTOTEMP VARCHAR2(1024 BYTE), DS_HASH_FILE_VERS VARCHAR2(254 BYTE), CONSTRAINT SYS_C0010375 PRIMARY KEY (IDDOCUMENTO, IDUNITADOC, IDCOMPONENTE));
COMMENT ON COLUMN PAR_COMPONENTE.RIFNUMERO IS '@Label("Numero")';
COMMENT ON COLUMN PAR_COMPONENTE.RIFANNO IS '@Label("Anno")';
COMMENT ON COLUMN PAR_COMPONENTE.RIFTIPOREGISTRO IS 'Label("Tipo registro")';
COMMENT ON COLUMN PAR_COMPONENTE.CODALLEGATO IS '@FileBlob
@Label("File")';
COMMENT ON COLUMN PAR_COMPONENTE.FLGUTFIRMARIFERIMENTOTEMP IS '@Label("Utilizza Firma per Riferimento")';
COMMENT ON COLUMN PAR_COMPONENTE.DATARIFERIMENTOTEMP IS '@Label("Riferimento temporale")';

-- changeset root:1753259610914-27
CREATE TABLE PAR_CONFIGURAZIONE (IDCONFIGURAZIONE NUMBER NOT NULL, CHIAVE VARCHAR2(50 BYTE) NOT NULL, VALORE VARCHAR2(150 BYTE) NOT NULL, CONSTRAINT PAR_CONFIGURAZIONE_PK PRIMARY KEY (IDCONFIGURAZIONE));

-- changeset root:1753259610914-28
CREATE TABLE PAR_DATISPECIFICI (IDDATISPECIFICI NUMBER(*, 0) NOT NULL, IDUNITADOC NUMBER(*, 0), IDDOCUMENTO NUMBER(*, 0), ENTITASACER VARCHAR2(20 BYTE), IDCOMPONENTE NUMBER(*, 0), FLGSTATO NUMBER(*, 0) NOT NULL, DTINS date NOT NULL, DTAGG date NOT NULL, PGM VARCHAR2(50 BYTE) NOT NULL, ID NUMBER(*, 0) NOT NULL, CONSTRAINT SYS_C0010376 PRIMARY KEY (IDDATISPECIFICI));

-- changeset root:1753259610914-29 splitStatements:true
CREATE TABLE PAR_DOCUMENTO (IDDOCUMENTO NUMBER(*, 0) NOT NULL, IDUNITADOC NUMBER(*, 0) NOT NULL, ID_TIPO_DOC NUMBER, FLGSTATO NUMBER(*, 0) NOT NULL, DTINS date NOT NULL, DTAGG date NOT NULL, PGM VARCHAR2(50 BYTE) NOT NULL, ID NUMBER(*, 0) NOT NULL, PROFILOAUTOREDOC VARCHAR2(254 BYTE), PROFILODESCRIZIONEDOC VARCHAR2(1024 BYTE), DFDENOMINAZIONE VARCHAR2(254 BYTE), DFCOGNOME VARCHAR2(100 BYTE), DFNOME VARCHAR2(100 BYTE), DFCODFISCALE VARCHAR2(16 BYTE), DFPIVA VARCHAR2(11 BYTE), DFDTEMISSIONE date, DFPROGRESSIVO NUMBER(*, 0), DFREGISTRO VARCHAR2(100 BYTE), DFPERIODO VARCHAR2(100 BYTE), DFDTTERMINEEMISSIONE date, TIPOLOGIA VARCHAR2(20 BYTE), CD_VERSIONE_XSD VARCHAR2(100 BYTE), ID_TIPO_STRUT_DOC NUMBER(38, 0), CONSTRAINT SYS_C0010374 PRIMARY KEY (IDDOCUMENTO, IDUNITADOC));
COMMENT ON COLUMN PAR_DOCUMENTO.ID_TIPO_DOC IS '@Label("Tipologia")';
COMMENT ON COLUMN PAR_DOCUMENTO.PROFILOAUTOREDOC IS '@Label("Autore")';
COMMENT ON COLUMN PAR_DOCUMENTO.PROFILODESCRIZIONEDOC IS '@Label("Descrizione")';
COMMENT ON COLUMN PAR_DOCUMENTO.TIPOLOGIA IS '@Label("Tipo documento allegato")
@Select (labels={"Documento Principale","Allegato", "Annotazione","Annesso"},values={"PRINC","ALLE","ANNO","ANNE"},displayMode=DisplayMode.DROPDOWN  )';

-- changeset root:1753259610914-30 splitStatements:true
CREATE TABLE PAR_FASCICOLO (IDFASCICOLO NUMBER(*, 0) NOT NULL, IDUNITADOC NUMBER(*, 0) NOT NULL, CODTIPOFASCICOLO VARCHAR2(20 BYTE), IDENTIFICATIVO VARCHAR2(100 BYTE), OGGETTO VARCHAR2(1024 BYTE), IDSOTTOFASCICOLO VARCHAR2(100 BYTE), OGGETTOSOTTOFASCICOLO VARCHAR2(1024 BYTE), CLASSIFICA VARCHAR2(254 BYTE), FLGSTATO NUMBER(*, 0) NOT NULL, DTINS date NOT NULL, DTAGG date NOT NULL, PGM VARCHAR2(50 BYTE) NOT NULL, ID NUMBER(*, 0) NOT NULL, CONSTRAINT SYS_C0010379 PRIMARY KEY (IDFASCICOLO, IDUNITADOC));
COMMENT ON COLUMN PAR_FASCICOLO.CODTIPOFASCICOLO IS '@Select (labels={"Fascicolo Principale","Fascicolo secondario"},values={"P","S"},displayMode=DisplayMode.DROPDOWN  )
@Label("Tipo fascicolo")';
COMMENT ON COLUMN PAR_FASCICOLO.IDENTIFICATIVO IS '@Label("Identificativo")
@RegExp(".+\\/[0-9]{4}\\/.+")';
COMMENT ON COLUMN PAR_FASCICOLO.OGGETTO IS '@Multiline
@Label("Oggetto")';
COMMENT ON COLUMN PAR_FASCICOLO.IDSOTTOFASCICOLO IS '@Label("Identificativo")
@RegExp(".+\\/[0-9]{4}\\/.+")';
COMMENT ON COLUMN PAR_FASCICOLO.OGGETTOSOTTOFASCICOLO IS '@Multiline
@Label("Oggetto")';
COMMENT ON COLUMN PAR_FASCICOLO.CLASSIFICA IS '@Label("Classifica")';

-- changeset root:1753259610914-31 splitStatements:true
CREATE TABLE PAR_UNITADOC (IDUNITADOC NUMBER(*, 0) NOT NULL, NUMERO VARCHAR2(20 BYTE) NOT NULL, VERSIONE VARCHAR2(100 BYTE) NOT NULL, ANNO NUMBER(4, 0), TIPOCONSERVAZIONE VARCHAR2(1 BYTE) DEFAULT 'S' NOT NULL, FLGSTATO NUMBER(*, 0) NOT NULL, DTINS date NOT NULL, DTAGG date NOT NULL, PGM VARCHAR2(50 BYTE) NOT NULL, ID NUMBER(*, 0) NOT NULL, FLGFORZACONSERVAZIONE NUMBER(1, 0), FLGFORZAACCETTAZIONE NUMBER(1, 0), FLGFORZACOLLEGAMENTO NUMBER(1, 0), OGGETTO VARCHAR2(1024 BYTE), DATA date, FLGCARTACEO NUMBER(*, 0), XMLRICHIESTA CLOB, XMLRISPOSTA CLOB, DATAVERSAMENTO TIMESTAMP(6), ESITOVERSAMENTO VARCHAR2(100 BYTE), FLGERROREREVISIONATO NUMBER(*, 0), NOTE CLOB, IDUTENTE NUMBER(*, 0), ID_STRUT NUMBER, ID_TIPO_UNITA_DOC NUMBER, ID_REGISTRO_UNITA_DOC NUMBER, STATO NUMBER(*, 0), CD_VERSIONE_XSD VARCHAR2(100 BYTE), CONSTRAINT SYS_C0010373 PRIMARY KEY (IDUNITADOC));
COMMENT ON COLUMN PAR_UNITADOC.NUMERO IS '@Label("Numero")';
COMMENT ON COLUMN PAR_UNITADOC.ANNO IS '@Label("Anno")';
COMMENT ON COLUMN PAR_UNITADOC.TIPOCONSERVAZIONE IS '@Label("Tipo conservazione")
@Select (labels={"Sostitutiva","Fiscale", "Migrazione"},values={"S","F","M"},displayMode=DisplayMode.DROPDOWN  )';
COMMENT ON COLUMN PAR_UNITADOC.FLGFORZACONSERVAZIONE IS '@Label("Forza conservazione")';
COMMENT ON COLUMN PAR_UNITADOC.FLGFORZAACCETTAZIONE IS '@Label("Forza accettazione")';
COMMENT ON COLUMN PAR_UNITADOC.FLGFORZACOLLEGAMENTO IS '@Label("Forza collegamento")';
COMMENT ON COLUMN PAR_UNITADOC.OGGETTO IS '@Label("Oggetto")
@Multiline';
COMMENT ON COLUMN PAR_UNITADOC.DATA IS '@Label("Data")';
COMMENT ON COLUMN PAR_UNITADOC.FLGCARTACEO IS '@Label("Cartaceo")';

-- changeset root:1753259610914-32
CREATE TABLE PAR_VALOREDATISPECIFICI (IDVALOREDATISPECIFICI NUMBER(*, 0) NOT NULL, IDDATISPECIFICI NUMBER(*, 0), VALORE VARCHAR2(4000 BYTE), FLGSTATO NUMBER(*, 0) NOT NULL, DTINS date NOT NULL, DTAGG date NOT NULL, PGM VARCHAR2(50 BYTE) NOT NULL, ID NUMBER(*, 0) NOT NULL, ID_STRUT NUMBER, ID_ATTRIB_DATI_SPEC NUMBER, CD_VERSIONE_XSD VARCHAR2(20 BYTE), CONSTRAINT SYS_C0010377 PRIMARY KEY (IDVALOREDATISPECIFICI));

-- changeset root:1753259610914-33
CREATE UNIQUE INDEX UQ_CONFIGURAZIONE_CHIAVE ON PAR_CONFIGURAZIONE(CHIAVE);

-- changeset root:1753259610914-34
ALTER TABLE PAR_CONFIGURAZIONE ADD CONSTRAINT UQ_CONFIGURAZIONE_CHIAVE UNIQUE (CHIAVE) USING INDEX UQ_CONFIGURAZIONE_CHIAVE;

-- changeset root:1753259610914-35
CREATE INDEX XIF1PAR_COLLEGAMENTO ON PAR_COLLEGAMENTO(IDUNITADOC);

-- changeset root:1753259610914-36
CREATE INDEX XIF1PAR_COMPONENTE ON PAR_COMPONENTE(IDDOCUMENTO, IDUNITADOC);

-- changeset root:1753259610914-37
CREATE INDEX XIF1PAR_DATISPECIFICI ON PAR_DATISPECIFICI(IDUNITADOC);

-- changeset root:1753259610914-38
CREATE INDEX XIF1PAR_DOCUMENTI ON PAR_DOCUMENTO(IDUNITADOC);

-- changeset root:1753259610914-39
CREATE INDEX XIF1PAR_FASCICOLO ON PAR_FASCICOLO(IDUNITADOC);

-- changeset root:1753259610914-40
CREATE INDEX XIF1PAR_UNITADOC ON PAR_UNITADOC(IDUTENTE, ID_STRUT);

-- changeset root:1753259610914-41
CREATE INDEX XIF1PAR_VALOREDATISPECIFICI ON PAR_VALOREDATISPECIFICI(IDDATISPECIFICI);

-- changeset root:1753259610914-42
CREATE INDEX XIF2PAR_DATISPECIFICI ON PAR_DATISPECIFICI(IDDOCUMENTO, IDUNITADOC);

-- changeset root:1753259610914-43
CREATE INDEX XIF3PAR_DATISPECIFICI ON PAR_DATISPECIFICI(IDDOCUMENTO, IDUNITADOC, IDCOMPONENTE);

-- changeset root:1753259610914-44
ALTER TABLE PAR_DOCUMENTO ADD CONSTRAINT SYS_C0011601 FOREIGN KEY (IDUNITADOC) REFERENCES PAR_UNITADOC (IDUNITADOC);

-- changeset root:1753259610914-45
ALTER TABLE PAR_COMPONENTE ADD CONSTRAINT SYS_C0011602 FOREIGN KEY (IDDOCUMENTO, IDUNITADOC) REFERENCES PAR_DOCUMENTO (IDDOCUMENTO, IDUNITADOC);

-- changeset root:1753259610914-46
ALTER TABLE PAR_DATISPECIFICI ADD CONSTRAINT SYS_C0011603 FOREIGN KEY (IDUNITADOC) REFERENCES PAR_UNITADOC (IDUNITADOC);

-- changeset root:1753259610914-47
ALTER TABLE PAR_DATISPECIFICI ADD CONSTRAINT SYS_C0011604 FOREIGN KEY (IDDOCUMENTO, IDUNITADOC) REFERENCES PAR_DOCUMENTO (IDDOCUMENTO, IDUNITADOC);

-- changeset root:1753259610914-48
ALTER TABLE PAR_DATISPECIFICI ADD CONSTRAINT SYS_C0011605 FOREIGN KEY (IDDOCUMENTO, IDUNITADOC, IDCOMPONENTE) REFERENCES PAR_COMPONENTE (IDDOCUMENTO, IDUNITADOC, IDCOMPONENTE);

-- changeset root:1753259610914-49
ALTER TABLE PAR_VALOREDATISPECIFICI ADD CONSTRAINT SYS_C0011606 FOREIGN KEY (IDDATISPECIFICI) REFERENCES PAR_DATISPECIFICI (IDDATISPECIFICI);

-- changeset root:1753259610914-50
ALTER TABLE PAR_COLLEGAMENTO ADD CONSTRAINT SYS_C0011607 FOREIGN KEY (IDUNITADOC) REFERENCES PAR_UNITADOC (IDUNITADOC);

-- changeset root:1753259610914-51
ALTER TABLE PAR_FASCICOLO ADD CONSTRAINT SYS_C0011608 FOREIGN KEY (IDUNITADOC) REFERENCES PAR_UNITADOC (IDUNITADOC);

