-- liquibase formatted sql

-- changeset root:1773338244522-56
CREATE TABLE MOVE_RECORD_LOG (COUNT_REC NUMBER NOT NULL, DATA TIMESTAMP(6), STATO_ELAB VARCHAR2(4000 BYTE), PROGRESS NUMBER);

-- changeset root:1773338244522-57
CREATE OR REPLACE FORCE VIEW MON_V_VIS_OBJ_OPT (ID_AMBIENTE_VERS, NM_AMBIENTE_VERS, ID_VERS, NM_VERS, ID_OBJECT, CD_KEY_OBJECT, ID_TIPO_OBJECT, NM_TIPO_OBJECT, NOTE, DS_INFO_OBJECT, TI_STATO_OBJECT, FL_RICH_ANNUL_TIMEOUT, ID_LAST_SESSIONE_INGEST, NI_UNITA_DOC_DA_VERS, NI_UNITA_DOC_VERS, NI_UNITA_DOC_VERS_OK, NI_UNITA_DOC_VERS_ERR, NI_UNITA_DOC_VERS_TIMEOUT, DT_APERTURA, DT_CHIUSURA, FL_FORZA_WARNING, FL_FORZA_ACCETTAZIONE, DL_MOTIVO_FORZA_ACCETTAZIONE, DL_MOTIVO_CHIUSO_WARNING, CD_VERSIONE_XML_VERS, BL_XML, TI_STATO_VERIFICA_HASH, CD_VERS_GEN, CD_TRASF, CD_VERSIONE_TRASF, TI_GEST_OGGETTI_FIGLI, NI_UNITA_DOC_ATTESE, PG_OGGETTO_TRASF, TI_VERS_FILE, ID_AMBIENTE_VERS_PADRE, NM_AMBIENTE_VERS_PADRE, ID_VERS_PADRE, NM_VERS_PADRE, ID_OBJECT_PADRE, CD_KEY_OBJECT_PADRE, DS_OBJECT_PADRE, ID_TIPO_OBJECT_PADRE, NM_TIPO_OBJECT_PADRE, TI_STATO_OBJECT_PADRE, DT_STATO_COR_PADRE, NI_TOT_OBJECT_TRASF, ID_OBJECT_TRASF, TI_PRIORITA, TI_PRIORITA_VERSAMENTO, TI_CONTENUTO_TIPO_OGGETTO, NI_FASCICOLI_DA_VERS, NI_FASCICOLI_VERS, NI_FASCICOLI_VERS_OK, NI_FASCICOLI_VERS_ERR, NI_FASCICOLI_VERS_TIMEOUT, NM_USERID_VERS) AS SELECT vers.id_ambiente_vers
	,amb.nm_ambiente_vers
	,vers.id_vers
	,vers.nm_vers
	,obj.id_object
	,obj.cd_key_object
	,obj.id_tipo_object
	,ti_obj.nm_tipo_object
	,obj.note
	,CASE
        WHEN ti_obj.nm_tipo_object = 'StudioDicom' THEN
            'Paziente: ' || COALESCE(dicom.ds_patient_name, 'NON DEFINITO') ||
            ', nato il ' || COALESCE(TO_CHAR(dicom.dt_patient_birth_date,'dd/mm/yyyy'),'NON DEFINITO') ||
            ' Studio del ' || TO_CHAR(dicom.dt_study_date,'yyyy-mm-dd hh24:mi:ss')
        ELSE obj.ds_object
    END AS ds_info_object
	,CASE 
		WHEN ti_obj.ti_vers_file = 'DA_TRASFORMARE'
			THEN CASE 
					WHEN obj.ti_stato_object != 'VERSATO_A_PING'
						THEN CASE 
								WHEN obj.ti_stato_object != 'CHIUSO_OK'
									THEN obj.ti_stato_object
								ELSE CASE 
										WHEN EXISTS (
												SELECT 1
												FROM PIG_OBJECT obj_figlio
												WHERE obj_figlio.id_object_padre = obj.id_object
													AND obj_figlio.ti_stato_object IN ('CHIUSO_ERR_SCHED','CHIUSO_ERR_CODA','CHIUSO_ERR_VERS')
                                                FETCH FIRST 1 ROW ONLY
                                                )
											THEN 'CHIUSO_OK (PROBLEMA_VERS_SACER)'
										ELSE CASE 
												WHEN EXISTS (
														SELECT 1
														FROM PIG_UNITA_DOC_OBJECT ud
														JOIN PIG_OBJECT figlio ON figlio.id_object_padre = obj.id_object AND ud.id_object = figlio.id_object
														WHERE 
                                                            ti_stato_unita_doc_object = 'VERSATA_ERR'
															AND cd_err_sacer IN ('UD-002','UD-002-001')
                                                            FETCH FIRST 1 ROW ONLY
                                                        )                                                    
													THEN 'CHIUSO_OK (WARNING_CHIAVE_DUPLICATA)'
												ELSE 'CHIUSO_OK'
												END
										END
								END
					ELSE CASE 
							WHEN EXISTS (
									SELECT 1
									FROM PIG_OBJECT figlio
									WHERE figlio.id_object_padre = obj.id_object
										AND figlio.ti_stato_object = 'IN_ATTESA_SCHED'
                                        FETCH FIRST 1 ROW ONLY
									)
								THEN 'VERSATO_A_PING'
							ELSE CASE 
									WHEN EXISTS (
											SELECT 1
											FROM PIG_OBJECT figlio
											WHERE figlio.id_object_padre = obj.id_object
												AND figlio.ti_stato_object IN ('CHIUSO_ERR_SCHED')
                                                FETCH FIRST 1 ROW ONLY
											)
										THEN 'VERSATO_A_PING (PROBLEMA_PREPARAZIONE_SIP)'
									ELSE CASE 
											WHEN EXISTS (
													SELECT 1
													FROM PIG_OBJECT figlio
													WHERE figlio.id_object_padre = obj.id_object
														AND figlio.ti_stato_object IN ('CHIUSO_ERR_CODA','CHIUSO_ERR_VERS')
                                                        FETCH FIRST 1 ROW ONLY
													)
												THEN 'VERSATO_A_PING (PROBLEMA_VERS_SACER)'
											ELSE 'VERSATO_A_PING (IN_CORSO_VERS_SACER)'
											END
									END
							END
					END
		ELSE CASE 
				WHEN obj.ti_stato_object = 'CHIUSO_OK'
					THEN CASE 
							WHEN EXISTS (
									SELECT 1
									FROM PIG_UNITA_DOC_OBJECT ud
									WHERE ud.id_object = obj.id_object
										AND	ti_stato_unita_doc_object = 'VERSATA_ERR'
                                        AND cd_err_sacer IN ('UD-002','UD-002-001')
                                        FETCH FIRST 1 ROW ONLY
									)
								THEN 'CHIUSO_OK (WARNING_CHIAVE_DUPLICATA)'
							ELSE obj.ti_stato_object
							END
				ELSE obj.ti_stato_object
				END
		END ti_stato_object
	,obj.fl_rich_annul_timeout
	,obj.id_last_sessione_ingest
    ,(
		SELECT count(*)
		FROM PIG_UNITA_DOC_OBJECT ud
		WHERE 
            ud.id_object = obj.id_object
	) ni_unita_doc_da_vers
	,(
		SELECT count(*)
		FROM PIG_UNITA_DOC_OBJECT ud
		WHERE ud.id_object = obj.id_object
			AND ti_stato_unita_doc_object IN ('VERSATA_OK','VERSATA_ERR','VERSATA_TIMEOUT')
    ) ni_unita_doc_vers
	,(
		SELECT count(*)
		FROM PIG_UNITA_DOC_OBJECT ud
		WHERE ud.id_object = obj.id_object 
        AND (ti_stato_unita_doc_object = 'VERSATA_OK' OR (ti_stato_unita_doc_object = 'VERSATA_ERR' AND cd_err_sacer IN ('UD-002','UD-002-001')))
    ) ni_unita_doc_vers_ok
	,(
		SELECT count(*)
		FROM PIG_UNITA_DOC_OBJECT ud
		WHERE ud.id_object = obj.id_object
			AND ti_stato_unita_doc_object = 'VERSATA_ERR' AND cd_err_sacer NOT IN ('UD-002','UD-002-001')
    ) ni_unita_doc_vers_err
	,(
		SELECT count(*)
		FROM PIG_UNITA_DOC_OBJECT ud
		WHERE ud.id_object = obj.id_object
			AND ti_stato_unita_doc_object = 'VERSATA_TIMEOUT'
	) ni_unita_doc_vers_timeout
	,ses.dt_apertura
	,ses.dt_chiusura
	,ses.fl_forza_warning
	,ses.fl_forza_accettazione
	,ses.dl_motivo_forza_accettazione
	,ses.dl_motivo_chiuso_warning
	,xml_obj.cd_versione_xml_vers
	,xml_obj.bl_xml
	,ses.ti_stato_verifica_hash
	,obj.cd_vers_gen
	,obj.cd_trasf
	,obj.cd_versione_trasf
	,obj.ti_gest_oggetti_figli
	,obj.ni_unita_doc_attese
	,obj.pg_oggetto_trasf
	,ti_obj.ti_vers_file
	,-- 		info su oggetto padre
	vers_padre.id_ambiente_vers id_ambiente_vers_padre
	,amb_padre.nm_ambiente_vers nm_ambiente_vers_padre
	,vers_padre.id_vers id_vers_padre
	,vers_padre.nm_vers nm_vers_padre
	,obj_padre.id_object id_object_padre
	,obj_padre.cd_key_object cd_key_object_padre
	,obj_padre.ds_object ds_object_padre
	,obj_padre.id_tipo_object id_tipo_object_padre
	,ti_obj_padre.nm_tipo_object nm_tipo_object_padre
	,CASE 
		WHEN obj_padre.ti_stato_object IS NOT NULL
			THEN CASE 
					WHEN obj_padre.ti_stato_object != 'VERSATO_A_PING'
						THEN CASE 
								WHEN obj_padre.ti_stato_object != 'CHIUSO_OK'
									THEN obj_padre.ti_stato_object
								ELSE CASE 
										WHEN EXISTS (
												SELECT 1
												FROM PIG_OBJECT obj_figlio
												WHERE obj_figlio.id_object_padre = obj_padre.id_object
													AND obj_figlio.ti_stato_object IN ('CHIUSO_ERR_SCHED','CHIUSO_ERR_CODA','CHIUSO_ERR_VERS')
                                                    FETCH FIRST 1 ROW ONLY
												)
											THEN 'CHIUSO_OK (PROBLEMA_VERS_SACER)'
										ELSE CASE 
												WHEN EXISTS (
														SELECT 1
														FROM PIG_UNITA_DOC_OBJECT ud
														INNER JOIN PIG_OBJECT figlio ON figlio.id_object_padre = obj_padre.id_object AND ud.id_object = figlio.id_object
														WHERE ti_stato_unita_doc_object = 'VERSATA_ERR'
                                                                AND cd_err_sacer IN ('UD-002','UD-002-001')
                                                        FETCH FIRST 1 ROW ONLY
                                                        )                                                
													THEN 'CHIUSO_OK (WARNING_CHIAVE_DUPLICATA)'
												ELSE 'CHIUSO_OK'
												END
										END
								END
					ELSE CASE 
							WHEN EXISTS (
									SELECT 1
									FROM PIG_OBJECT figlio
									WHERE figlio.id_object_padre = obj_padre.id_object
										AND figlio.ti_stato_object = 'IN_ATTESA_SCHED'
                                        FETCH FIRST 1 ROW ONLY
									)
								THEN 'VERSATO_A_PING'
							ELSE CASE 
									WHEN EXISTS (
											SELECT 1
											FROM PIG_OBJECT figlio
											WHERE figlio.id_object_padre = obj_padre.id_object
												AND figlio.ti_stato_object IN ('CHIUSO_ERR_SCHED','CHIUSO_ERR_CODA','CHIUSO_ERR_VERS')
                                                FETCH FIRST 1 ROW ONLY
                                            )
										THEN 'VERSATO_A_PING (PROBLEMA_VERS_SACER)'
									ELSE 'VERSATO_A_PING (IN_CORSO_VERS_SACER)'
									END
							END
					END
		ELSE NULL
		END ti_stato_object_padre
	,stato_cor_padre.ts_reg_stato dt_stato_cor_padre
	,obj_padre.ni_tot_object_trasf
	,--		info oggetto generato da trasformazione
	obj_trasf.id_object_trasf
	,obj.ti_priorita
	,obj.ti_priorita_versamento
	,ti_obj.ti_contenuto
	,(
		SELECT count(*)
		FROM PIG_FASCICOLO_OBJECT ud
		WHERE ud.id_object = obj.id_object
    ) ni_fascicoli_da_vers
	,(
		SELECT count(*)
		FROM PIG_FASCICOLO_OBJECT fascicolo
		WHERE fascicolo.id_object = obj.id_object
			AND ti_stato_fascicolo_object IN ('VERSATA_OK','VERSATA_ERR','VERSATA_TIMEOUT')
	) ni_fascicoli_vers
	,(
		SELECT count(*)
		FROM PIG_FASCICOLO_OBJECT fascicolo
		WHERE fascicolo.id_object = obj.id_object
			AND (ti_stato_fascicolo_object = 'VERSATA_OK' OR (ti_stato_fascicolo_object = 'VERSATA_ERR'	AND cd_err_sacer IN ('UD-002','UD-002-001')))            
	) ni_fascicoli_vers_ok
	,(
		SELECT count(*)
		FROM PIG_FASCICOLO_OBJECT fascicolo
		WHERE fascicolo.id_object = obj.id_object
			AND ti_stato_fascicolo_object = 'VERSATA_ERR'
			AND cd_err_sacer NOT IN ('UD-002','UD-002-001')
    ) ni_fascicoli_vers_err
	,(
		SELECT count(*)
		FROM PIG_FASCICOLO_OBJECT fascicolo
		WHERE fascicolo.id_object = obj.id_object
			AND ti_stato_fascicolo_object = 'VERSATA_TIMEOUT'
	) ni_fascicoli_vers_timeout
	,usr.nm_userid nm_userid_vers
FROM PIG_OBJECT obj
INNER JOIN PIG_VERS vers ON vers.id_vers = obj.id_vers
INNER JOIN PIG_AMBIENTE_VERS amb ON amb.id_ambiente_vers = vers.id_ambiente_vers
INNER JOIN PIG_TIPO_OBJECT ti_obj ON ti_obj.id_tipo_object = obj.id_tipo_object
INNER JOIN PIG_SESSIONE_INGEST ses ON ses.id_sessione_ingest = obj.id_last_sessione_ingest
INNER JOIN PIG_STATO_SESSIONE_INGEST stato_cor ON stato_cor.id_stato_sessione_ingest = ses.id_stato_sessione_ingest_cor
LEFT JOIN PIG_XML_OBJECT xml_obj ON xml_obj.id_object = obj.id_object
LEFT JOIN PIG_INFO_DICOM dicom ON dicom.id_object = obj.id_object
LEFT JOIN PIG_OBJECT obj_padre ON obj_padre.id_object = obj.id_object_padre
LEFT JOIN PIG_VERS vers_padre ON vers_padre.id_vers = obj_padre.id_vers
LEFT JOIN PIG_AMBIENTE_VERS amb_padre ON amb_padre.id_ambiente_vers = vers_padre.id_ambiente_vers
LEFT JOIN PIG_TIPO_OBJECT ti_obj_padre ON ti_obj_padre.id_tipo_object = obj_padre.id_tipo_object
LEFT JOIN PIG_SESSIONE_INGEST ses_padre ON ses_padre.id_sessione_ingest = obj_padre.id_last_sessione_ingest
LEFT JOIN PIG_STATO_SESSIONE_INGEST stato_cor_padre ON stato_cor_padre.id_stato_sessione_ingest = ses_padre.id_stato_sessione_ingest_cor
LEFT JOIN IAM_USER usr ON usr.id_user_iam = obj.id_user_iam
LEFT JOIN PIG_OBJECT_TRASF obj_trasf ON obj_trasf.cd_key_object_trasf = obj.cd_key_object AND obj_trasf.id_vers = obj.id_vers;

-- changeset root:1773338244522-58
CREATE TABLE PIG_FILE_OBJECT_OLD (ID_FILE_OBJECT NUMBER NOT NULL, ID_OBJECT NUMBER NOT NULL, NM_FILE_OBJECT VARCHAR2(100 BYTE) NOT NULL, ID_TIPO_FILE_OBJECT NUMBER NOT NULL, DS_HASH_FILE_VERS VARCHAR2(254 BYTE), TI_ALGO_HASH_FILE_VERS VARCHAR2(20 BYTE), CD_ENCODING_HASH_FILE_VERS VARCHAR2(100 BYTE), NI_SIZE_FILE_VERS NUMBER, NM_BUCKET VARCHAR2(100 BYTE), CD_KEY_FILE VARCHAR2(254 BYTE), CONSTRAINT PK_FILE_OBJ PRIMARY KEY (ID_FILE_OBJECT));

-- changeset root:1773338244522-59
CREATE TABLE PIG_INFO_DICOM_OLD (ID_INFO_DICOM NUMBER NOT NULL, ID_OBJECT NUMBER NOT NULL, ID_VERS NUMBER NOT NULL, CD_VERSIONE_DATI_SPEC_DICOM VARCHAR2(100 BYTE) NOT NULL, CD_AET_NODO_DICOM VARCHAR2(100 BYTE) NOT NULL, DL_LISTA_SOP_CLASS VARCHAR2(2048 BYTE), DT_STUDY_DATE date NOT NULL, DS_ACCESSION_NUMBER VARCHAR2(254 BYTE), DL_LISTA_MODALITY_IN_STUDY VARCHAR2(2048 BYTE), DS_INSTITUTION_NAME VARCHAR2(254 BYTE), DS_REF_PHYSICIAN_NAME VARCHAR2(254 BYTE), DL_STUDY_DESCRIPTION VARCHAR2(1024 BYTE), DS_PATIENT_NAME VARCHAR2(100 BYTE) NOT NULL, CD_PATIENT_ID VARCHAR2(100 BYTE) NOT NULL, CD_PATIENT_ID_ISSUER VARCHAR2(100 BYTE), DT_PATIENT_BIRTH_DATE date, TI_PATIENT_SEX CHAR(1 BYTE), DS_STUDY_INSTANCE_UID VARCHAR2(254 BYTE) NOT NULL, NI_STUDY_RELATED_SERIES NUMBER(5, 0) NOT NULL, NI_STUDY_RELATED_IMAGES NUMBER(5, 0) NOT NULL, DS_STUDY_ID VARCHAR2(254 BYTE), DT_PRESA_IN_CARICO date NOT NULL, BL_DCM_HASH_TXT CLOB NOT NULL, DS_DCM_HASH VARCHAR2(254 BYTE) NOT NULL, TI_ALGO_DCM_HASH VARCHAR2(20 BYTE) NOT NULL, CD_ENCODING_DCM_HASH VARCHAR2(100 BYTE) NOT NULL, BL_GLOBAL_HASH_TXT CLOB NOT NULL, DS_GLOBAL_HASH VARCHAR2(254 BYTE) NOT NULL, TI_ALGO_GLOBAL_HASH VARCHAR2(20 BYTE) NOT NULL, CD_ENCODING_GLOBAL_HASH VARCHAR2(100 BYTE) NOT NULL, DS_FILE_HASH VARCHAR2(254 BYTE) NOT NULL, TI_ALGO_FILE_HASH VARCHAR2(20 BYTE) NOT NULL, CD_ENCODING_FILE_HASH VARCHAR2(100 BYTE) NOT NULL, ID_XSD_SPEC NUMBER NOT NULL, CONSTRAINT PK_INFO_DICOM PRIMARY KEY (ID_INFO_DICOM));

-- changeset root:1773338244522-60
CREATE TABLE PIG_OBJECT_OLD (ID_OBJECT NUMBER NOT NULL, ID_VERS NUMBER NOT NULL, CD_KEY_OBJECT VARCHAR2(100 BYTE) NOT NULL, ID_TIPO_OBJECT NUMBER NOT NULL, ID_LAST_SESSIONE_INGEST NUMBER NOT NULL, TI_STATO_OBJECT VARCHAR2(30 BYTE) NOT NULL, FL_VERS_SACER_DA_RECUP CHAR(1 BYTE), MM_FIRST_SES NUMBER(6, 0) NOT NULL, ID_USER_IAM NUMBER, DS_OBJECT VARCHAR2(1024 BYTE), NI_UNITA_DOC_ATTESE NUMBER(5, 0), NI_TOT_OBJECT_TRASF NUMBER(3, 0), ID_OBJECT_PADRE NUMBER, PG_OGGETTO_TRASF NUMBER(3, 0), CD_TRASF VARCHAR2(100 BYTE), CD_VERSIONE_TRASF VARCHAR2(100 BYTE), CD_VERS_GEN VARCHAR2(100 BYTE), FL_RICH_ANNUL_TIMEOUT CHAR(1 BYTE), TI_GEST_OGGETTI_FIGLI VARCHAR2(20 BYTE), NOTE VARCHAR2(1024 BYTE), TI_PRIORITA VARCHAR2(20 CHAR), TI_PRIORITA_VERSAMENTO VARCHAR2(20 CHAR), CONSTRAINT PK_OBJ PRIMARY KEY (ID_OBJECT));

-- changeset root:1773338244522-61
CREATE TABLE PIG_OBJECT_TRASF_OLD (ID_OBJECT_TRASF NUMBER NOT NULL, ID_OBJECT NUMBER NOT NULL, CD_KEY_OBJECT_TRASF VARCHAR2(100 BYTE) NOT NULL, DS_OBJECT_TRASF VARCHAR2(1024 BYTE), ID_VERS NUMBER NOT NULL, ID_TIPO_OBJECT NUMBER NOT NULL, DS_PATH VARCHAR2(254 BYTE) NOT NULL, DS_HASH_FILE_VERS VARCHAR2(254 BYTE), TI_ALGO_HASH_FILE_VERS VARCHAR2(20 BYTE), CD_ENCODING_HASH_FILE_VERS VARCHAR2(100 BYTE), PG_OGGETTO_TRASF NUMBER(3, 0) NOT NULL, CD_ERR VARCHAR2(100 BYTE), DL_ERR VARCHAR2(1024 BYTE), CONSTRAINT PK_PIG_OBJECT_TRASF PRIMARY KEY (ID_OBJECT_TRASF));

-- changeset root:1773338244522-62
CREATE TABLE PIG_SESSIONE_INGEST_OLD (ID_SESSIONE_INGEST NUMBER NOT NULL, NM_AMBIENTE_VERS VARCHAR2(100 BYTE) NOT NULL, NM_VERS VARCHAR2(100 BYTE) NOT NULL, CD_KEY_OBJECT VARCHAR2(100 BYTE) NOT NULL, ID_VERS NUMBER, DT_APERTURA date NOT NULL, DT_CHIUSURA date, NM_TIPO_OBJECT VARCHAR2(100 BYTE), FL_FILE_CIFRATO CHAR(1 BYTE), FL_FORZA_ACCETTAZIONE CHAR(1 BYTE) DEFAULT '0', DL_MOTIVO_FORZA_ACCETTAZIONE VARCHAR2(1024 BYTE), CD_VERSIONE_XML_VERS VARCHAR2(100 BYTE), TI_STATO VARCHAR2(30 BYTE) NOT NULL, ID_OBJECT NUMBER, NI_UNITA_DOC_DA_VERS NUMBER, NI_UNITA_DOC_VERS NUMBER, CD_ERR VARCHAR2(100 BYTE), DL_ERR VARCHAR2(1024 BYTE), DL_MOTIVO_CHIUSO_WARNING VARCHAR2(1024 BYTE), NI_UNITA_DOC_VERS_OK NUMBER, NI_UNITA_DOC_VERS_ERR NUMBER, FL_FORZA_WARNING CHAR(1 BYTE), FL_SES_ERR_VERIF CHAR(1 BYTE), FL_SES_ERR_NON_RISOLUB CHAR(1 BYTE), NI_UNITA_DOC_VERS_TIMEOUT NUMBER, TI_STATO_VERIFICA_HASH VARCHAR2(20 BYTE), NM_AMBIENTE_VERS_PADRE VARCHAR2(100 BYTE), NM_VERS_PADRE VARCHAR2(100 BYTE), CD_KEY_OBJECT_PADRE VARCHAR2(100 BYTE), NI_UNITA_DOC_ATTESE NUMBER(5, 0), NI_TOT_OBJECT_TRASF NUMBER(3, 0), PG_OGGETTO_TRASF NUMBER(3, 0), DS_OBJECT VARCHAR2(1024 BYTE), ID_STATO_SESSIONE_INGEST_COR NUMBER, CD_TRASF VARCHAR2(100 BYTE), CD_VERSIONE_TRASF VARCHAR2(100 BYTE), CD_VERS_GEN VARCHAR2(100 BYTE), TI_GEST_OGGETTI_FIGLI VARCHAR2(20 BYTE), NOTE VARCHAR2(1024 BYTE), NM_REPORT_TRASF_OS VARCHAR2(200 BYTE), CONSTRAINT PK_SES_INGEST PRIMARY KEY (ID_SESSIONE_INGEST));

-- changeset root:1773338244522-63
CREATE TABLE PIG_SISMA_BCK (ID_SISMA NUMBER NOT NULL, TI_STATO VARCHAR2(40 CHAR) NOT NULL, OGGETTO VARCHAR2(300 BYTE), ANNO NUMBER(4, 0) NOT NULL, NUMERO VARCHAR2(20 CHAR) NOT NULL, DT_CREAZIONE date NOT NULL, ID_VERS NUMBER NOT NULL, DS_ERR VARCHAR2(300 CHAR), ID_USER_IAM NUMBER NOT NULL, CD_KEY VARCHAR2(50 CHAR) NOT NULL, CD_KEY_OS VARCHAR2(160 CHAR) NOT NULL, CD_ERR VARCHAR2(20 CHAR), DATA date NOT NULL, DT_STATO date, DS_DESCRIZIONE VARCHAR2(1024 BYTE), ID_SISMA_VAL_ATTO NUMBER NOT NULL, ANNO_AG NUMBER(4, 0), REGISTRO_AG VARCHAR2(60 CHAR), NUMERO_AG VARCHAR2(20 CHAR), DATA_AG date, ID_VERS_AG NUMBER, ID_SISMA_PROGETTI_AG NUMBER NOT NULL, ID_SISMA_FASE_PROGETTO NUMBER NOT NULL, ID_SISMA_STATO_PROGETTO NUMBER NOT NULL, CLASSIFICA VARCHAR2(100 BYTE), ID_FASCICOLO VARCHAR2(100 BYTE), OGGETTO_FASCICOLO VARCHAR2(100 BYTE), ID_SOTTOFASCICOLO VARCHAR2(100 BYTE), OGGETTO_SOTTOFASCICOLO VARCHAR2(100 BYTE), FL_INVIATO_A_ENTE VARCHAR2(1 BYTE) NOT NULL, FL_INTERVENTO_SOGGETTO_A_TUTELA VARCHAR2(1 BYTE), CLASSIFICA_AG VARCHAR2(100 BYTE), ID_FASCICOLO_AG VARCHAR2(100 BYTE), OGGETTO_FASCICOLO_AG VARCHAR2(100 BYTE), ID_SOTTOFASCICOLO_AG VARCHAR2(100 BYTE), OGGETTO_SOTTOFASCICOLO_AG VARCHAR2(100 BYTE));

-- changeset root:1773338244522-64
CREATE TABLE PIG_SISMA_PIANO_DOC_REQ_BKP (ID_SISMA_PIANO_DOC_REQ NUMBER NOT NULL, ID_PIG_SISMA_VAL_DOC NUMBER NOT NULL, FL_DOC_OBBLIGATORIO CHAR(1 CHAR), ID_SISMA_VAL_ATTO NUMBER NOT NULL);

-- changeset root:1773338244522-65
CREATE TABLE PIG_SISMA_VAL_ATTO_BCK (ID_SISMA_VAL_ATTO NUMBER NOT NULL, NM_TIPO_ATTO VARCHAR2(60 CHAR) NOT NULL, TI_TIPO_ATTO VARCHAR2(60 CHAR) NOT NULL, ID_SISMA_FASE_PROGETTO NUMBER NOT NULL);

-- changeset root:1773338244522-66
CREATE TABLE PIG_STATO_SESSIONE_INGEST_OLD (ID_STATO_SESSIONE_INGEST NUMBER NOT NULL, ID_SESSIONE_INGEST NUMBER NOT NULL, TI_STATO VARCHAR2(30 BYTE) NOT NULL, TS_REG_STATO TIMESTAMP(3) NOT NULL, CONSTRAINT PK_STATO_SES_INGEST PRIMARY KEY (ID_STATO_SESSIONE_INGEST));

-- changeset root:1773338244522-67
CREATE TABLE PIG_STRUM_URB_COLLEGAMENTI_BKP (ID_STRUM_URB_COLLEGAMENTI NUMBER NOT NULL, ID_STRUMENTI_URBANISTICI NUMBER NOT NULL, NUMERO VARCHAR2(20 CHAR), ANNO NUMBER, ID_STRUM_URB_PIANO_STATO NUMBER NOT NULL);

-- changeset root:1773338244522-68
CREATE TABLE PIG_TIPO_FILE_OBJECT_BCK_20231023 (ID_TIPO_FILE_OBJECT NUMBER, ID_TIPO_OBJECT NUMBER, NM_TIPO_FILE_OBJECT VARCHAR2(100 BYTE), DS_TIPO_FILE_OBJECT VARCHAR2(254 BYTE), FL_VERS_SACER_ASINC CHAR(1 BYTE), NM_TIPO_DOC_SACER VARCHAR2(100 BYTE), TI_DOC_SACER VARCHAR2(20 BYTE), NM_TIPO_STRUT_DOC_SACER VARCHAR2(100 BYTE), NM_TIPO_COMP_DOC_SACER VARCHAR2(100 BYTE), NM_FMT_FILE_VERS_SACER VARCHAR2(100 BYTE), FL_VER_FIRMA_FMT_SACER CHAR(1 BYTE), NM_FMT_FILE_CALC_SACER VARCHAR2(100 BYTE), DS_FMT_RAPPR_ESTESO_CALC_SACER VARCHAR2(254 BYTE), DS_FMT_RAPPR_CALC_SACER VARCHAR2(254 BYTE), FL_CALC_HASH_SACER CHAR(1 BYTE), TI_CALC_HASH_SACER VARCHAR2(20 BYTE));

-- changeset root:1773338244522-69
CREATE TABLE PIG_UNITA_DOC_OBJECT_OLD (ID_UNITA_DOC_OBJECT NUMBER NOT NULL, ID_OBJECT NUMBER NOT NULL, CD_REGISTRO_UNITA_DOC_SACER VARCHAR2(100 BYTE) NOT NULL, AA_UNITA_DOC_SACER NUMBER(4, 0) NOT NULL, CD_KEY_UNITA_DOC_SACER VARCHAR2(100 BYTE) NOT NULL, NI_SIZE_FILE_BYTE NUMBER NOT NULL, TI_STATO_UNITA_DOC_OBJECT VARCHAR2(25 BYTE) NOT NULL, CD_ERR_SACER VARCHAR2(100 BYTE), DL_ERR_SACER VARCHAR2(1024 BYTE), ID_ORGANIZ_IAM NUMBER, FL_VERS_SIMULATO CHAR(1 BYTE), CD_VER_WS_SACER VARCHAR2(100 BYTE), CONSTRAINT PK_UNI_DOC_OBJ PRIMARY KEY (ID_UNITA_DOC_OBJECT));

-- changeset root:1773338244522-70
CREATE TABLE PIG_UNITA_DOC_SESSIONE_OLD (ID_UNITA_DOC_SESSIONE NUMBER NOT NULL, ID_SESSIONE_INGEST NUMBER NOT NULL, CD_REGISTRO_UNITA_DOC_SACER VARCHAR2(100 BYTE) NOT NULL, AA_UNITA_DOC_SACER NUMBER(4, 0) NOT NULL, CD_KEY_UNITA_DOC_SACER VARCHAR2(100 BYTE) NOT NULL, TI_STATO_UNITA_DOC_SESSIONE VARCHAR2(25 BYTE) NOT NULL, NI_SIZE_FILE_BYTE NUMBER NOT NULL, CD_ERR_SACER VARCHAR2(100 BYTE), DL_ERR_SACER VARCHAR2(1024 BYTE), ID_ORGANIZ_IAM NUMBER, FL_VERS_SIMULATO CHAR(1 BYTE), CD_VER_WS_SACER VARCHAR2(100 BYTE), CONSTRAINT PK_UNI_DOC_SES PRIMARY KEY (ID_UNITA_DOC_SESSIONE));

-- changeset root:1773338244522-71
CREATE TABLE PIG_VALORE_PARAM_APPLIC_OLD_MULTIOS (ID_VALORE_PARAM_APPLIC NUMBER NOT NULL, ID_PARAM_APPLIC NUMBER NOT NULL, TI_APPART VARCHAR2(30 BYTE) NOT NULL, DS_VALORE_PARAM_APPLIC VARCHAR2(254 BYTE) NOT NULL, ID_AMBIENTE_VERS NUMBER, ID_VERS NUMBER, ID_TIPO_OBJECT NUMBER);

-- changeset root:1773338244522-72
CREATE TABLE PIG_XML_OBJECT_OLD (ID_XML_OBJECT NUMBER NOT NULL, ID_OBJECT NUMBER NOT NULL, CD_VERSIONE_XML_VERS VARCHAR2(100 BYTE) NOT NULL, BL_XML CLOB NOT NULL, CONSTRAINT PK_XML_OBJ PRIMARY KEY (ID_XML_OBJECT));

-- changeset root:1773338244522-73
CREATE TABLE PIG_XML_OBJECT_TRASF_OLD (ID_XML_OBJECT_TRASF NUMBER NOT NULL, ID_OBJECT_TRASF NUMBER NOT NULL, CD_VERSIONE_XML_VERS VARCHAR2(100 BYTE) NOT NULL, BL_XML CLOB NOT NULL, CONSTRAINT PK_XML_OBJ_TRASF PRIMARY KEY (ID_XML_OBJECT_TRASF));

-- changeset root:1773338244522-74
CREATE TABLE PIG_XML_SACER_UNITA_DOC_OLD (ID_XML_SACER_UNITA_DOC NUMBER NOT NULL, ID_UNITA_DOC_OBJECT NUMBER NOT NULL, TI_XML_SACER VARCHAR2(20 BYTE) NOT NULL, BL_XML_SACER CLOB NOT NULL, CONSTRAINT PK_XML_UNI_DOC PRIMARY KEY (ID_XML_SACER_UNITA_DOC));

-- changeset root:1773338244522-75
CREATE TABLE PIG_XML_SACER_UNITA_DOC_SES_OLD (ID_XML_SACER_UNITA_DOC_SES NUMBER NOT NULL, ID_UNITA_DOC_SESSIONE NUMBER NOT NULL, TI_XML_SACER VARCHAR2(20 BYTE) NOT NULL, BL_XML_SACER CLOB NOT NULL, CONSTRAINT PK_XML_UNI_DOC_SES PRIMARY KEY (ID_XML_SACER_UNITA_DOC_SES));

-- changeset root:1773338244522-76
CREATE TABLE PIG_XML_SESSIONE_INGEST_OLD (ID_XML_SESSIONE_INGEST NUMBER NOT NULL, ID_SESSIONE_INGEST NUMBER NOT NULL, BL_XML CLOB NOT NULL, CONSTRAINT PK_XML_SES_INGEST PRIMARY KEY (ID_XML_SESSIONE_INGEST));

-- changeset root:1773338244522-77
CREATE TABLE TMP_OBJ_SES_DA_RECUP (ID_OBJECT NUMBER NOT NULL, ID_LAST_SESSIONE_INGEST NUMBER NOT NULL, CD_KEY_OBJECT VARCHAR2(150 CHAR) NOT NULL, DL_ERR_SACER VARCHAR2(1024 BYTE));

-- changeset root:1773338244522-78
CREATE TABLE TMP_XSD (ID VARCHAR2(40 BYTE), XSD CLOB);

-- changeset root:1773338244522-79
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD ID_PUC NUMBER;

-- changeset root:1773338244522-80
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD NR_BURERT VARCHAR2(100 CHAR);

-- changeset root:1773338244522-81
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD DATA_BURERT date;

-- changeset root:1773338244522-82
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD REPERTORIO VARCHAR2(10 CHAR);

-- changeset root:1773338244522-83
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD ANNO_PROTOCOLLO NUMBER(4, 0);

-- changeset root:1773338244522-84
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD NR_PROTOCOLLO VARCHAR2(20 CHAR);

-- changeset root:1773338244522-85
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD DATA_PROTOCOLLO date;

-- changeset root:1773338244522-86
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD ID_VERS_UFFICIO NUMBER;

-- changeset root:1773338244522-87
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD FL_INVIATO_A_ENTE VARCHAR2(1 BYTE) DEFAULT '0' NOT NULL;

-- changeset root:1773338244522-88
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD CLASSIFICA_URB VARCHAR2(100 CHAR);

-- changeset root:1773338244522-89
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD ID_FASCICOLO_URB VARCHAR2(100 CHAR);

-- changeset root:1773338244522-90
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD OGGETTO_FASCICOLO_URB VARCHAR2(100 CHAR);

-- changeset root:1773338244522-91
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD ID_SOTTOFASCICOLO_URB VARCHAR2(100 CHAR);

-- changeset root:1773338244522-92
ALTER TABLE PIG_STRUMENTI_URBANISTICI ADD OGGETTO_SOTTOFASCICOLO_URB VARCHAR2(100 CHAR);

-- changeset root:1773338244522-93
CREATE UNIQUE INDEX UN_FILE_OBJ ON PIG_FILE_OBJECT_OLD(ID_OBJECT, NM_FILE_OBJECT);

-- changeset root:1773338244522-94
ALTER TABLE PIG_FILE_OBJECT_OLD ADD CONSTRAINT UN_FILE_OBJ UNIQUE (ID_OBJECT, NM_FILE_OBJECT) USING INDEX UN_FILE_OBJ;

-- changeset root:1773338244522-95
CREATE UNIQUE INDEX UN_INFO_DICOM ON PIG_INFO_DICOM_OLD(ID_OBJECT);

-- changeset root:1773338244522-96
ALTER TABLE PIG_INFO_DICOM_OLD ADD CONSTRAINT UN_INFO_DICOM UNIQUE (ID_OBJECT) USING INDEX UN_INFO_DICOM;

-- changeset root:1773338244522-97
CREATE UNIQUE INDEX UN_OBJ ON PIG_OBJECT_OLD(ID_VERS, CD_KEY_OBJECT);

-- changeset root:1773338244522-98
ALTER TABLE PIG_OBJECT_OLD ADD CONSTRAINT UN_OBJ UNIQUE (ID_VERS, CD_KEY_OBJECT) USING INDEX UN_OBJ;

-- changeset root:1773338244522-99
CREATE UNIQUE INDEX UN_OBJ_TRASF ON PIG_OBJECT_TRASF_OLD(ID_OBJECT, CD_KEY_OBJECT_TRASF);

-- changeset root:1773338244522-100
ALTER TABLE PIG_OBJECT_TRASF_OLD ADD CONSTRAINT UN_OBJ_TRASF UNIQUE (ID_OBJECT, CD_KEY_OBJECT_TRASF) USING INDEX UN_OBJ_TRASF;

-- changeset root:1773338244522-101
CREATE UNIQUE INDEX UN_OBJ_TRASF_PG ON PIG_OBJECT_TRASF_OLD(ID_OBJECT, PG_OGGETTO_TRASF);

-- changeset root:1773338244522-102
ALTER TABLE PIG_OBJECT_TRASF_OLD ADD CONSTRAINT UN_OBJ_TRASF_PG UNIQUE (ID_OBJECT, PG_OGGETTO_TRASF) USING INDEX UN_OBJ_TRASF_PG;

-- changeset root:1773338244522-103
CREATE UNIQUE INDEX UN_OBJ_TRASF_VERS ON PIG_OBJECT_TRASF_OLD(ID_VERS, CD_KEY_OBJECT_TRASF);

-- changeset root:1773338244522-104
ALTER TABLE PIG_OBJECT_TRASF_OLD ADD CONSTRAINT UN_OBJ_TRASF_VERS UNIQUE (ID_VERS, CD_KEY_OBJECT_TRASF) USING INDEX UN_OBJ_TRASF_VERS;

-- changeset root:1773338244522-105
CREATE UNIQUE INDEX UN_STATO_SES_INGEST ON PIG_STATO_SESSIONE_INGEST_OLD(ID_SESSIONE_INGEST, TS_REG_STATO);

-- changeset root:1773338244522-106
ALTER TABLE PIG_STATO_SESSIONE_INGEST_OLD ADD CONSTRAINT UN_STATO_SES_INGEST UNIQUE (ID_SESSIONE_INGEST, TS_REG_STATO) USING INDEX UN_STATO_SES_INGEST;

-- changeset root:1773338244522-107
CREATE UNIQUE INDEX UN_UNI_DOC_OBJ ON PIG_UNITA_DOC_OBJECT_OLD(ID_OBJECT, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER);

-- changeset root:1773338244522-108
ALTER TABLE PIG_UNITA_DOC_OBJECT_OLD ADD CONSTRAINT UN_UNI_DOC_OBJ UNIQUE (ID_OBJECT, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER) USING INDEX UN_UNI_DOC_OBJ;

-- changeset root:1773338244522-109
CREATE UNIQUE INDEX UN_UNI_DOC_SES ON PIG_UNITA_DOC_SESSIONE_OLD(ID_SESSIONE_INGEST, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER);

-- changeset root:1773338244522-110
ALTER TABLE PIG_UNITA_DOC_SESSIONE_OLD ADD CONSTRAINT UN_UNI_DOC_SES UNIQUE (ID_SESSIONE_INGEST, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER) USING INDEX UN_UNI_DOC_SES;

-- changeset root:1773338244522-111
CREATE UNIQUE INDEX UN_XML_OBJ ON PIG_XML_OBJECT_OLD(ID_OBJECT);

-- changeset root:1773338244522-112
ALTER TABLE PIG_XML_OBJECT_OLD ADD CONSTRAINT UN_XML_OBJ UNIQUE (ID_OBJECT) USING INDEX UN_XML_OBJ;

-- changeset root:1773338244522-113
CREATE UNIQUE INDEX UN_XML_OBJ_TRASF ON PIG_XML_OBJECT_TRASF_OLD(ID_OBJECT_TRASF);

-- changeset root:1773338244522-114
ALTER TABLE PIG_XML_OBJECT_TRASF_OLD ADD CONSTRAINT UN_XML_OBJ_TRASF UNIQUE (ID_OBJECT_TRASF) USING INDEX UN_XML_OBJ_TRASF;

-- changeset root:1773338244522-115
CREATE UNIQUE INDEX UN_XML_SES_INGEST ON PIG_XML_SESSIONE_INGEST_OLD(ID_SESSIONE_INGEST);

-- changeset root:1773338244522-116
ALTER TABLE PIG_XML_SESSIONE_INGEST_OLD ADD CONSTRAINT UN_XML_SES_INGEST UNIQUE (ID_SESSIONE_INGEST) USING INDEX UN_XML_SES_INGEST;

-- changeset root:1773338244522-117
CREATE UNIQUE INDEX UN_XML_UNI_DOC ON PIG_XML_SACER_UNITA_DOC_OLD(ID_UNITA_DOC_OBJECT, TI_XML_SACER);

-- changeset root:1773338244522-118
ALTER TABLE PIG_XML_SACER_UNITA_DOC_OLD ADD CONSTRAINT UN_XML_UNI_DOC UNIQUE (ID_UNITA_DOC_OBJECT, TI_XML_SACER) USING INDEX UN_XML_UNI_DOC;

-- changeset root:1773338244522-119
CREATE UNIQUE INDEX UN_XML_UNI_DOC_SES ON PIG_XML_SACER_UNITA_DOC_SES_OLD(ID_UNITA_DOC_SESSIONE, TI_XML_SACER);

-- changeset root:1773338244522-120
ALTER TABLE PIG_XML_SACER_UNITA_DOC_SES_OLD ADD CONSTRAINT UN_XML_UNI_DOC_SES UNIQUE (ID_UNITA_DOC_SESSIONE, TI_XML_SACER) USING INDEX UN_XML_UNI_DOC_SES;

-- changeset root:1773338244522-121
CREATE INDEX IDX_FILE_OBJ ON PIG_FILE_OBJECT_OLD(ID_OBJECT);

-- changeset root:1773338244522-122
CREATE INDEX IDX_INFO_DICOM_ACCESSION ON PIG_INFO_DICOM_OLD(ID_VERS, DS_ACCESSION_NUMBER);

-- changeset root:1773338244522-123
CREATE INDEX IDX_INFO_DICOM_COGN_PATIENT ON PIG_INFO_DICOM_OLD(ID_VERS, DS_PATIENT_NAME);

-- changeset root:1773338244522-124
CREATE INDEX IDX_INFO_DICOM_DCM_HASH ON PIG_INFO_DICOM_OLD(ID_VERS, DS_DCM_HASH);

-- changeset root:1773338244522-125
CREATE INDEX IDX_INFO_DICOM_ID_PATIENT ON PIG_INFO_DICOM_OLD(ID_VERS, CD_PATIENT_ID, CD_PATIENT_ID_ISSUER);

-- changeset root:1773338244522-126
CREATE INDEX IDX_INFO_DICOM_STUDY_TIME ON PIG_INFO_DICOM_OLD(ID_VERS, DT_STUDY_DATE);

-- changeset root:1773338244522-127
CREATE INDEX IDX_INFO_DICOM_STUDY_UID ON PIG_INFO_DICOM_OLD(ID_VERS, DS_STUDY_INSTANCE_UID);

-- changeset root:1773338244522-128
CREATE INDEX IDX_OBJ_PADRE ON PIG_OBJECT_OLD(ID_OBJECT_PADRE);

-- changeset root:1773338244522-129
CREATE INDEX IDX_OBJ_TIPO_OBJ ON PIG_OBJECT_OLD(ID_TIPO_OBJECT);

-- changeset root:1773338244522-130
CREATE INDEX IDX_OBJ_USR ON PIG_OBJECT_OLD(ID_USER_IAM);

-- changeset root:1773338244522-131
CREATE INDEX IDX_SES_INGEST_ID_OBJECT ON PIG_SESSIONE_INGEST_OLD(ID_OBJECT);

-- changeset root:1773338244522-132
CREATE INDEX IDX_SES_INGEST_KEY_OBJECT ON PIG_SESSIONE_INGEST_OLD(NM_AMBIENTE_VERS, NM_VERS, CD_KEY_OBJECT);

-- changeset root:1773338244522-133
CREATE INDEX IDX_SES_INGEST_KEY_VERS_OBJ ON PIG_SESSIONE_INGEST_OLD(ID_VERS, CD_KEY_OBJECT);

-- changeset root:1773338244522-134
CREATE INDEX IDX_SES_INGEST_STATO_COR ON PIG_SESSIONE_INGEST_OLD(ID_STATO_SESSIONE_INGEST_COR);

-- changeset root:1773338244522-135
CREATE INDEX IDX_SES_INGEST_VERS ON PIG_SESSIONE_INGEST_OLD(ID_VERS, TI_STATO);

-- changeset root:1773338244522-136
CREATE INDEX IDX_TEST ON PIG_UNITA_DOC_OBJECT(ID_OBJECT);

-- changeset root:1773338244522-137
CREATE INDEX IDX_UNITA_DOC_OBJ ON PIG_XML_SACER_UNITA_DOC_OLD(ID_UNITA_DOC_OBJECT);

-- changeset root:1773338244522-138
CREATE INDEX IDX_UNI_DOC_OBJ_ORGANIZ ON PIG_UNITA_DOC_OBJECT_OLD(ID_ORGANIZ_IAM);

-- changeset root:1773338244522-139
CREATE INDEX IDX_UNI_DOC_SES_ORGANIZ ON PIG_UNITA_DOC_SESSIONE_OLD(ID_ORGANIZ_IAM);

-- changeset root:1773338244522-140
ALTER TABLE PIG_FILE_OBJECT_OLD ADD CONSTRAINT FK_FILE_OBJ_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1773338244522-141
ALTER TABLE PIG_FILE_OBJECT_OLD ADD CONSTRAINT FK_FILE_OBJ_TI_FILE_OBJ FOREIGN KEY (ID_TIPO_FILE_OBJECT) REFERENCES PIG_TIPO_FILE_OBJECT (ID_TIPO_FILE_OBJECT);

-- changeset root:1773338244522-142
ALTER TABLE PIG_INFO_DICOM_OLD ADD CONSTRAINT FK_INFO_DICOM_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1773338244522-143
ALTER TABLE PIG_INFO_DICOM_OLD ADD CONSTRAINT FK_INFO_DICOM_XSD_SPEC FOREIGN KEY (ID_XSD_SPEC) REFERENCES PIG_XSD_DATI_SPEC (ID_XSD_SPEC);

-- changeset root:1773338244522-144
ALTER TABLE PIG_OBJECT_OLD ADD CONSTRAINT FK_OBJ_PADRE FOREIGN KEY (ID_OBJECT_PADRE) REFERENCES PIG_OBJECT_OLD (ID_OBJECT);

-- changeset root:1773338244522-145
ALTER TABLE PIG_OBJECT ADD CONSTRAINT FK_OBJ_PADRE_NEW FOREIGN KEY (ID_OBJECT_PADRE) REFERENCES PIG_OBJECT (ID_OBJECT);

-- changeset root:1773338244522-146
ALTER TABLE PIG_OBJECT_OLD ADD CONSTRAINT FK_OBJ_TI_OBJ FOREIGN KEY (ID_TIPO_OBJECT) REFERENCES PIG_TIPO_OBJECT (ID_TIPO_OBJECT);

-- changeset root:1773338244522-147
ALTER TABLE PIG_OBJECT ADD CONSTRAINT FK_OBJ_TI_OBJ_NEW FOREIGN KEY (ID_TIPO_OBJECT) REFERENCES PIG_TIPO_OBJECT (ID_TIPO_OBJECT);

-- changeset root:1773338244522-148
ALTER TABLE PIG_OBJECT_TRASF_OLD ADD CONSTRAINT FK_OBJ_TRASF_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1773338244522-149
ALTER TABLE PIG_OBJECT_TRASF_OLD ADD CONSTRAINT FK_OBJ_TRASF_TI_OBJ FOREIGN KEY (ID_TIPO_OBJECT) REFERENCES PIG_TIPO_OBJECT (ID_TIPO_OBJECT);

-- changeset root:1773338244522-150
ALTER TABLE PIG_OBJECT_TRASF_OLD ADD CONSTRAINT FK_OBJ_TRASF_VERS FOREIGN KEY (ID_VERS) REFERENCES PIG_VERS (ID_VERS) ON DELETE CASCADE;

-- changeset root:1773338244522-151
ALTER TABLE PIG_OBJECT_OLD ADD CONSTRAINT FK_OBJ_USR FOREIGN KEY (ID_USER_IAM) REFERENCES IAM_USER (ID_USER_IAM);

-- changeset root:1773338244522-152
ALTER TABLE PIG_OBJECT ADD CONSTRAINT FK_OBJ_USR_NEW FOREIGN KEY (ID_USER_IAM) REFERENCES IAM_USER (ID_USER_IAM);

-- changeset root:1773338244522-153
ALTER TABLE PIG_OBJECT_OLD ADD CONSTRAINT FK_OBJ_VERS FOREIGN KEY (ID_VERS) REFERENCES PIG_VERS (ID_VERS) ON DELETE CASCADE;

-- changeset root:1773338244522-154
ALTER TABLE PIG_OBJECT ADD CONSTRAINT FK_OBJ_VERS_NEW FOREIGN KEY (ID_VERS) REFERENCES PIG_VERS (ID_VERS) ON DELETE CASCADE;

-- changeset root:1773338244522-155
ALTER TABLE PIG_SESSIONE_INGEST_OLD ADD CONSTRAINT FK_SES_INGEST_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1773338244522-156
ALTER TABLE PIG_SESSIONE_INGEST_OLD ADD CONSTRAINT FK_SES_INGEST_VERS FOREIGN KEY (ID_VERS) REFERENCES PIG_VERS (ID_VERS) ON DELETE CASCADE;

-- changeset root:1773338244522-157
ALTER TABLE PIG_SESSIONE_RECUP ADD CONSTRAINT FK_SES_RECUP_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1773338244522-158
ALTER TABLE PIG_STATO_SESSIONE_INGEST_OLD ADD CONSTRAINT FK_STATO_SES_INGEST FOREIGN KEY (ID_SESSIONE_INGEST) REFERENCES PIG_SESSIONE_INGEST_OLD (ID_SESSIONE_INGEST) ON DELETE CASCADE;

-- changeset root:1773338244522-159
ALTER TABLE PIG_UNITA_DOC_OBJECT_OLD ADD CONSTRAINT FK_UNI_DOC_OBJ_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1773338244522-160
ALTER TABLE PIG_UNITA_DOC_OBJECT_OLD ADD CONSTRAINT FK_UNI_DOC_OBJ_ORG_IAM FOREIGN KEY (ID_ORGANIZ_IAM) REFERENCES SACER_IAM.USR_ORGANIZ_IAM (ID_ORGANIZ_IAM);

-- changeset root:1773338244522-161
ALTER TABLE PIG_UNITA_DOC_SESSIONE_OLD ADD CONSTRAINT FK_UNI_DOC_SES_ORG_IAM FOREIGN KEY (ID_ORGANIZ_IAM) REFERENCES SACER_IAM.USR_ORGANIZ_IAM (ID_ORGANIZ_IAM);

-- changeset root:1773338244522-162
ALTER TABLE PIG_UNITA_DOC_SESSIONE_OLD ADD CONSTRAINT FK_UNI_DOC_SES_SES_INGEST FOREIGN KEY (ID_SESSIONE_INGEST) REFERENCES PIG_SESSIONE_INGEST_OLD (ID_SESSIONE_INGEST) ON DELETE CASCADE;

-- changeset root:1773338244522-163
ALTER TABLE PIG_XML_OBJECT_OLD ADD CONSTRAINT FK_XML_OBJ_OBJ FOREIGN KEY (ID_OBJECT) REFERENCES PIG_OBJECT_OLD (ID_OBJECT) ON DELETE CASCADE;

-- changeset root:1773338244522-164
ALTER TABLE PIG_XML_OBJECT_TRASF_OLD ADD CONSTRAINT FK_XML_OBJ_TRASF FOREIGN KEY (ID_OBJECT_TRASF) REFERENCES PIG_OBJECT_TRASF_OLD (ID_OBJECT_TRASF) ON DELETE CASCADE;

-- changeset root:1773338244522-165
ALTER TABLE PIG_XML_OBJECT_TRASF_OLD ADD CONSTRAINT FK_XML_OBJ_TRASF_NEW FOREIGN KEY (ID_OBJECT_TRASF) REFERENCES PIG_OBJECT_TRASF (ID_OBJECT_TRASF) ON DELETE CASCADE;

-- changeset root:1773338244522-166
ALTER TABLE PIG_XML_SESSIONE_INGEST_OLD ADD CONSTRAINT FK_XML_SES_INGEST_SES_INGEST FOREIGN KEY (ID_SESSIONE_INGEST) REFERENCES PIG_SESSIONE_INGEST_OLD (ID_SESSIONE_INGEST) ON DELETE CASCADE;

-- changeset root:1773338244522-167
ALTER TABLE PIG_XML_SACER_UNITA_DOC_SES_OLD ADD CONSTRAINT FK_XML_UNI_DOC_SES FOREIGN KEY (ID_UNITA_DOC_SESSIONE) REFERENCES PIG_UNITA_DOC_SESSIONE_OLD (ID_UNITA_DOC_SESSIONE) ON DELETE CASCADE;

-- changeset root:1773338244522-168
ALTER TABLE PIG_XML_SACER_UNITA_DOC_OLD ADD CONSTRAINT FK_XML_UNI_DOC_UNI_DOC_OBJ FOREIGN KEY (ID_UNITA_DOC_OBJECT) REFERENCES PIG_UNITA_DOC_OBJECT_OLD (ID_UNITA_DOC_OBJECT) ON DELETE CASCADE;

-- changeset root:1773338244522-169
ALTER TABLE PIG_XML_SACER_UNITA_DOC ADD CONSTRAINT FK_XML_UNI_DOC_UNI_DOC_OBJ_NEW FOREIGN KEY (ID_UNITA_DOC_OBJECT) REFERENCES PIG_UNITA_DOC_OBJECT (ID_UNITA_DOC_OBJECT) ON DELETE CASCADE;

-- changeset root:1773338244522-170
ALTER TABLE PIG_XML_SACER_UNITA_DOC DROP CONSTRAINT UN_XML_UNI_DOC_NEW DROP INDEX;

-- changeset root:1773338244522-171
ALTER TABLE PIG_XML_SACER_UNITA_DOC_SES DROP CONSTRAINT UN_XML_UNI_DOC_SES_NEW DROP INDEX;

-- changeset root:1773338244522-172
DROP TABLE MD_APPLICATIONFILES;

-- changeset root:1773338244522-173
DROP TABLE MD_APPLICATIONS;

-- changeset root:1773338244522-174
DROP TABLE MD_CATALOGS;

-- changeset root:1773338244522-175
DROP TABLE MD_COLUMNS;

-- changeset root:1773338244522-176
DROP TABLE MD_CONNECTIONS;

-- changeset root:1773338244522-177
DROP TABLE MD_CONSTRAINTS;

-- changeset root:1773338244522-178
DROP TABLE MD_FILE_ARTIFACTS;

-- changeset root:1773338244522-179
DROP TABLE MD_GROUP_MEMBERS;

-- changeset root:1773338244522-180
DROP TABLE MD_INDEX_DETAILS;

-- changeset root:1773338244522-181
DROP TABLE MD_MIGR_PARAMETER;

-- changeset root:1773338244522-182
DROP TABLE MD_OTHER_OBJECTS;

-- changeset root:1773338244522-183
DROP TABLE MD_PARTITIONS;

-- changeset root:1773338244522-184
DROP TABLE MD_PROJECTS;

-- changeset root:1773338244522-185
DROP TABLE MD_REPOVERSIONS;

-- changeset root:1773338244522-186
DROP TABLE MD_SEQUENCES;

-- changeset root:1773338244522-187
DROP TABLE MD_TABLESPACES;

-- changeset root:1773338244522-188
DROP TABLE MD_USERS;

-- changeset root:1773338244522-189
DROP TABLE MD_USER_PRIVILEGES;

-- changeset root:1773338244522-190
ALTER TABLE PIG_SISMA_PIANO_DOC_REQ DROP PRIMARY KEY DROP INDEX;

-- changeset root:1773338244522-1
COMMENT ON COLUMN PIG_DEC_JOB_FOTO.DT_PROSSIMA_ATTIVAZIONE_FOTO IS 'Quando il job verrÃ  eseguito la prossima volta (se Ã¨ attivo).';

-- changeset root:1773338244522-2
ALTER TABLE PIG_SISMA_DOCUMENTI MODIFY NM_FILE_OS VARCHAR2(150 CHAR);

-- changeset root:1773338244522-3
COMMENT ON COLUMN PIG_DEC_JOB_FOTO.NM_NODO_ASSEGNATO_FOTO IS 'Nome del nodo del cluster su cui verrÃ  eseguito il job';

-- changeset root:1773338244522-4
ALTER TABLE PIG_OBJECT_TRASF DROP PRIMARY KEY DROP INDEX;

-- changeset root:1773338244522-5
CREATE UNIQUE INDEX PK_PIG_OBJECT_TRASF_NEW ON PIG_OBJECT_TRASF(ID_OBJECT_TRASF);

-- changeset root:1773338244522-6
ALTER TABLE PIG_OBJECT_TRASF ADD CONSTRAINT PK_PIG_OBJECT_TRASF_NEW PRIMARY KEY (ID_OBJECT_TRASF) USING INDEX PK_PIG_OBJECT_TRASF_NEW;

-- changeset root:1773338244522-7
ALTER TABLE PIG_XML_OBJECT_TRASF DROP PRIMARY KEY DROP INDEX;

-- changeset root:1773338244522-8
CREATE UNIQUE INDEX PK_XML_OBJ_TRASF_NEW ON PIG_XML_OBJECT_TRASF(ID_XML_OBJECT_TRASF);

-- changeset root:1773338244522-9
ALTER TABLE PIG_XML_OBJECT_TRASF ADD CONSTRAINT PK_XML_OBJ_TRASF_NEW PRIMARY KEY (ID_XML_OBJECT_TRASF) USING INDEX PK_XML_OBJ_TRASF_NEW;

-- changeset root:1773338244522-10
ALTER TABLE PIG_FILE_OBJECT DROP CONSTRAINT UN_FILE_OBJ_NEW DROP INDEX;

-- changeset root:1773338244522-11
CREATE UNIQUE INDEX UN_FILE_OBJ_NEW ON PIG_FILE_OBJECT(ID_OBJECT, NM_FILE_OBJECT);

-- changeset root:1773338244522-12
ALTER TABLE PIG_FILE_OBJECT ADD CONSTRAINT UN_FILE_OBJ_NEW UNIQUE (ID_OBJECT, NM_FILE_OBJECT) USING INDEX UN_FILE_OBJ_NEW;

-- changeset root:1773338244522-13
ALTER TABLE PIG_OBJECT_TRASF DROP CONSTRAINT UN_OBJ_TRASF_NEW DROP INDEX;

-- changeset root:1773338244522-14
CREATE UNIQUE INDEX UN_OBJ_TRASF_NEW ON PIG_OBJECT_TRASF(ID_OBJECT, CD_KEY_OBJECT_TRASF);

-- changeset root:1773338244522-15
ALTER TABLE PIG_OBJECT_TRASF ADD CONSTRAINT UN_OBJ_TRASF_NEW UNIQUE (ID_OBJECT, CD_KEY_OBJECT_TRASF) USING INDEX UN_OBJ_TRASF_NEW;

-- changeset root:1773338244522-16
ALTER TABLE PIG_OBJECT_TRASF DROP CONSTRAINT UN_OBJ_TRASF_PG_NEW DROP INDEX;

-- changeset root:1773338244522-17
CREATE UNIQUE INDEX UN_OBJ_TRASF_PG_NEW ON PIG_OBJECT_TRASF(ID_OBJECT, PG_OGGETTO_TRASF);

-- changeset root:1773338244522-18
ALTER TABLE PIG_OBJECT_TRASF ADD CONSTRAINT UN_OBJ_TRASF_PG_NEW UNIQUE (ID_OBJECT, PG_OGGETTO_TRASF) USING INDEX UN_OBJ_TRASF_PG_NEW;

-- changeset root:1773338244522-19
ALTER TABLE PIG_OBJECT_TRASF DROP CONSTRAINT UN_OBJ_TRASF_VERS_NEW DROP INDEX;

-- changeset root:1773338244522-20
CREATE UNIQUE INDEX UN_OBJ_TRASF_VERS_NEW ON PIG_OBJECT_TRASF(ID_VERS, CD_KEY_OBJECT_TRASF);

-- changeset root:1773338244522-21
ALTER TABLE PIG_OBJECT_TRASF ADD CONSTRAINT UN_OBJ_TRASF_VERS_NEW UNIQUE (ID_VERS, CD_KEY_OBJECT_TRASF) USING INDEX UN_OBJ_TRASF_VERS_NEW;

-- changeset root:1773338244522-22
ALTER TABLE PIG_UNITA_DOC_OBJECT DROP CONSTRAINT UN_UNI_DOC_OBJ_NEW DROP INDEX;

-- changeset root:1773338244522-23
CREATE UNIQUE INDEX UN_UNI_DOC_OBJ_NEW ON PIG_UNITA_DOC_OBJECT(ID_VERS, ID_OBJECT, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER);

-- changeset root:1773338244522-24
ALTER TABLE PIG_UNITA_DOC_OBJECT ADD CONSTRAINT UN_UNI_DOC_OBJ_NEW UNIQUE (ID_VERS, ID_OBJECT, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER) USING INDEX UN_UNI_DOC_OBJ_NEW;

-- changeset root:1773338244522-25
ALTER TABLE PIG_UNITA_DOC_SESSIONE DROP CONSTRAINT UN_UNI_DOC_SES_NEW DROP INDEX;

-- changeset root:1773338244522-26
CREATE UNIQUE INDEX UN_UNI_DOC_SES_NEW ON PIG_UNITA_DOC_SESSIONE(ID_SESSIONE_INGEST, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER);

-- changeset root:1773338244522-27
ALTER TABLE PIG_UNITA_DOC_SESSIONE ADD CONSTRAINT UN_UNI_DOC_SES_NEW UNIQUE (ID_SESSIONE_INGEST, CD_REGISTRO_UNITA_DOC_SACER, AA_UNITA_DOC_SACER, CD_KEY_UNITA_DOC_SACER) USING INDEX UN_UNI_DOC_SES_NEW;

-- changeset root:1773338244522-28
ALTER TABLE PIG_XML_OBJECT_TRASF DROP CONSTRAINT UN_XML_OBJ_TRASF_NEW DROP INDEX;

-- changeset root:1773338244522-29
CREATE UNIQUE INDEX UN_XML_OBJ_TRASF_NEW ON PIG_XML_OBJECT_TRASF(ID_OBJECT_TRASF);

-- changeset root:1773338244522-30
ALTER TABLE PIG_XML_OBJECT_TRASF ADD CONSTRAINT UN_XML_OBJ_TRASF_NEW UNIQUE (ID_OBJECT_TRASF) USING INDEX UN_XML_OBJ_TRASF_NEW;

-- changeset root:1773338244522-31
DROP INDEX IDX_OBJ_PADRE_NEW;

-- changeset root:1773338244522-32
CREATE INDEX IDX_OBJ_PADRE_NEW ON PIG_OBJECT(ID_OBJECT_PADRE);

-- changeset root:1773338244522-33
DROP INDEX IDX_SES_INGEST_STATO_COR_NEW;

-- changeset root:1773338244522-34
CREATE INDEX IDX_SES_INGEST_STATO_COR_NEW ON PIG_SESSIONE_INGEST(ID_STATO_SESSIONE_INGEST_COR);

-- changeset root:1773338244522-35
ALTER TABLE PIG_DEC_JOB_FOTO DROP PRIMARY KEY DROP INDEX;

-- changeset root:1773338244522-36
CREATE UNIQUE INDEX PK_JOB_FOTO ON PIG_DEC_JOB_FOTO(ID_JOB_FOTO);

-- changeset root:1773338244522-37
ALTER TABLE PIG_DEC_JOB_FOTO ADD CONSTRAINT PK_JOB_FOTO PRIMARY KEY (ID_JOB_FOTO) USING INDEX PK_JOB_FOTO;

-- changeset root:1773338244522-38
ALTER TABLE PIG_SESSIONE_INGEST DROP PRIMARY KEY DROP INDEX;

-- changeset root:1773338244522-39
CREATE UNIQUE INDEX PK_SES_INGEST_NEW ON PIG_SESSIONE_INGEST(ID_SESSIONE_INGEST);

-- changeset root:1773338244522-40
ALTER TABLE PIG_SESSIONE_INGEST ADD CONSTRAINT PK_SES_INGEST_NEW PRIMARY KEY (ID_SESSIONE_INGEST) USING INDEX PK_SES_INGEST_NEW;

-- changeset root:1773338244522-41
ALTER TABLE PIG_UNITA_DOC_SESSIONE DROP PRIMARY KEY DROP INDEX;

-- changeset root:1773338244522-42
CREATE UNIQUE INDEX PK_UNI_DOC_SES_NEW ON PIG_UNITA_DOC_SESSIONE(ID_UNITA_DOC_SESSIONE);

-- changeset root:1773338244522-43
ALTER TABLE PIG_UNITA_DOC_SESSIONE ADD CONSTRAINT PK_UNI_DOC_SES_NEW PRIMARY KEY (ID_UNITA_DOC_SESSIONE) USING INDEX PK_UNI_DOC_SES_NEW;

-- changeset root:1773338244522-44
ALTER TABLE PIG_XML_OBJECT DROP PRIMARY KEY DROP INDEX;

-- changeset root:1773338244522-45
CREATE UNIQUE INDEX PK_XML_OBJ_NEW ON PIG_XML_OBJECT(ID_XML_OBJECT);

-- changeset root:1773338244522-46
ALTER TABLE PIG_XML_OBJECT ADD CONSTRAINT PK_XML_OBJ_NEW PRIMARY KEY (ID_XML_OBJECT) USING INDEX PK_XML_OBJ_NEW;

-- changeset root:1773338244522-47
ALTER TABLE PIG_XML_SESSIONE_INGEST DROP PRIMARY KEY DROP INDEX;

-- changeset root:1773338244522-48
CREATE UNIQUE INDEX PK_XML_SES_INGEST_NEW ON PIG_XML_SESSIONE_INGEST(ID_XML_SESSIONE_INGEST);

-- changeset root:1773338244522-49
ALTER TABLE PIG_XML_SESSIONE_INGEST ADD CONSTRAINT PK_XML_SES_INGEST_NEW PRIMARY KEY (ID_XML_SESSIONE_INGEST) USING INDEX PK_XML_SES_INGEST_NEW;

-- changeset root:1773338244522-50
ALTER TABLE PIG_DEC_JOB_FOTO DROP CONSTRAINT UN_JOB_FOTO DROP INDEX;

-- changeset root:1773338244522-51
CREATE UNIQUE INDEX UN_JOB_FOTO ON PIG_DEC_JOB_FOTO(NM_JOB_FOTO);

-- changeset root:1773338244522-52
ALTER TABLE PIG_DEC_JOB_FOTO ADD CONSTRAINT UN_JOB_FOTO UNIQUE (NM_JOB_FOTO) USING INDEX UN_JOB_FOTO;

-- changeset root:1773338244522-53
CREATE OR REPLACE FORCE VIEW MON_V_VIS_OBJ (ID_AMBIENTE_VERS, NM_AMBIENTE_VERS, ID_VERS, NM_VERS, ID_OBJECT, CD_KEY_OBJECT, ID_TIPO_OBJECT, NM_TIPO_OBJECT, NOTE, DS_INFO_OBJECT, TI_STATO_OBJECT, FL_RICH_ANNUL_TIMEOUT, ID_LAST_SESSIONE_INGEST, NI_UNITA_DOC_DA_VERS, NI_UNITA_DOC_VERS, NI_UNITA_DOC_VERS_OK, NI_UNITA_DOC_VERS_ERR, NI_UNITA_DOC_VERS_TIMEOUT, DT_APERTURA, DT_CHIUSURA, FL_FORZA_WARNING, FL_FORZA_ACCETTAZIONE, DL_MOTIVO_FORZA_ACCETTAZIONE, DL_MOTIVO_CHIUSO_WARNING, CD_VERSIONE_XML_VERS, BL_XML, TI_STATO_VERIFICA_HASH, CD_VERS_GEN, CD_TRASF, CD_VERSIONE_TRASF, TI_GEST_OGGETTI_FIGLI, NI_UNITA_DOC_ATTESE, PG_OGGETTO_TRASF, TI_VERS_FILE, ID_AMBIENTE_VERS_PADRE, NM_AMBIENTE_VERS_PADRE, ID_VERS_PADRE, NM_VERS_PADRE, ID_OBJECT_PADRE, CD_KEY_OBJECT_PADRE, DS_OBJECT_PADRE, ID_TIPO_OBJECT_PADRE, NM_TIPO_OBJECT_PADRE, TI_STATO_OBJECT_PADRE, DT_STATO_COR_PADRE, NI_TOT_OBJECT_TRASF, ID_OBJECT_TRASF, TI_PRIORITA, TI_PRIORITA_VERSAMENTO, TI_CONTENUTO_TIPO_OGGETTO, NI_FASCICOLI_DA_VERS, NI_FASCICOLI_VERS, NI_FASCICOLI_VERS_OK, NI_FASCICOLI_VERS_ERR, NI_FASCICOLI_VERS_TIMEOUT, NM_USERID_VERS) AS WITH
/* Flag logici per OGGETTO */
obj_figli AS (
    SELECT
        id_object_padre,
        MAX(CASE WHEN ti_stato_object = 'CHIUSO_ERR_SCHED' THEN 1 END) AS esiste_err_sched,
        MAX(CASE WHEN ti_stato_object IN ('CHIUSO_ERR_CODA','CHIUSO_ERR_VERS') THEN 1 END) AS esiste_err_vers,
        MAX(CASE WHEN ti_stato_object IN ('IN_ATTESA_SCHED','IN_CODA_HASH') THEN 1 END) AS esiste_in_corso
    FROM PIG_OBJECT
    GROUP BY id_object_padre
),
ud_err AS (
    SELECT
        obj.id_object,
        obj.id_object_padre,
        MAX(CASE WHEN ti_stato_unita_doc_object = 'VERSATA_ERR' AND cd_err_sacer IN ('UD-002','UD-002-001') THEN 1 END) AS esiste_ud_dup
    FROM PIG_UNITA_DOC_OBJECT ud INNER JOIN PIG_OBJECT obj ON ud.id_object = obj.id_object
    GROUP BY obj.id_object, obj.id_object_padre
),
fasc_err AS (
    SELECT
        figlio.id_object,
        figlio.id_object_padre,
        MAX(CASE WHEN ti_stato_fascicolo_object = 'VERSATA_ERR' AND cd_err_sacer = 'FASC-001-001' THEN 1 END) esiste_fasc_dup
    FROM PIG_FASCICOLO_OBJECT fasc INNER JOIN PIG_OBJECT figlio ON fasc.id_object = figlio.id_object
    GROUP BY figlio.id_object, figlio.id_object_padre
),
/* Totali Unità Documentarie */
totale_ud AS (
    SELECT
        id_object,
        COUNT(*) ni_tot,
        SUM(CASE WHEN ti_stato_unita_doc_object IN ('VERSATA_OK','VERSATA_ERR','VERSATA_TIMEOUT') THEN 1 END) ni_vers,
        SUM(CASE WHEN ti_stato_unita_doc_object = 'VERSATA_OK' OR (ti_stato_unita_doc_object = 'VERSATA_ERR' AND cd_err_sacer IN ('UD-002','UD-002-001')) THEN 1 END) ni_vers_ok,
        SUM(CASE WHEN ti_stato_unita_doc_object = 'VERSATA_ERR' AND cd_err_sacer NOT IN ('UD-002','UD-002-001') THEN 1 END) ni_vers_err,
        SUM(CASE WHEN ti_stato_unita_doc_object = 'VERSATA_TIMEOUT' THEN 1 END) ni_vers_timeout
    FROM PIG_UNITA_DOC_OBJECT
    GROUP BY id_object
),
/* Totali Fascicoli */
totale_fascicoli AS (
    SELECT
        id_object,
        COUNT(*) ni_tot,
        SUM(CASE WHEN ti_stato_fascicolo_object IN ('VERSATA_OK','VERSATA_ERR','VERSATA_TIMEOUT') THEN 1 END) ni_vers,
        SUM(CASE WHEN ti_stato_fascicolo_object = 'VERSATA_OK' OR (ti_stato_fascicolo_object = 'VERSATA_ERR' AND cd_err_sacer IN ('UD-002','UD-002-001')) THEN 1 END) ni_vers_ok,
        SUM(CASE WHEN ti_stato_fascicolo_object = 'VERSATA_ERR' AND cd_err_sacer NOT IN ('UD-002','UD-002-001') THEN 1 END) ni_vers_err,
        SUM(CASE WHEN ti_stato_fascicolo_object = 'VERSATA_TIMEOUT' THEN 1 END) ni_vers_timeout
    FROM PIG_FASCICOLO_OBJECT
    GROUP BY id_object
)
SELECT
    /* Identificativi */
    vers.id_ambiente_vers,
    amb.nm_ambiente_vers,
    vers.id_vers,
    vers.nm_vers,
    obj.id_object,
    obj.cd_key_object,
    obj.id_tipo_object,
    ti_obj.nm_tipo_object,
    obj.note,
    /* Descrizione oggetto DICOM */
    CASE
        WHEN ti_obj.nm_tipo_object = 'StudioDicom' THEN
            'Paziente: ' || COALESCE(dicom.ds_patient_name, 'NON DEFINITO') ||
            ', nato il ' || COALESCE(TO_CHAR(dicom.dt_patient_birth_date,'dd/mm/yyyy'),'NON DEFINITO') ||
            ' Studio del ' || TO_CHAR(dicom.dt_study_date,'yyyy-mm-dd hh24:mi:ss')
        ELSE obj.ds_object
    END AS ds_info_object,
    /* Stato oggetto (centralizzato) */
    CASE 
        WHEN ti_obj.ti_vers_file = 'DA_TRASFORMARE' THEN
            CASE WHEN obj.ti_stato_object <> 'VERSATO_A_PING' THEN
                CASE WHEN obj.ti_stato_object <> 'CHIUSO_OK' THEN obj.ti_stato_object
                ELSE
                    CASE WHEN flags.esiste_err_sched = 1 OR flags.esiste_err_vers = 1 THEN 'CHIUSO_OK (PROBLEMA_VERS_SACER)'
                    ELSE
                        CASE WHEN EXISTS (SELECT 1 FROM ud_err WHERE ud_err.id_object_padre = obj.id_object AND ud_err.esiste_ud_dup = 1) 
                               OR EXISTS (SELECT 1 FROM fasc_err WHERE fasc_err.id_object_padre = obj.id_object AND fasc_err.esiste_fasc_dup = 1) THEN 'CHIUSO_OK (WARNING_CHIAVE_DUPLICATA)'
                        ELSE
                            obj.ti_stato_object                                        
                        END
                    END
                END
            ELSE
                CASE 
                    WHEN flags.esiste_in_corso = 1 THEN 'VERSATO_A_PING'
                ELSE
                    CASE 
                        WHEN flags.esiste_err_sched = 1 THEN 'VERSATO_A_PING (PROBLEMA_PREPARAZIONE_SIP)'
                    ELSE
                        CASE 
                            WHEN flags.esiste_err_vers = 1 THEN 'VERSATO_A_PING (PROBLEMA_VERS_SACER)'
                        ELSE 'VERSATO_A_PING (IN_CORSO_VERS_SACER)'
                        END
                    END                        
                END
            END
    ELSE
        CASE 
            WHEN obj.ti_stato_object = 'CHIUSO_OK' THEN
                CASE 
                    WHEN ud_err.esiste_ud_dup = 1 OR fasc_err.esiste_fasc_dup = 1 THEN 'CHIUSO OK (WARNING_CHIAVE_DUPLICATA)'
                ELSE obj.ti_stato_object
                END                
        ELSE
            obj.ti_stato_object
        END
    END AS ti_stato_object,
    obj.fl_rich_annul_timeout,
    obj.id_last_sessione_ingest,
    COALESCE(t_ud.ni_tot,0) ni_unita_doc_da_vers,
    COALESCE(t_ud.ni_vers,0) ni_unita_doc_vers,
    COALESCE(t_ud.ni_vers_ok,0) ni_unita_doc_vers_ok,
    COALESCE(t_ud.ni_vers_err,0) ni_unita_doc_vers_err,
    COALESCE(t_ud.ni_vers_timeout,0) ni_unita_doc_vers_timeout,
    ses.dt_apertura,
    ses.dt_chiusura,
    ses.fl_forza_warning,
    ses.fl_forza_accettazione,
    ses.dl_motivo_forza_accettazione,
    ses.dl_motivo_chiuso_warning,
    xml_obj.cd_versione_xml_vers,
    xml_obj.bl_xml,
    ses.ti_stato_verifica_hash,
    obj.cd_vers_gen,
    obj.cd_trasf,
    obj.cd_versione_trasf,
    obj.ti_gest_oggetti_figli,
    obj.ni_unita_doc_attese,
    obj.pg_oggetto_trasf,
    ti_obj.ti_vers_file,
    /* Oggetto padre */
    vers_padre.id_ambiente_vers id_ambiente_vers_padre,
    amb_padre.nm_ambiente_vers nm_ambiente_vers_padre,
    vers_padre.id_vers id_vers_padre,
    vers_padre.nm_vers nm_vers_padre,
    obj_padre.id_object id_object_padre,
    obj_padre.cd_key_object cd_key_object_padre,
    obj_padre.ds_object ds_object_padre,
    obj_padre.id_tipo_object id_tipo_object_padre,
    ti_obj_padre.nm_tipo_object nm_tipo_object_padre,
    /* Stato padre = stessa logica */
    CASE WHEN obj_padre.id_object IS NOT NULL THEN
        CASE WHEN obj_padre.ti_stato_object <> 'VERSATO_A_PING' THEN
            CASE WHEN obj_padre.ti_stato_object <> 'CHIUSO_OK' THEN obj_padre.ti_stato_object
            ELSE
                CASE WHEN flags.esiste_err_sched = 1 OR flags.esiste_err_vers = 1 THEN 'CHIUSO_OK (PROBLEMA_VERS_SACER)'
                ELSE
                    CASE WHEN EXISTS (SELECT 1 FROM ud_err WHERE ud_err.id_object_padre = obj_padre.id_object AND ud_err.esiste_ud_dup = 1) 
                           OR EXISTS (SELECT 1 FROM fasc_err WHERE fasc_err.id_object_padre = obj_padre.id_object AND fasc_err.esiste_fasc_dup = 1) THEN 'CHIUSO_OK (WARNING_CHIAVE_DUPLICATA)'
                    ELSE obj.ti_stato_object
                    END
                END
            END
        ELSE
            CASE WHEN flags.esiste_in_corso = 1 THEN 'VERSATO_A_PING'
                 WHEN flags.esiste_err_sched = 1 OR flags.esiste_err_vers = 1 THEN 'VERSATO_A_PING (PROBLEMA_VERS_SACER)'
                 ELSE 'VERSATO_A_PING (IN_CORSO_VERS_SACER)'
            END
        END
    END AS ti_stato_object_padre,
    stato_cor_padre.ts_reg_stato dt_stato_cor_padre,
    obj_padre.ni_tot_object_trasf,
    obj_trasf.id_object_trasf,
    obj.ti_priorita,
    obj.ti_priorita_versamento,
    ti_obj.ti_contenuto,
    COALESCE(t_fasc.ni_tot,0) ni_fascicoli_da_vers,
    COALESCE(t_fasc.ni_vers,0) ni_fascicoli_vers,
    COALESCE(t_fasc.ni_vers_ok,0) ni_fascicoli_vers_ok,
    COALESCE(t_fasc.ni_vers_err,0) ni_fascicoli_vers_err,
    COALESCE(t_fasc.ni_vers_timeout,0) ni_fascicoli_vers_timeout,
    usr.nm_userid nm_userid_vers

FROM PIG_OBJECT obj
JOIN PIG_VERS vers ON vers.id_vers = obj.id_vers
JOIN PIG_AMBIENTE_VERS amb ON amb.id_ambiente_vers = vers.id_ambiente_vers
JOIN PIG_TIPO_OBJECT ti_obj ON ti_obj.id_tipo_object = obj.id_tipo_object
LEFT JOIN obj_figli flags ON flags.id_object_padre = obj.id_object
LEFT JOIN UD_ERR ud_err ON ud_err.id_object = obj.id_object
LEFT JOIN FASC_ERR fasc_err ON fasc_err.id_object = obj.id_object
LEFT JOIN totale_ud t_ud ON t_ud.id_object = obj.id_object
LEFT JOIN totale_fascicoli t_fasc ON t_fasc.id_object = obj.id_object
LEFT JOIN PIG_INFO_DICOM dicom ON dicom.id_object = obj.id_object
LEFT JOIN PIG_XML_OBJECT xml_obj ON xml_obj.id_object = obj.id_object
JOIN PIG_SESSIONE_INGEST ses ON ses.id_sessione_ingest = obj.id_last_sessione_ingest
LEFT JOIN PIG_OBJECT obj_padre ON obj_padre.id_object = obj.id_object_padre
LEFT JOIN PIG_VERS vers_padre ON vers_padre.id_vers = obj_padre.id_vers
LEFT JOIN PIG_AMBIENTE_VERS amb_padre ON amb_padre.id_ambiente_vers = vers_padre.id_ambiente_vers
LEFT JOIN PIG_TIPO_OBJECT ti_obj_padre ON ti_obj_padre.id_tipo_object = obj_padre.id_tipo_object
LEFT JOIN PIG_SESSIONE_INGEST ses_padre ON ses_padre.id_sessione_ingest = obj_padre.id_last_sessione_ingest
LEFT JOIN PIG_STATO_SESSIONE_INGEST stato_cor_padre ON stato_cor_padre.id_stato_sessione_ingest = ses_padre.id_stato_sessione_ingest_cor
LEFT JOIN IAM_USER usr ON usr.id_user_iam = obj.id_user_iam
LEFT JOIN PIG_OBJECT_TRASF obj_trasf ON obj_trasf.cd_key_object_trasf = obj.cd_key_object AND obj_trasf.id_vers = obj.id_vers;

-- changeset root:1773338244522-54
CREATE OR REPLACE FORCE VIEW MON_V_VIS_OBJ_TRASF (ID_OBJECT_TRASF, ID_VERS_TRASF, NM_AMBIENTE_VERS_TRASF, NM_VERS_TRASF, CD_KEY_OBJECT_TRASF, PG_OGGETTO_TRASF, NM_TIPO_OBJECT_TRASF, DS_OBJECT_TRASF, DS_PATH, DS_PATH_TRASF, DS_HASH_FILE_VERS, TI_ALGO_HASH_FILE_VERS, CD_ENCODING_HASH_FILE_VERS, TI_STATO_TRASF, CD_ERR, DL_ERR, NM_AMBIENTE_VERS_DA_TRASF, NM_VERS_DA_TRASF, ID_VERS_DA_TRASF, CD_KEY_OBJECT_DA_TRASF, ID_OBJECT_DA_TRASF, NM_TIPO_OBJECT_DA_TRASF, DS_OBJECT_DA_TRASF, NI_TOT_OBJECT_TRASF, TI_STATO_OBJECT_DA_TRASF, DT_STATO_COR_DA_TRASF) AS select
 obj_trasf.id_object_trasf,
 
 obj_trasf.id_vers id_vers_trasf,
 amb_trasf.nm_ambiente_vers  nm_ambiente_vers_trasf, vers_trasf.nm_vers nm_vers_trasf, obj_trasf.cd_key_object_trasf,
 obj_trasf.pg_oggetto_trasf,
 ti_obj_trasf.nm_tipo_object nm_tipo_object_trasf,
 obj_trasf.ds_object_trasf,
 obj_trasf.ds_path,
 
 --vers_trasf.ds_path_trasf,
 (select val.ds_valore_param_applic from PIG_PARAM_APPLIC par
join PIG_VALORE_PARAM_APPLIC val
	on (val.id_param_applic = par.id_param_applic)
where par.nm_param_applic = 'DS_PATH_OUTPUT_FTP' and val.id_vers = vers_trasf.id_vers),
 obj_trasf.ds_hash_file_vers,
 obj_trasf.ti_algo_hash_file_vers,
 obj_trasf.cd_encoding_hash_file_vers,

 obj.ti_stato_object ti_stato_trasf,
 obj_trasf.cd_err,
 obj_trasf.dl_err,
 
 
 amb_da_trasf.nm_ambiente_vers  nm_ambiente_vers_da_trasf, vers_da_trasf.nm_vers nm_vers_da_trasf, vers_da_trasf.id_vers id_vers_da_trasf, obj_da_trasf.cd_key_object cd_key_object_da_trasf,
 obj_da_trasf.id_object id_object_da_trasf,
 ti_obj_da_trasf.nm_tipo_object nm_tipo_object_da_trasf,
 obj_da_trasf.ds_object ds_object_da_trasf,
 obj_da_trasf.ni_tot_object_trasf,
 obj_da_trasf.ti_stato_object ti_stato_object_da_trasf,
 stato_da_trasf.ts_reg_stato dt_stato_cor_da_trasf
 
from PIG_OBJECT_TRASF obj_trasf
join PIG_TIPO_OBJECT ti_obj_trasf
 on (ti_obj_trasf.id_tipo_object = obj_trasf.id_tipo_object)
join PIG_VERS vers_trasf
 on (vers_trasf.id_vers = obj_trasf.id_vers)
join PIG_AMBIENTE_VERS amb_trasf
 on (amb_trasf.id_ambiente_vers = vers_trasf.id_ambiente_vers)
 
left join PIG_OBJECT obj
 on (obj.id_vers = obj_trasf.id_vers
 and obj.cd_key_object = obj_trasf.cd_key_object_trasf
 and obj.pg_oggetto_trasf  = obj_trasf.pg_oggetto_trasf)

join PIG_OBJECT obj_da_trasf
 on (obj_da_trasf.id_object = obj_trasf.id_object)
join PIG_TIPO_OBJECT ti_obj_da_trasf
 on (ti_obj_da_trasf.id_tipo_object = obj_da_trasf.id_tipo_object)
join PIG_VERS vers_da_trasf
 on (vers_da_trasf.id_vers = obj_da_trasf.id_vers)
join PIG_AMBIENTE_VERS amb_da_trasf
 on (amb_da_trasf.id_ambiente_vers = vers_da_trasf.id_ambiente_vers)
join PIG_SESSIONE_INGEST ses_da_trasf
 on (ses_da_trasf.id_sessione_ingest = obj_da_trasf.id_last_sessione_ingest)
join PIG_STATO_SESSIONE_INGEST stato_da_trasf
 on (stato_da_trasf.id_stato_sessione_ingest = ses_da_trasf.id_stato_sessione_ingest_cor);

-- changeset root:1773338244522-55
CREATE OR REPLACE FORCE VIEW PIG_V_SISMA_CHECKS (ID_SISMA, FL_VERIFICA_IN_CORSO, FL_VERIFICA_ERRATA, FL_FILE_MANCANTE) AS SELECT sISMA.id_SISMA,
       CASE
           WHEN EXISTS
                  (SELECT 1
                   FROM pig_SISMA_documenti docs
                   WHERE docs.id_SISMA = sISMA.id_SISMA
                     AND (docs.FL_ESITO_VERIFICA = '0'
                          AND docs.fl_deleted = '0')--                   (docs.FL_ESITO_VERIFICA = 1 AND docs.err_desc is not null AND docs.fl_deleted = 0) or
 ) THEN '1'
           ELSE '0'
       END AS "FL_VERIFICA_IN_CORSO",
       CASE
           WHEN EXISTS
                  (SELECT 1
                   FROM pig_SISMA_documenti docs
                   WHERE docs.id_SISMA = sISMA.id_SISMA
                     AND docs.FL_ESITO_VERIFICA = '1'
                     AND (docs.cd_err IS NOT NULL
                          OR docs.ds_err IS NOT NULL)
                     AND docs.fl_deleted = '0') THEN '1'
           ELSE '0'
       END AS "FL_VERIFICA_ERRATA",
       CASE
           WHEN EXISTS
                  (SELECT 1
                   FROM pig_sisma_piano_doc_req req
                   JOIN pig_sisma_fase_progetto fase_progetto ON (fase_progetto.id_sisma_fase_progetto = req.id_sisma_fase_progetto)
                   JOIN pig_sisma_val_doc doc ON (doc.id_sisma_val_doc = req.id_pig_sisma_val_doc)
                   WHERE req.id_sisma_fase_progetto = sisma.id_sisma_fase_progetto
                     AND req.fl_doc_obbligatorio = '1'
                     AND NOT EXISTS
                       (SELECT 1
                        FROM pig_sisma_documenti docs
                        WHERE docs.id_sisma = sisma.id_sisma
                          AND docs.fl_deleted = '0'
                          AND req.id_pig_sisma_val_doc = docs.id_sisma_val_doc)) THEN '1'
           ELSE '0'
       END AS "FL_FILE_MANCANTE"
FROM pig_SISMA SISMA;

